lib/features/steps/request_assertion_steps.rb
The Android mapping API request body does not necessarily have 6 parts (the overwrite flag can be conditionally included)
=> Remove restriction on api part count for mapping api

lib/features/steps/error_reporting_steps.rb, lib/features/steps/request_assertion_steps.rb, test/fixtures/sinatra-app/features/error_reporting.feature, test/fixtures/sinatra-app/features/fixtures/run_sinatra_app.sh
- Adds steps to verify that a given event parameter is a parsable time-in-seconds string
- Adds support for regex comparisons to be made
- Adds step for timestamp regex validation on payload parameters
=> feature: parsable time in seconds/timestamps

lib/features/support/docker.rb
- Adds -T flag to docker-compose exec calls to stop TTY related errors
This fixes an issue with docker-compose failing exec commands with the message `the input device is not a TTY`.  While I don't believe we need to worry about `tty` commands as any `execs` on containers should be running commands, not opening terminals.
Let me know if there may be a circumstance we won't want this flag and I can arg it out.
=> fix(docker): Disable TTY connection when using exec

lib/features/steps/request_assertion_steps.rb
The regex was too mangled to work correctly, so this converts the string back into a regex before calling `assert_match`
=> fix(payload regex): Ensure payload field regex checks work correctly

lib/features/support/env.rb
The first of probably a few PRs to get `maze-runner` running on Windows.
`/dev/null` is not a valid path on windows, this seems to be the equivalent.
=> Fix /dev/null output on windows

lib/features/support/env.rb
I'm not sure if there is a reason for using SIGHUP but this is not supported on windows. It doesn't seem like we need to care if the process gets a chance to clean up as it is just our test scripts running and is only called after the scenario.
Another potential solution for this is to split based on the OS and use `taskkill` or similar on windows
=> Fix signal usage

lib/features/support/env.rb
windows does not support the shebang that we use in the scripts so it needs to know how to execute the script. Passing `cmd /c` tells windows to use it's known file associations to execute this path. If ruby is installed on windows then it will know that `rb` files should be executed using ruby etc. It does mean that we need to use the correct file extension for the scripts that need to be able to run on windows
=> Fix script execution

lib/features/support/env.rb
A couple of tweaks that will allow the mock api server to recieve requests from Safari on BrowserStack and IE8/9.
=> Changes to mock server to support Safari (on BrowserStack) and IE8/9

lib/features/scripts/launch-android-app.sh
Adds a metadata flag which is passed to scenarios via ADB, allowing for multiple paths when running the same Scenario class
=> Add event metadata flag

lib/features/support/docker.rb, lib/features/support/env.rb
This method of setting ENV variables does not work on windows. 
We can let ruby set the env variables as part of the command so that we don't need to worry about the formatting of them for cross platform compatibility in the same way that `run_script` does
=> Improve ENV variable setting

lib/features/steps/error_reporting_steps.rb
I made this change backwards compatible so that it doesn't break anyone's tests.
Ruby didn't like this change though, until I added an argument for the regex capture, even though I knew I would never use it. I called it `_`  – is that idiomatic (or idotic 😂) Ruby? Or is there a better way in the regex to declare a sequence of characters as optional without capturing them?
=> Fix typo in request error_reporting_steps.rb

Gemfile.lock, README.md, Rakefile, bugsnag-maze-runner.gemspec
While adding changes to maze-runner I noticed that some of our setup is a little busted. This adds the following:
- Add rake dependency so that we can run the rake file
- Fix the rake file so that the default task works
- Update the readme to specify the right command to run the tests
=> Fix test setup

lib/features/support/env.rb
These dependencies get loaded later on by the `request_assertion_steps.rb` but my code calls the `run_command` function before that is loaded, causing a the following error:
```
undefined method `assert_true' for main:Object (NoMethodError)
```
One question, I don't know whether this should then be removed from `request_assertion_steps.rb`?
=> run_command needs assert_true so explicitly require it

lib/features/steps/error_reporting_steps.rb
We can already do:
```cucumber
And the "file" of stack frame 1 equals "/usr/src/app/node_modules/lodash/lodash.js"
```
This adds the ability to do:
```cucumber
And the "inProject" of stack frame 1 is false
And the "inProject" of stack frame 1 is true
And the "inProject" of stack frame 1 is null
And the "inProject" of stack frame 1 is not null
```
=> feat: Add "is {false|true|null|not null}" assertions to stack frame utils

lib/features/steps/session_tracking_steps.rb
Session payload steps were missing the integer matcher which the payload assertions have. I've tested this out locally in my project.
=> feat: Facilitate int matching on session payloads

README.md, lib/features/steps/session_tracking_steps.rb
In order to address https://github.com/bugsnag/bugsnag-js/pull/381#discussion_r208255754 I needed to make assertions against multiple session payloads in the same test. To do so, the session payload assertions needed the "for request n" suffix, so I added it to them all. It needed a little helper in the case were it wasn't passed in.
I also added this to the readme, as it wasn't mentioned there at all yet.
I used this branch with both the @bugsnag/node and @bugsnag/browser test suites, and they pass.
=> Session payload request index assertions

lib/features/steps/request_assertion_steps.rb
Adds a step to check that only 1 thread trace contains the 'errorReportingThread' boolean flag.
=> Check that only 1 thread uses the errorReportingThread flag

lib/features/steps/request_assertion_steps.rb
This changeset adds a step to verify that the error reporting flag only shows in one of the threads, by specifying the thread's ID, rather than its name. 
bugsnag-cocoa uses a sequential thread ID, and cannot serialise the name. Whereas the thread name will always be known ahead of time in the bugsnag-android scenario, and the ID will not.
=> Add error reporting thread step for cocoa

lib/features/steps/request_assertion_steps.rb
Cocoa serialises the thread ID as an integer, not a string, which means `the thread with id "(.+)"` step failed.
Coerced object to a string.
- Ran the mazerunner scenario on CI (pointed to this branch), ensuring that it now passes: https://travis-ci.org/bugsnag/bugsnag-cocoa/jobs/419114160#L951
- Ran the Android mazerunner scenario locally to ensure the `thread with name` step is not affected.
For the submitter, initial self-review:
- This pull request is ready for:
For the pull request reviewer(s), this changeset has been reviewed for:
=> Coerce thread id/name to a string, allowing comparison on cocoa

lib/features/steps/automation_steps.rb, lib/features/steps/compound_steps.rb, lib/features/support/env.rb
- Adds in compound steps used in several of the Server maze-tests, such as Ruby, Laravel & Python.
- Adds in `current_ip` support, that gives the current server host for allowing docker-containers to communicate.
=> Server steps: Add required commands for Ruby & Laravel server tests

lib/features/support/env.rb
Enable the `wait_for_response` method to deal with the `Errno::ECONNRESET` error caused when trying to access a docker container too early.
=> Rescue Reset: Add ECONNRESET to rescue

bugsnag-maze-runner.gemspec
Adds `appium_lib` to the dependencies, allowing mobile interaction on via `selenium-webdriver`.
=> Add appium_lib to dependencies

lib/features/steps/error_reporting_steps.rb, lib/features/steps/request_assertion_steps.rb
It's been found that the `payloadVersion` location in the body of an error payload isn't consistent across notifiers (and isn't supposed to be).
In JS notifiers each event should contain its own `payloadVersion`, which is reflected in the existing check and Error reporting API document on APIary.
In other notifiers, the `payloadVersion` should be a top level key in the payload, which is what all the other notifiers currently do.
This change enables the testing of either of these positions in the same step, and updates the error reporting API validation step to work on the Android (and other) notifiers.
=> Extend payloadVersion matching for different notifiers

lib/features/steps/app_automator_steps.rb, lib/features/support/app_automate_driver.rb, test/app_automate_driver_test.rb
Provides easier extending of the `wait_for_element` app automate method by returning `true` or `false` when waiting for an element and allowing the caller to determine how to handle the response, rather than raising a TimeoutError.
=> AppAutomateDriver: Better handling of Timeout errors

lib/features/support/env.rb
Prevents errors when writing failed requests to disk if the content-type is not JSON.
Tested locally, it continues to write JSON payloads to disk and doesn't fail when writing a non-JSON payload.
This is a simple fix, as a feature we could add a switch and parse different content-types differently (i.e. output formdata, ignore binary objects).
Replaces https://github.com/bugsnag/maze-runner/pull/64
=> Fix failed request write: Check content-type is JSON before writing

lib/features/support/app_automate_driver.rb, test/app_automate_driver_test.rb
Enables capabilities to be added to on a case-by-case basis, such as when needing to activate network or other kinds of logs on specific test runs.
=> Enable additional capabilities in Appium

Dockerfile, lib/features/support/docker.rb
Enables setting a compose project name for use in docker compose.  This allows multiple containers to be run from a single docker-compose file without interfering with one-another.
Example usage:
```ruby
Before do
Docker.compose_project_name = "#{rand.to_s}:#{Time.new.strftime("%s")}"
end
```
Required for the Ruby e2e tests move.
In addition, updates to a new version of docker-compose in the maze-runner image so that the `-a` flag can be used in `docker-compose ps` for debugging purposes.
=> Add project-name flag and update docker-compose image

DOCS.md, lib/features/steps/breadcrumb_steps.rb, lib/features/steps/error_reporting_steps.rb, test/fixtures/payload-helpers/features/breadcrumb_json_fixtures.feature, test/fixtures/payload-helpers/features/fixtures/breadcrumb_match.json, test/fixtures/payload-helpers/features/scripts/send_request.sh
This change moves the existing breadcrumb steps from error_reporting_steps.rb to their own file, breadcrumb_steps.rb.  In addition, it adds two new steps to enable easier testing of breadcrumbs:
- A step that tests that a breadcrumb with a particular type is not present within a payload, useful for testing both breadcrumb filtering and automatic breadcrumb configuration in notifiers such as JS
- A step that takes a JSON fixture and searches for a matching breadcrumb within a payload. This is useful for verifying the types of information and fields present in a breadcrumb without having to know the index of said breadcrumb.
In addition, this PR updates the step links to fit with the new docs generated by this PR, and adds some testing around the breadcrumb steps.
=> V2 breadcrumb step updates

.buildkite/pipeline.yml
When updating to v4.3.5 elastic stack CI buildkite agent we found that due to a change made to how commands inside of extensions are run we were essentially unable to use two docker-compose plugins within a single build step, as only the first one would actually run.
In response to this we've updated to the last version that doesn't include this change (4.3.4), and have ticketed updating the existing pipelines that would have issues caused by this change.
This PR re-arranges the maze-runner CI pipeline in order to work with the updated buildkite version.  It also provides a PoC and place for discussion of what changes would be required on other notifier pipelines.
Overall I don't believe these changes represent massive steps away from how the notifier pipelines are currently set up, but …
=> Buildkite agent updates: Prep for 4.3.5

DOCS.md, lib/features/support/logger.rb
- Lower default log level from `WARN` to `INFO` allowing `INFO` to be used for general information output
- Add the `QUIET` flag which will set the log level to `ERROR`, removing most of our output information
=> Info log level by default

dockerfiles/Dockerfile.ci
Adds 2 automatic retries when a step fails.  These retries work immediately without running to the end of the tests.
In addition, ensures the tests will exit on the first test failure.  These conditions work in conjunction, so the retries will occur immediately after a failing scenario, with the tests exiting if the failure occurs 3 times.
I've verified that this works manually, but the nature of the `fail-fast` tests mean that a solid test will potentially be difficult.  As this is an in-built feature of cucumber, I don't believe it is necessary to add exhaustive tests.
I can however add an integration test for the retries using a stateful fixture that will only pass after a number of retries.
=> Add retries and fast-failure to maze-runner

.buildkite/pipeline.yml
Fixes CI issues for branches with `/` in the name.
CI should pass!
=> CI: Use pre-sanitized 'BRANCH_NAME' for image tags

.gitignore, Dockerfile, Gemfile.lock, bugsnag-maze-runner.gemspec
Resolve security warning from Github due to outdated version of Rake.
Minimal set of changes possible made, as we are looking to promote the v2 branch asap.
rake update to 12.3.3 minimum
Gemfile.lock regenerated
Dockerfile updated to provide Bundler 2
Generated files added to .gitignore
Testing using existing unit tests and CI pipeline.
=> Update v1 to Rake 12.3.3

.gitignore, Gemfile.lock, bugsnag-maze-runner.gemspec, dockerfiles/Dockerfile.docs
Resolve security warning from Github due to outdated version of Rake.
Minimal set of changes made to resolve the security warning.
rake update to 12.3.3 minimum 
Gemfile.lock regenerated 
Dockerfile updated to provide Bundler 2 
Generated files added to .gitignore
Testing using existing unit tests and CI pipeline.
=> Update v2 to Rake 12.3.3

lib/features/steps/request_assertion_steps.rb, test/fixtures/request-test/Gemfile, test/fixtures/request-test/features/steps/scripting_steps.rb, test/fixtures/request-test/features/verify_request_steps.feature, test/integration/automation_test.rb
Adds a step for interrogating the HTTP_VERSION of a given request
Verified manually.
Added test fixture testing this step specifically.
To run:
`git checkout v1-add-http-versions`
`cd test/fixtures/request-test`
`bundle install`
`bundle exec maze-runner`
=> Add HTTP version step

Gemfile.lock, bugsnag-maze-runner.gemspec, dockerfiles/Dockerfile.ci
Two updates in this PR.
1) Update test-unit to prevent a warning being logged when running mazerunner
2) Remove the custom entrypoint that retries failures. If we want to do this it should be in the ci pipeline in the repo under test, as it is way more discoverable there. The merits of having it or not are a separate discussion that I believe has already happened, but having it baked in to the maze runner images means its hard to know that is why it is not running the full suite and its hard to disable it locally to opt out (you basically have to know you have to override the entrypoint).
=> V2 updates

bugsnag-maze-runner.gemspec
Removed limitation on Gem push host.
Maze Runner Gems must be pushed to rubygems.org in order that there is public read access for notifier repos to pull from.
=> Use rubygems.org as the push host

CHANGELOG.md, bugsnag-maze-runner.gemspec
This resolves an unfortunate but small diversion of v1 changes over the master and v1 branch.
Once this is merged, master will be retagged at 1.2.0 and the v1 branch deleted.
=> Resolve diversion of v1 work

.buildkite/pipeline.yml, .github/PULL_REQUEST_TEMPLATE.md, CHANGELOG.md
Prepare for the release of v2.0.0.
Pipeline pushes the Docker image tagged with the branch name on every build so that it can be tested in notifier pipelines pre-merge.
Once merged and a release is created in Github (which tags the repo), the Docker image is tagged with both the release version number and "latest", in order that clients can choose to either roll with the latest release or selectively upgrade.  (They can also ride the bleeding edge by using "master").
Changelog and pipeline updated ready for v2.0.0 release.
PR template updated to match Android as, whilst good intentioned, it was too onerous to complete.
I made and deleted a couple of fake releases of github to verify that the pipeline will be triggered.
=> V2 release

lib/features/support/app_automate_driver.rb
When testing some functionality that relies on the `BUILDKITE` environment variable it was discovered that the `empty?` and `nil?` guards on this code not only don't work correctly but cause an error to be thrown if the either of the variables in question are `nil`.
This change swaps the order of the `nil?` and `empty?` guards so that if the variable is `nil` the `empty?` call will not occur on the `nil` object, and the error won't be thrown.
It will allow us to define and test behaviour that depends on the presence of the `BUILDKITE` variable, although it should have minimal visible effect on the actual CI runs.
=> Ensure `nil?` is called before `empty?` on potentially `nil` variables

.buildkite/pipeline.yml, lib/features/steps/request_assertion_steps.rb, lib/features/support/diagnostics.rb, lib/features/support/logger.rb
The main objective of this PR is to provide better diagnostics whenever a scenario fails, but logging out all requests that were received.  This is an improvement on what we currently have, where we often have no useful output to analyse. 
Some peripheral changes have also been made to resolve Rubucop warnings - expect this to happen across forthcoming PRs as we visit different areas.
This is intended to be a quick win, but it can make the log noisy.  The plan will be to move the logging into files that get attached as downloadable artifacts in Buildkite steps.
New support file to manage diagnostic output. Warnings resolved in a couple of other files in the same area.
I've run the Cocoa tests against this branch locally and on CI to check behaviour and will encourage the use of `master` …
=> Improve diagnostics

CHANGELOG.md, lib/features/support/diagnostics.rb
Make the Maze Runner output easier to digest in Buildkite by using collapsed log sections for scenarios that pass.  For any scenarios that fail, the log is automatically expanded.
This approach use the Collapsing Log feature of Buildkite and works by simply outputting stylised text before each scenario (and after in the case of a fail).  `STDOUT.puts` is needed as Cucumber captures any output to normal `puts`, formatting it as test output and hence breaking the collapsing logs.
Run against a currently flaking Buildkite, observing that collapsing occurred as desired.
=> Collapse logs for passing scenarios

CHANGELOG.md, bin/bugsnag-maze-runner
Allow tests to be flaky by default when `--retry` is provided.
By default, MR will add the `--strict` option when calling Cucumber.  Except when:
- If any strict or no-strict option is provided to MR, no action is taken
- If `--retry` is given to MR then `--strict-undefined` and `--strict-pending` are added.
Tested locally by outputting the options passed to Cucumber and trying each combination of options.
=> Allow flaky tests by default when —retry is provided

CHANGELOG.md, lib/features/steps/app_automator_steps.rb, lib/features/support/app_automate_driver.rb
Increase default timeout for an element to be aware to 30s, for the cases where an app may be slower to load.
=> Allow timeout to be set when waiting for an element to be present

CHANGELOG.md, lib/features/steps/app_automator_steps.rb, lib/features/support/app_automate_driver.rb, test/fixtures/browserstack-app/features/handled_exception.feature
This adds a verification step that checks for different values based on the value of the `AppAutomatorDriver`s `os` capability.
This has four outcomes:
1. `$driver` isn't present as this isn't a BrowserStack app automation test, the step will automatically fail
2. The `os` value isn't present in the table, the step will automatically fail
3. & 4. Pass and fail depending on if the expected value matches the payload value
```
Then the event "exceptions.0.errorClass" matches the correct platform value:
| android | Java.lang.RuntimeException |
| ios         | NSException                           |
```
Added steps to the BrowserStack app feature for a positive outcome, tested negative outcomes manually
=> Add a step that matches different values for different BrowserStack OS's

CHANGELOG.md, lib/features/steps/app_automator_steps.rb, test/fixtures/browserstack-app/features/handled_exception.feature
Adds the ability to skip a step on a platform (useful for parameters such as `appVersionCode` which are Android specific).
This is accomplished by using the `@skip` keyword/tag inside of the value table, e.g.:
```
And the event "app.appVersionCode" matches the correct platform value:
| android | 1.0       |
| ios         | @skip |
```
Tested by adding the step to the BrowserStackApp test fixture.
=> Update platform comparison step to allow step skipping via keywords

.buildkite/pipeline.yml
Avoid changes to v1 overwriting the Docker images published for v2 releases, which use `latest-cli`.
Peer review, a passing CI and subsequent remedial actions for other pipelines should be sufficient to verify this.
=> [PLAT-4734] Push Docker images as v1 rather than latest, which conflicts with v2.

lib/features/steps/request_assertion_steps.rb
The build UUID field is asserted to be non-nil, but the API allows for it to be nullable. Previously the plugin always sent a request where the field was not null, but as part of the performance improvements this is no longer the case.
API docs: https://docs.bugsnag.com/api/android-mapping-upload/#for-proguard
=> Fix Android mapping API assertion as Build UUID not strictly required

.rubocop.yml, lib/features/steps/network_steps.rb, lib/features/steps/runner_steps.rb, lib/features/support/app_automate_driver.rb, lib/features/support/diagnostics.rb, lib/features/support/logger.rb, lib/features/support/runner.rb, lib/features/support/server.rb, lib/features/support/servlet.rb, test/app_automate_driver_test.rb
Reverts part of the previous PR, to go back to using a global variable for the logger.  Whilst testing the next branch based on that, I realised that the logger passed to the WEBrick server needs to be an instance of `Logger` (or a subclass of it) and so it had broken the server logging.
We could just keep with using the singleton instance `MazeLogger.instance` everywhere, but these seems unnecessarily verbose and that actually using a global variable is reasonable considering the nature of MazeRunner and how/where steps are written.  I've disabled the Rubcop rule on global variables on the basis that we can trust ourselves to use them appropriately.
This will be naturally tested further before release by the next change that is already in progress.
=> Revert to using global logger

CHANGELOG.md, lib/features/support/app_automate_driver.rb, test/fixtures/browserstack-app/features/support/env.rb
Reduces the chance that we get duplicate requests from the test fixture closing too quickly.  While this doesn't deterministically deal with the issue, it should provide some more resilience by allowing extra time for HTTP requests to resolve.
In order to use this method, `$driver.reset` calls in the `After` blocks that use AppAutomateDriver should be changed to `$driver.reset_app`
The 0.1 second default timeout is intended to allow HTTP requests in progress to resolve before the app is reset, while also being small enough that it shouldn't have a large impact on the overall runtime of tests.  This value is variable, so can be adjusted on a per notifier basis.
The intended use has been added to the browserstack test fixture.
=> [PLAT-3907] Add reset_app method with 0.1 second timeout by default

CHANGELOG.md, Gemfile.lock, lib/features/support/server.rb, lib/features/support/servlet.rb, lib/version.rb
Getting some errors caused by the mock Server class starting before the Servlet has been required by cucumber.  This explicitly makes sure the Servlet (and the logger) is required by the Server file.
In addition fixes an error was introduced in the Servlet where if the payload Body is `nil` when attempting to log the request the app would crash.
Also contains version updates and changelog entries for v2.3.1 release.
It runs and doesn't complain.
=> General fixes & v2.3.1 release

CHANGELOG.md, Gemfile.lock, lib/features/support/capabilities/devices.rb, lib/version.rb
Remove the explicit setting of appium_version on devices, as there is a suspicion that it acts against BrowserStack's management of Appium version use during their engineering investigations.
Tested in advance of release by running our JS and Android pipelines against it.
=> Do not explicitly set appium versions

.buildkite/pipeline.yml
Automatically trigger builds on our Android, Cocoa and JavaScript repos against the new `master` Maze Runner whenever it changes.  This will provide us with additional confidence in changes prior to making a new release, allowing us to move faster.  If a breaking change does occur, this approach will also allow us to more easily see which change was responsible.
I have set up a standard `maze-runner-master` branches on our Android, Cocoa and JavaScript notifiers that run tests using the latest `master-cli` Maze Runner Docker image.  When a change is merged to Maze Runner `master` (and only `master`), the pipeline will publish the new Docker image tagged with `master-cli` before triggering builds for each repository.
Possible drawbacks of this approach are:
- The need for special …
=> Trigger notifier pipelines against master updates

CHANGELOG.md, docker-compose.yml, lib/features/support/app_automate_driver.rb, test/app_automate_driver_test.rb, test/fixtures/browserstack-app/dockerfile, test/fixtures/comparison/Dockerfile
Use the `BRANCH_NAME` variable to avoid `/`s in branch names breaking CI.
Tested by CI, having included a `/` in this branch's name.
=> Use BRANCH_NAME throughout instead of BUILDKITE_BRANCH

.buildkite/pipeline.yml, CHANGELOG.md, docker-compose.yml, lib/features/hooks/hooks.rb, lib/features/steps/proxy_steps.rb, lib/features/support/.gitignore, lib/features/support/proxy.rb, test/fixtures/proxy/Dockerfile, test/fixtures/proxy/Gemfile, test/fixtures/proxy/features/fixtures/payload.json, test/fixtures/proxy/features/proxy.feature, test/fixtures/proxy/features/scripts/http.sh, test/fixtures/proxy/features/scripts/http_with_creds.sh, test/fixtures/proxy/features/scripts/https.sh, test/fixtures/proxy/features/scripts/https_with_creds.sh
Provides HTTP/S proxy functionality with and without basic authentication.
Having determined that the Ruby standard library provides support for HTTP/S proxies, it was the natural choice for implementing the functionality.  The proxy class is more than large enough to warrant its own file, although I have also deliberately avoided touching the existing `Server` class in the knowledge that it is being refactored as part of separating the Notify and Session endpoints.
New class for running a proxy on demand, supporting Cucumber steps and test scenarios.
Tested using a new set of "proxy" Cucumber scenarios, each driven my a simple `curl` command.
=> Add proxy functionality

.buildkite/pipeline.yml, CHANGELOG.md, lib/features/support/capabilities/devices.rb
Adds the full range of Android 6.0, 8.0 and 8.1 devices available on BrowaerStack.  The same could be done for other versions, it just hasn't been done at this stage.
I've created a new function to reduce the repetition in `devices.rb`.  The constant naming convention was agreed up-front and is the device name minus brand, upper-cased and spaces replaced with underscores.
Alternative devices added.
The existing CI pipeline is sufficient to prove that I've not broken ANDROID_6_0 through ANDROID_10_0 (to only ones currently in use) and I've informally tested the new entries using a bespoke build of our Android notifier.
=> Add additional Android devices to choose from

CHANGELOG.md, Gemfile.lock, lib/features/steps/build_api_steps.rb, lib/version.rb
The missing "And" from the beginning of these steps caused the following issue:
```
Then the request is valid for the Build API                                      # maze-runner-094befd98347/lib/features/steps/build_api_steps.rb:5
Parser errors:
(5:5): expected: #EOF, #TableRow, #DocStringSeparator, #StepLine, #TagLine, #ScenarioLine, #ScenarioOutlineLine, #Comment, #Empty, got 'the payload field "appVersion" is not null' (Gherkin::CompositeParserException)
features/abi_apk_splits.feature:7:in `Then the request is valid for the Build API'
```
This should fix it by making it parsable.
Will be tested with another project.  WIP will be removed then.
=> Fix broken build api step syntax

CHANGELOG.md, lib/features/hooks/hooks.rb, lib/features/support/logger.rb, lib/features/support/servlet.rb
Centralise logging of requests, allowing non-JSON, non-ASCII or just large requests to be handled without error and more meaningfully.  For example, file upload requests can easily swamp the log output and this approach allow us to put some limits and truncation in place.
The `LogUtil` class added can be made as sophisticated as we want, but for now the intention is to make logging something that is useful and, in particular, does not cause errors during the execution of a test.
Request logging routines refactored.
I've tested the branch using a currently failing Android Gradle Plugin test with DEBUG logging on.  This exercises both the logging of requests as they are received and at the end of failing scenario when Maze Runner outputs the requests that it received.  An extra unit test …
=> Fix logging of requests

UPGRADING.md, lib/features/hooks/hooks.rb, lib/features/steps/app_automator_steps.rb, lib/features/steps/breadcrumb_steps.rb, lib/features/steps/error_reporting_steps.rb, lib/features/steps/request_assertion_steps.rb, lib/features/steps/session_tracking_steps.rb, lib/features/steps/value_steps.rb, lib/features/support/request_list.rb, lib/features/support/server.rb, lib/features/support/servlet.rb, test/fixtures/browserstack-app/app/src/main/java/com/bugsnag/android/mazerunner/MainActivity.kt, test/fixtures/browserstack-app/features/handled_exception.feature, test/fixtures/comparison/features/compare_requests_json_fixtures.feature, test/fixtures/comparison/features/scripts/send_request.sh, test/fixtures/comparison/features/steps/scripting_steps.rb, test/fixtures/comparison/features/test_across_requests.feature, test/fixtures/comparison/features/test_unordered_requests.feature, test/fixtures/payload-helpers/features/breadcrumb_json_fixtures.feature, test/fixtures/payload-helpers/features/compare_requests_json_fixtures.feature, test/fixtures/payload-helpers/features/scripts/send_request.sh, test/fixtures/proxy/features/proxy.feature, test/fixtures/proxy/features/scripts/http.sh, test/fixtures/proxy/features/scripts/http_with_creds.sh, test/fixtures/proxy/features/scripts/https.sh, test/fixtures/proxy/features/scripts/https_with_creds.sh, test/request_list_test.rb, test/server_test.rb
Initial separation of the `session` and `notify` (error) endpoints in the `Server` class.
This change is definitely not complete (e.g. verification of sessions is currently completely unsupported), but I am trying to make reviews relatively manageable by working iteratively.  This iteration performs the initial separation of a single `requests` list into `sessions` and `errors` (for notify) in the `Server` class and `Servlet` is updated to be parameterised via a constructor, allowing separate instances to be mounted on `/notify` and `/sessions`.
Until I look more closely at the notifier repos, I'm unsure which Cucumber steps will be needed only for errors, which only apply to session and which might apply to both (and potentially others over time).  I've therefore tended to default to …
=> Separate endpoints for error and session requests

.buildkite/pipeline.yml, CHANGELOG.md, UPGRADING.md, bin/bugsnag-maze-runner, lib/features/hooks/hooks.rb, lib/features/support/configuration.rb, lib/features/support/maze_runner.rb, test/fixtures/browserstack-app/features/support/env.rb
Adds a new command line option that allows each Cucumber scenario to be run in its own Appium session.
This provides one option for dealing with underlying stability issues in Appium based test infrastructure.  It's not mandated and disabled by default, as there are potential drawbacks such as additional length of tests (which seems to vary depending on the device/OS version).
New command line option and associated handled.
New `Configuration` class to store options selected for later access.
New `MazeRunner` "binder" class, providing a central point for accessing features of MazeRunner - over time potentially removing the use of slightly messy global variables.
I've enabled the option on a few of the pipeline steps, so that we have some coverage of it both on and off.
=> Separate appium sessions

CHANGELOG.md, lib/features/support/capabilities/devices.rb
Corrects the Android version for the Galaxy Tab S3 on BrowserStack.
=> Correct Android version for device hash entry

.buildkite/pipeline.yml, CHANGELOG.md, UPGRADING.md, lib/features/hooks/hooks.rb, lib/features/steps/app_automator_steps.rb, lib/features/support/app_automate_driver.rb, lib/features/support/maze_runner.rb, lib/features/support/resilient_driver.rb, test/app_automate_driver_test.rb, test/fixtures/browserstack-app/features/support/env.rb
Provides resilience to flaky Appium sessions by handling exceptions on each method and restarting the driver.
It didn't seem possible to have a central method for catching all Appium exception, so I've gone for the next best option of adding a class whose single concern is to catch Appium errors of each method and restart the session.
- New `ResilientAppiumDriver` class.
- Addition of `driver` to the central `MazeRunner` class to avoid the need to use global `$driver`.
Our Cocoa notifier build suffers the most from flaking Appium session and I have shared internally the results of an extended soak test run against this.  It shows the exception handling code in action and no failed builds as a result.
As always with Maze Runner, tests will also be triggered automatically on our Cocoa, …
=> Resilient Appium driver

CHANGELOG.md, lib/features/support/app_automate_driver.rb, test/app_automate_driver_test.rb
Allow a path to the BrowserStackLocal binary to be provided in the environment.  
With this in place it is then possible to run Maze Runner locally under `bundle exec` only and not having to build or pull the Docker image first.  This makes using the tool much quicker to use and easier to develop for.
Simple change to Appium driver class.
Unit tests updated to show use of the environment, together with local testing.  Passing CI also shows the standard case continues to work.
=> Allow path to BrowserStackLocal binary to be provided in environment

CHANGELOG.md, lib/features/support/app_automate_driver.rb, test/app_automate_driver_test.rb
Avoids having to upload the same app to BrowserStack more than once.
Passing CI and unit tests sufficient to show that the standard case works.  Tested manually locally to verify that a BrowserStack URL can be specified.
=> Allow app location to be given by url

bin/bugsnag-maze-runner, lib/features/hooks/hooks.rb, lib/features/steps/app_automator_steps.rb, lib/features/support/configuration.rb, lib/features/support/maze_runner.rb, test/capabilities/devices_test.rb
Ensure that an intended OS version is provided, which is needed by notifier tests in order to know when annotated scenarios should be skipped.
I was hoping to extract the actual OS (or at least API) version from the device using Appium, but it doesn't seem to be possible to do this with both iOS and Android both locally and on BrowserStack.  I've therefore settled for ensuring that the intended OS version is specified (which is what we've been doing on BrowserStack all along, so it's not a regression in that respect).
I've started a new branch to move the CL option parsing into a separate file, which I'll raise a PR for in itself.  
CL option processing and device/OS configuration.
New unit test added to ensure that the `DEVICE_HASH` always contents a float-like OS version.  For now I …
=> Provide intended OS version

CHANGELOG.md, lib/features/hooks/hooks.rb, lib/features/support/appium_driver.rb, lib/features/support/browser_stack_utils.rb, lib/features/support/logger.rb, test/appium_driver_test.rb, test/browser_stack_utils_test.rb
Review the details logged when creating the Appium driver.
For now I've just logged the project (pipeline name) and a build UUID that can be used to get hold of device logs etc from BrowserStack (and a sensible link to the dashboard is now also logged).  Details of the device in use will be added in a subsequent PR, as extra work is needed to get that working for both BrowserStack and local devices.
Logging calls, including a new util to make use of Buildkite's ANSI escape sequence capability.
Unit testing and manual inspection of the new logs.
=> Update Appium driver logging

.buildkite/pipeline.yml
Push released Docker images to their own repository so that they don't get swept away.
Each repository has a limit of 300 images (according to the policy set).  Whilst maze-runner has its own repository, we hit the 300 quickly because we push for every branch.
We now have a separate repository specifically for Maze Runner releases.  Technically we'll hit the limit eventually, but not in a timeframe that will trouble us.
Pipeline.
Won't be fully tested until the next release.
=> Push release images to their own repo

CHANGELOG.md, Gemfile.lock, lib/features/hooks/hooks.rb, lib/version.rb
Do not clear all environment variables between scenarios.
A change was added towards the end of v2, in response to failures in the Bugsnag Anddroid Gradle Plugin pipeline caused by environment variables being carried across from one scenario to the next.  Whilst a good change in theory, it unfortunately broke the Ruby (and perhaps other) pipeline, as it relies on environment variables for the Ruby test version, etc.
As BAGP is still on v2, I have therefore simply removing the clearing for now and have raised an internal ticket to reintroduce it with more configurability, which in turn is linked to a ticket for updating the BAGP pipeline to v3.
Before scenario Cucumber hook.
Passing CI and we have separately verified that the change fixes the issues in the Ruby pipeline.
=> Do not clear environment

.buildkite/pipeline.yml, CHANGELOG.md, Gemfile.lock, lib/version.rb
Push the released Docker image to a separate ECR repository so that it doesn't get removed over time.
I have also removed the build steps relating to merges into `master` and publishing of docs, as v3 now overtakes that.  v2 will now only live on the `v2` branch.
Pipeline steps.
Covered by passing CI and subsequent verification that our notifier pipelines continue to work.
=> Preserve released Docker image and round off v2

CHANGELOG.md, Gemfile.lock, bin/bugsnag-maze-runner, lib/features/hooks/hooks.rb, lib/features/steps/app_automator_steps.rb, lib/features/support/configuration.rb, lib/features/support/maze_runner.rb, lib/version.rb, test/capabilities/devices_test.rb
This change re-applies and builds upon #145, where something very strange happened at some point post PR approval.  If you look at that PR, you can see comments on files that no longer show in the diff.  It appears that the bulk of the commits were lost from the PR somehow (perhaps, but only speculation, because #145 itself was a representation of #142 AND involved a revert PR!).  
As it transpires, the changes in #145 were not complete anyway and needed fixing for local run mode.  Basically it was a right mess, so this is a completely fresh branch manually recreating the changes necessary.  The following sections are from the original PR.
Ensure that an intended OS version is provided, which is needed by notifier tests in order to know when annotated scenarios should be skipped.
I was …
=> Re-add and fix OS version CL option

CHANGELOG.md, Gemfile.lock, bin/bugsnag-maze-runner, lib/features/hooks/hooks.rb, lib/features/support/configuration.rb, lib/features/support/resilient_driver.rb, lib/version.rb
Provides the ability to configure the Appium driver to locate elements by accessibility id.  This appears to be required for React Native and slipped through the cracks on the initial move to v3.
Following the existing pattern, a new command line switch is added and configuration set based on that.
Gem entry point, configuration and new (defaulted) parameter added to `ResilientAppiumDriver`.
The CI tests should be sufficient to guard against any regression and I have been running the React Native tests mostly successfully against the development image that gets pushed (the issues I'm seeing now do not relate to element location).
=> Allow elements to be located by accessibility id

.buildkite/pipeline.yml, CHANGELOG.md, bin/bugsnag-maze-runner, lib/features/hooks/hooks.rb, lib/features/support/capabilities/capabilities.rb, lib/features/support/configuration.rb
Adds a new command line option for specifying the Appium version capability when using BrowserStack.
Design follows the usual pattern of adding the option and pushing into configuration for later use.  I've also taken the opportunity to group options into BrowserStack, local and common use (making the diff look a little messier, I'm afraid).
New CL option and config.  Update to the `Capabilities` class.
I've specific Appium 1.17.0 on two of the CI pipeline steps and verified that the change takes effect by inspecting the Appium logs on BrowserStack:
```
[Appium] Appium v1.17.0 creating new AndroidUiautomator2Driver (v1.46.0) session
```
Earlier versions of Appium are not always as easy to identify, but the difference can be seen:
```
[Appium] Creating new AndroidUiautomator2Driver …
```
=> Add BrowserStack Appium version option

.buildkite/pipeline.yml, lib/features/steps/runner_steps.rb, lib/features/support/interactive_cli.rb, lib/features/support/runner.rb, test/cli_test.rb, test/fixtures/cli/Gemfile, test/fixtures/cli/features/CLI.feature, test/fixtures/cli/features/fixtures/error_script, test/fixtures/cli/features/fixtures/node_script, test/integration/automation_test.rb
Adds a way to interact with a terminal, sending commands and verifying output.  This will enable testing of CLIs (such as the upcoming React-native CLI)
The `InteractiveCLI` instance will act as a single terminal run, storing the parsed STDOUT and STDERR streams to be tested against.
This will be accessible through the `Runner` class, ensuring only one terminal is running at any given time. While this terminal is running it won't be possible to start another one without explicitly stopping it.
Covered by basic unit and e2e tests so far, but more will follow in subsequent PRs as part of the ongoing work.
=> [PLAT-4981] Add Interactive CLI steps

.buildkite/pipeline.yml, CHANGELOG.md, lib/features/support/capabilities/devices.rb
Sets the Appium version to use on each BrowserStack Android device, in preparation for their imminent change to the default version.
The versions chosen have followed a period of investigation into which Appium versions are required for each Android version.
BrowserStack device capabilities.
Covered by CI and subsequent testing against notifier pipelines prior to full release.
=> Set Appium version for all Android devices (v2)

.buildkite/pipeline.yml, CHANGELOG.md, lib/features/support/capabilities/devices.rb
Sets the Appium version to use on each BrowserStack Android device, in preparation for their imminent change to the default version.
The versions chosen have followed a period of investigation into which Appium versions are required for each Android version.
BrowserStack device capabilities.
Covered by CI and subsequent testing against notifier pipelines prior to full release.
=> Set Appium version for all Android devices (v3)

.buildkite/pipeline.yml, CHANGELOG.md, docker-compose.yml, lib/features/hooks/hooks.rb, lib/features/steps/network_steps.rb, lib/features/support/server.rb, lib/features/support/servlet.rb, test/fixtures/http-response/Dockerfile, test/fixtures/http-response/Gemfile, test/fixtures/http-response/features/fixtures/exact_match.json, test/fixtures/http-response/features/fixtures/fuzzy_match.json, test/fixtures/http-response/features/fixtures/ignore_apple.json, test/fixtures/http-response/features/fixtures/numerics.json, test/fixtures/http-response/features/scripts/send_request.sh, test/fixtures/http-response/features/set_different_responses.feature, test/integration/automation_test.rb
Adds steps to allow setting the HTTP status code response of the servlet to any given POST or OPTIONS request.
This will work in one of two ways:
- Setting an HTTP status code that will be used for all subsequent requests
- Setting an HTTP status code that will be used for the next received request, after which the code will return to `200`
- Added maze test fixture exercising changes.
=> [PLAT-4982] Server response code steps

.buildkite/pipeline.yml, CHANGELOG.md, Gemfile.lock, docker-compose.yml, dockerfiles/Dockerfile.ci, lib/features/support/docker.rb, lib/version.rb
Provide easy access to the container logs when running a Docker Compose service with a command.
when running a Docker service with a command, do so in the foreground rather than the detaching.  This is appropriate for the existing uses of the functionality as the commands issued are short lived processes.  Long running process such as web servers use the start service functionality with no command.
- Docker class
- Bumped Buildkite plugin versions
- Refactored Dockerfile to reduce image size.
Covered by standard CI.
=> Do not detach when running Docker Compose services with a command

.buildkite/pipeline.yml, CHANGELOG.md, bin/bugsnag-maze-runner, lib/features/hooks/hooks.rb, lib/features/support/configuration.rb
Make the use of the ResilientAppiumDriver optional.
`--resilient` option added to one of the CI test steps and logs inspected to check the expected branch was taken.
=> Provide an option to use the resilient driver

CHANGELOG.md, lib/features/support/capabilities/devices.rb
Default the Appium version for iOS devices to 1.15.0.
Our Cocoa tests currently set the Appium version to 1.15.0 when they instantiate the ResilientAppiumDriver in `env.rb`, but the creation of the driver is now performed by Maze in v3.
This change simply sets the default Appium version in accordance with that.  Notifiers can still override this should they wish by using the `--appium-version=` command line option.
Note: The React Native CI pipeline still uses Maze Runner v2 currently, so there is no impact.
Appium version set for BrowserStack iOS devices only.
Tested locally before raising the PR.  We do need to add iOS based tests to the Maze Runner CI, but that is outside of the scope of this PR.
=> Fix Appium version for iOS devices to 1.15.0

CHANGELOG.md, lib/features/steps/header_steps.rb, lib/features/support/header.rb, lib/features/support/servlet.rb, test/fixtures/android-app/app/build.gradle, test/fixtures/browserstack-app/app/build.gradle, test/fixtures/browserstack-app/app/src/main/java/com/bugsnag/android/mazerunner/MainActivity.kt, test/fixtures/browserstack-app/build.gradle, test/fixtures/browserstack-app/features/handled_exception.feature, test/fixtures/browserstack-app/gradle/wrapper/gradle-wrapper.properties, test/header_test.rb
Adds `the Bugsnag-Integrity header is valid` as a step to validate the `Bugsnag-Integrity` header. This should be a valid SHA-1 or simple digest.
The validation logic is covered by new unit tests. This has also been run against the Android CI here: https://github.com/bugsnag/bugsnag-android/pull/987
=> Add assertions for and auto-checking of Bugsnag-Integrity header

CHANGELOG.md, lib/features/steps/app_automator_steps.rb
Fix the step `I click the element {string}`.
This has been tested locally by @nickdowell during the recent work to get tests running against MacOS.
=> Fix `I clear the element {string}` step

CHANGELOG.md, lib/features/support/capabilities/devices.rb
Adds all of the iOS 11 devices available on BrowserStack as options.
Follows the existing pattern for Android alternatives.
Results in new entries in `DEVICE_HASH`.
Tested locally from a Cocoa branch pointing at the Docker image for the development branch - build shared internally.
=> Add full range of iOS 11 devices available on BrowserStack

.gitignore, test/fixtures/browserstack-app/app/src/main/java/com/bugsnag/android/mazerunner/MainActivity.kt, test/fixtures/browserstack-app/app/src/main/res/layout/activity_main.xml, test/fixtures/browserstack-app/features/handled_exception.feature
Updates the BrowserStack test fixture and adds tests for text entry/clearing.
I found myself adding these as part of investigating a _possible_ bug in one of the steps.  I haven't found it necessary to make any changes to Maze as yet, but we may as well keep the tests.
BrowserStack test fixture updated and new scenario added.
Covered by standard CI, no change to the MazeRunner tool itself..
=> Text entry and clearing tests added

CHANGELOG.md, lib/features/support/servlet.rb
The current `Access-Control-Allow-Headers` list doesn't include Bugsnag-Integrity, so requests using it fail in web browsers
> Request header field Bugsnag-Integrity is not allowed by Access-Control-Allow-Headers in preflight response.
This is/will be tested by bugsnag-js; there aren't really any MR specific tests for this
=> Allow the Bugsnag-Integrity header

CHANGELOG.md, lib/features/support/servlet.rb
This is PR https://github.com/bugsnag/maze-runner/pull/167 backported to v2 so that JS can make use of it before it is migrated to v3
=> [v2] Backport allow bugsnag integrity header

lib/features/steps/request_assertion_steps.rb
Rewords the error message when the number of requests does not match what is expected, as this has caused confusion in the past.
An example of what this looks like:
```
When I run "CXXAutoContextScenario"                                 # features/steps/android_steps.rb:1
And I wait to receive a request                                     # /maze-runner/lib/features/steps/request_assertion_steps.rb:12
Expected 1 requests but received 0 within the 30s timeout. This could indicate that Bugsnag crashed with a fatal error, or that it hasn’t made the requests that it should have done. Please check the device logs to confirm. (RuntimeError)
```
=> Reword request count assertion error message

CHANGELOG.md, Gemfile.lock, lib/features/steps/error_reporting_steps.rb, lib/features/steps/request_assertion_steps.rb, lib/features/steps/session_tracking_steps.rb, lib/features/support/env.rb, lib/version.rb, test/fixtures/payload-helpers/features/scripts/send_request.sh
ISO8601 timezones can either be 'Z' for UTC or a timezone offset, e.g. '+01:00' or '-12:34'
The PHP notifier uses timezone offsets rather than forcing everything to UTC, so the current assertions fail — only the Laravel notifier has MR tests so this wasn't noticed at the time
One of the tests now uses Ruby's `iso8601` method, which returns '+00:00' for UTC
=> Allow more than one valid ISO8601 timezone format

.buildkite/pipeline.yml, bin/bugsnag-maze-runner, lib/features/support/option.rb, lib/features/support/option_parser.rb, lib/features/support/option_processor.rb, test/fixtures/android-app/app/build.gradle, test/fixtures/android-app/build.gradle, test/fixtures/browserstack-app/build.gradle
Split the existing `bugsnag-maze-runner` entry point into separate files to reduce its size and make unit testing of each aspect easier.
I've been as friendly as I can be, by performing the refactoring in three distinct commits - each should be reviewable in its own right with no overlap.
This is a refactor only, there should be no change in functionality.
Should be covered by passing CI, but I have also performed some light local testing including use of the `--help` and `--version` options.  Some further testing with notifier clients before release would also seem prudent on this occasion.
=> Refactor parsing and processing of command line options

CHANGELOG.md, dockerfiles/Dockerfile.ci, lib/features/hooks/hooks.rb, lib/features/steps/app_automator_steps.rb, lib/features/support/browser_stack_utils.rb, lib/features/support/capabilities/capabilities.rb, lib/features/support/configuration.rb, lib/options/option_processor.rb, lib/options/option_validator.rb, test/browser_stack_utils_test.rb, test/options/options_processor_test.rb, test/options/options_validator_test.rb
Provides the ability to run tests against macOS apps (using `--farm=local` and `--os=macos`) using Appium and [AppiumForMac](https://github.com/appium/appium-for-mac).
Follows the thrust of the recent prototype developed by @nickdowell, updated to align with the current codebase.
- Addition of `macos` as a valid `--os`
- Setting of Appium capabilities for MacOS
- Hooks to launch/kill MacOS apps
- New Cucumber steps to support MacOS testing
Tested successfully locally with the macOS test fixture and scenarios currently in development in `bugsnag-cocoa`.
=> macOS automation support

CHANGELOG.md, Gemfile.lock, lib/features/support/servlet.rb, lib/version.rb
Fixes the check on the `Bugsnag-Integrity` header and prepares for the release of v3.6.0.
As before, further testing any updates to notifier repo will be made as part of shepherding the release out.
=> Fix check for Bugsnag-Integrity header

lib/features/steps/request_assertion_steps.rb
Resolve the following runtime warning `warning: already initialized constant INTERVAL`
Observable in the last CI run for master (in the No-device tests step):
Scenario: Testing payloads pass regardless of order | 1s
-- | --
  | Scenario: Testing payloads pass regardless of order # features/test_unordered_requests.feature:3
  | When I send a "ordered 1"-type request            # features/steps/scripting_steps.rb:1
  | And I send a "ordered 2"-type request             # features/steps/scripting_steps.rb:1
  | /app/lib/features/steps/request_assertion_steps.rb:23: warning: already initialized constant INTERVAL
  | /app/lib/features/steps/request_assertion_steps.rb:23: warning: previous definition of INTERVAL was here
  | And I wait to receive 2 requests                  # …
=> Resolve warning: already initialized constant INTERVAL

.buildkite/pipeline.yml, docker-compose.yml, lib/features/steps/request_assertion_steps.rb, lib/features/steps/runner_steps.rb, lib/features/support/interactive_cli.rb, lib/features/support/runner.rb, lib/wait.rb, test/cli_test.rb, test/fixtures/cli/Dockerfile, test/fixtures/cli/Gemfile, test/fixtures/cli/features/CLI.feature, test/wait_test.rb
Fixes some problems with the Interactive CLI / its tests, so that it's ready to use in anger
The tests were failing for two reasons:
- the docker image didn't have Node installed, so they couldn't run the scripts
- the command didn't exit until _after_ the stderr assertion, so stderr was never populated in time
If "the shell exited successfully" was added to the first step it would also fail due to the second reason above — the shell only exited _after_ the test finished. This has also been fixed, so tests can assert that they worked by waiting for the shell to exit
It's a bit unfortunate to have to explicitly let the shell exit, but I think this is unavoidable as the code doesn't know what the command should do, so it can't make assumptions about when it should be done
A new "I wait for …
=> InteractiveCLI fixes for RN CLI

lib/features/steps/runner_steps.rb, test/fixtures/docker-app/features/run_docker_services.feature
Currently our matching on stdout is done against any line — this is a good thing because otherwise there are race conditions and the potential for ordering changes to cause tests to flake
However, we also use the output of `echo $?` (and similar) to check the exit codes of commands. This means that any command that exits successfully will then allow all other commands to pass the "exited successfully" step, because the success output is already in the stdout logs
This PR is a fix specifically for that problem by adding a UUID to the exit code output, so each time the step runs it expects something different & unique
We also have an issue with output generally where any line of text in stdout will pass, even if another command is run afterwards. We may want to clear stdout before running a …
=> Allow checking the exit code of multiple commands

CHANGELOG.md, lib/options/option_parser.rb, test/options/options_parser_test.rb
Enables environment variables to be used when configuring:
- Device farm username -> `MAZE_DEVICE_FARM_USERNAME`
- Device farm access key -> `MAZE_DEVICE_FARM_ACCESS_KEY`
- BrowserStack local path -> `MAZE_BS_LOCAL`
- Appium server URL -> `MAZE_APPIUM_SERVER`
- Apple team ID -> `MAZE_APPLE_TEAM_ID`
- Apple UDID -> `MAZE_UDID`
These variables will be lower priority than actual configuration flags, which will take precedence.
In addition minor formatting changes have been made for readability.
Unit tests for the option parser in general have been added, verifying:
- Defaults
- Flag configuration
- Short-flag configuration
- Environment variable configuration
- Configuration priority
=> [PLAT-5475] Allow environment variables be used to configure specific options

.buildkite/pipeline.yml, CHANGELOG.md, Gemfile.lock, lib/features/hooks/hooks.rb, lib/features/steps/session_tracking_steps.rb, lib/version.rb
Clear the request arrays that we assert against after each scenario completes, rather than beforehand.
Until now our device-based test fixtures have not started Bugsnag until a button is actively pressed.  That has changed with the birth of the RN CLI, such that session requests are sent as soon as the app is first opened - which occurs before the scenario itself actually starts.  
Clearing of arrays moved to the `After`hook and clearly comments as to why.
I've also taken the opportunity to add a new Cucumber step for checking session requests for React Native, which could have come from either the Cocoa or Android notifier.
Regression is mitigated by Maze Runner CI and I have tested the new step locally with a RN app on both Android and iOS.
=> Clear request arrays after each scenario

CHANGELOG.md, bugsnag-maze-runner.gemspec, lib/features/support/server.rb, lib/options/option_parser.rb, lib/version.rb, test/server_test.rb
Display the Maze Runner version when the mock server starts.
Our CI instances include localized Docker registries, so that just after a release of Maze Runner we can often we left in doubt as to whether the old `latest` image is still being used or if something has gone horribly wrong.  This should avoid that doubt.
Additional log in server class.
Covered by CI and basic local testing that options such as `--help` and `--version` are not adversely affected.
=> Display version at startup

Gemfile.lock, UPGRADING.md, lib/features/hooks/hooks.rb, lib/features/steps/error_reporting_steps.rb, lib/features/steps/request_assertion_steps.rb, lib/features/steps/session_tracking_steps.rb, lib/features/steps/value_steps.rb, lib/features/support/browser_stack_utils.rb, lib/features/support/configuration.rb, lib/features/support/request_list.rb, lib/features/support/server.rb, lib/options/option_validator.rb, test/fixtures/payload-helpers/features/compare_requests_json_fixtures.feature, test/fixtures/payload-helpers/features/scripts/send_request.sh, test/request_list_test.rb
Furthers development of the endpoint separation epic to the point that the Cocoa notifier tests now successfully run against it.
This change takes the integration branch to a candidate for release as v4 in its own right.  However, I've already taken the changes forward another step (for JS browsers), so another PR into the integration branch should be expected before moving on to PR the integration branch for a v4 release.
The changes here were made in conjunction with the updating of the bugsnag-cocoa notifier tests to run against it.  These changes are on that repository's `tms/maze-v4` branch and will be PRed in due course (once the changes here are actually released).
The main source of changes here are the addition of Cucumber steps geared towards the verification of session …
=> Separate endpoints - Cocoa ready

CHANGELOG.md, Gemfile.lock, lib/features/support/capabilities/capabilities.rb, lib/version.rb
Disables network logs on BrowserStack by default.
All of our Android tests on version 4,6 and 7 have been failing for the last 2 weeks and this appears to have been due to a fault in the BrowserStack infrastructure when network logs are enabled (which we have always had set).  As a short (and possibly longer) term workaround, I've opted to disable network logging on BrowserStack by default.  It's pretty rare that I look at them anyway and the `--capabilities` option can be used to enable them selectively as required.
Remove setting of BrowserStack network logs capability.
CI now passes!
=> Disable BrowserStack network logs by default

bin/bugsnag-maze-runner, lib/features/hooks/hooks.rb, lib/features/steps/app_automator_steps.rb, lib/features/steps/breadcrumb_steps.rb, lib/features/steps/browser_steps.rb, lib/features/steps/error_reporting_steps.rb, lib/features/steps/header_steps.rb, lib/features/steps/multipart_request_steps.rb, lib/features/steps/network_steps.rb, lib/features/steps/request_assertion_steps.rb, lib/features/steps/session_tracking_steps.rb, lib/features/steps/value_steps.rb, lib/features/support/appium_driver.rb, lib/features/support/capabilities/browsers.yml, lib/features/support/capabilities/capabilities.rb, lib/features/support/configuration.rb, lib/features/support/selenium_driver.rb, lib/features/support/server.rb, lib/features/support/servlet.rb, lib/options/option.rb, lib/options/option_parser.rb, lib/options/option_processor.rb, lib/options/option_validator.rb, test/fixtures/comparison/features/steps/scripting_steps.rb, test/options/options_parser_test.rb, test/server_test.rb
Updates the Cucumber steps in order that the JS-Browser tests will run against separate notify/sessions endpoints.  I've also taken the opportunity to add the Selenium web driver code, currently present in the bugsnag-js repo.
The changes here follow the existing patterns for both the separation of endpoints and addition of a new `--browser` option to the Maze Runner command line.
Due to the increased use of Maze Runner outside of Docker (and the increased chance of clashes in the default namespace), I have also moved classes into their the `Maze` namespace where appropriate.
- Addition of Selenium webdriver code currently present in bugsnag-js
- New `--browser` option
- Updated/added Cucumber steps to support the separation of endpoints.
Largely covered by CI and having successfully …
=> Endpoint separation for JS-Browser and add Selenium web driver

CHANGELOG.md, Gemfile.lock, lib/features/hooks/hooks.rb, lib/version.rb
Fix the broken link to the BrowserStack dashboard, which has just been updated.
Can be seen working in the build for this PR:
=> Correct link to BrowserStack dashboard

CHANGELOG.md, Gemfile.lock, bugsnag-maze-runner.gemspec, lib/features/support/interactive_cli.rb, lib/version.rb, test/fixtures/docker-app/features/fixtures/interactive/guessing-game
Strip ansi escape codes from CLI stdout/stderr, which seems to help reduce flakes in the RN CLI pipeline
=> Strip ansi escape codes from CLI stdout/stderr

CHANGELOG.md, Gemfile.lock, lib/options/option_parser.rb, lib/version.rb
Moves environmental population of maze-runner options from the parser to a separate method so the `--help` command doesn't show the server environment variables in instructions.
Running:
```MAZE_DEVICE_FARM_ACCESS_KEY=foo ./bin/bugsnag-maze-runner --help```
yields the help information without including the mentioned environment variable.
=> [PLAT-5599] Ensure help doesn't display potentially secure environment variable

lib/features/steps/browser_steps.rb, lib/features/steps/error_reporting_steps.rb, lib/features/steps/header_steps.rb, lib/features/steps/request_assertion_steps.rb, lib/maze/helper.rb, lib/maze/request_list.rb, test/fixtures/browserstack-app/app/build.gradle, test/fixtures/browserstack-app/features/handled_exception.feature, test/fixtures/payload-helpers/features/compare_requests_json_fixtures.feature
Corrects some errors that came to light as part of updating the Android pipeline to use what is now a candidate for MazeRunner v4.
Cucumber step corrections and refactoring.  Also updated the Android notifier that the end-to-end tests use in order that the `Bugnsag-Integrity` header step can be brought in.
Covered by CI combined with Android PR https://github.com/bugsnag/bugsnag-android/pull/1080, which uses it.
=> Step corrections for separation of endpoints

CHANGELOG.md, Gemfile.lock, lib/maze.rb, lib/maze/devices.rb
Adds two more devices from the BrowserStack pool.
Follows the existing pattern.
Adds the Galaxy S6 and Note 4, both of which look like they have more power than the Android 4/5 devices currently in use. 
Tested locally.
=> Additional Android 4 and 5 devices

.buildkite/pipeline.yml
Removes triggering of notifier builds against the the new MazeRunner master.
This mechanism has been overtaken by events by a large extent and drifted out of use.  The custom branches it triggers are no longer up to date and I can't remember the last time I wanted to look at the results.  We have got better at adding tests to the MazeRunner pipeline as we go and are also very reactive to any issues with new release, so it has become more of a burden having to wait for them to run and cancel the triggered builds to avoid unnecessary resource use.
I suggest we now remove these - if we really find the need to run the notifier pipelines in advance of a release we can do this manually.
Notifier pipeline build triggers removed.
Covered by CI.
=> Remove triggering of notifier builds for new master

CHANGELOG.md, Gemfile.lock, lib/maze.rb, lib/maze/devices.rb
Adds the remaining set of Android 4 and 5 devices available on BrowserStack.
Use tested locally.
=> Further Android 4 and 5 devices added

CHANGELOG.md, Gemfile.lock, lib/features/steps/app_automator_steps.rb, lib/maze.rb
Generalises the payload type used when making platform-dependent checks, allowing platform-dependent assertions to be made against session payloads.
=> Make platform-dependent tests independent of payload type

.buildkite/pipeline.yml, CHANGELOG.md, Gemfile.lock, docker-compose.yml, lib/features/steps/request_assertion_steps.rb, lib/maze.rb, lib/maze/request_list.rb, test/request_list_test.rb
Ensures the batch of requests captured by the `I wait to receive {int} {word}` step are sorted by the `Bugsnag-Sent-At` header, if it is present on all requests.  If requests are sent very close together (perhaps <0.1s), they can end up being stored out of order, resulting in test flakes.
It is important that sorting of requests does not intrude upon:
- requests previously captured and already processed
- requests that arrive due to subsequent actions, whilst the batch is still being processed.
The unit tests added are designed to ensure this.
- New method on the `RequestList` class to sort by header in-situ.  
- Plumbing into the Cucumber step
- Incidental pipeline change to reduce unnecessary noise (values are now set in the environment)
Logic for sorting of the requests sub-list is …
=> Sort received requests by Bugsnag-Sent-At header

CHANGELOG.md, Gemfile.lock, lib/features/steps/app_automator_steps.rb, lib/maze.rb, test/fixtures/browserstack-app/app/src/main/java/com/bugsnag/android/mazerunner/MainActivity.kt, test/fixtures/browserstack-app/features/handled_exception.feature
Adds `@null` and `@not_null` tags for use with platform-dependence steps.
This allows:
- Asserting that a value is present (with an unknown value) on a specific platform using `@not_null`
- Asserting that a value will not be present, or be null, on a specific platform using `@null`
Added to the platform-dependence e2e tests.
=> Nullable platform dependence

CHANGELOG.md, Gemfile.lock, lib/features/support/hooks.rb, lib/maze.rb, lib/maze/server.rb, test/server_test.rb
Adds an endpoint to the basic server on `/` that logs responds to all requests with a `200` status code.
This will be used for certain platforms that need to establish the server is reachable before attempting to run tests.
Manually tested to ensure logging and status codes are correct
- It may be useful to add more debug logging for received requests, but I'd be reluctant to do too much as this endpoint shouldn't typically be used.
- We could record a hit here and add steps for testing whether something has hit the endpoint, but this seems unnecessary for our purposes.
Changelog entry incoming
=> [PLAT-PLAT-5827] Add root endpoint for connectivity checks

CHANGELOG.md, lib/features/steps/app_automator_steps.rb, lib/features/steps/build_api_steps.rb, lib/features/steps/header_steps.rb, lib/features/steps/payload_steps.rb, lib/features/steps/query_parameter_steps.rb, lib/features/steps/request_assertion_steps.rb, lib/features/steps/value_steps.rb, lib/features/support/hooks.rb, lib/maze/configuration.rb, lib/maze/server.rb, test/fixtures/payload-helpers/features/build_endpoint.feature, test/fixtures/payload-helpers/features/scripts/send_request.sh, test/server_test.rb
Allows requests to be received on `/builds` and then tested using the payload steps with `build` as the request type
Added basic tests to the payload helper e2e test set to verify requests are received and payload steps work correctly
=> Add build endpoint

CHANGELOG.md, Gemfile.lock, lib/features/steps/log_steps.rb, lib/features/support/hooks.rb, lib/maze.rb, lib/maze/server.rb, test/fixtures/comparison/features/scripts/send_request.sh, test/fixtures/comparison/features/test_log_requests.feature, test/server_test.rb
Provides a new endpoint on `/logs` for clients to `POST` log messages to and write assertions upon.
The new endpoint follows the existing design for multiple endpoints.  The new steps chosen for the verification of log messages make the assumption that clients will be controlled in what they choose to send, so that stepping though request one at a time (as we do with requests and sessions) is not egregious to use.
New endpoint with Cucumber steps.
Verified by the addition of a new test scenario.
=> Add logs endpoint

CHANGELOG.md, Gemfile.lock, lib/features/steps/log_steps.rb, lib/features/support/hooks.rb, lib/maze.rb, lib/maze/server.rb, lib/maze/servlet.rb
Corrects some issues with the new `/logs` endpoint:
- Disables `Bugsnag-Integrity` header checking for all requests on the endpoint
- Fails gracefully if log message checks are attempts before waiting to receive them
- Prints logs received at the end of any failing scenarios
Testing using the in-development Android test fixture on branch `PLAT-5905/ndk-on-error`.  The scenarios did not pass as-is (I assume because it is still in development), but I was able to demonstrate the receipt and checking of a log message from a real test fixture.
=> Logs endpoint fixes

CHANGELOG.md, Gemfile.lock, lib/features/support/hooks.rb, lib/maze.rb, lib/maze/driver/browser.rb, test/appium_driver_test.rb
Logs a link to the BrowserStack build (and sessions onwards) for browser test runs.
Follows the existing pattern for Appium runs.
A little extra plumbing was needed in order to pass the build name (that we decide) through to BrowserStack as a capability in order to search against.
Regression to logging for Appium runs is covered by CI.  I've tested the new feature for browser testing both locally and via a custom CI run in the `bugsnag-js-browser` pipeline.
=> Log links to BrowserStack build/sessions for browser runs

CHANGELOG.md, lib/features/steps/runner_steps.rb, test/fixtures/cli/features/CLI.feature
This enables the use of regexes in testing stdout lines, which allows flexibility in certain circumstances (and mitigates flakes where the exact message is not important).
This updates the exit code steps to use a regex as well, meaning in the event the shell prompt is present in the stdout (which appears inconsistently) we are more resilient to it.
Added scenario testing new regex steps to current CLI feature.
=> Enable the use of regexes when testing received STDOUT lines

CHANGELOG.md, lib/features/steps/runner_steps.rb
Adds several steps originally present in the react-native-CLI e2e tests.
The steps have been slightly adjusted in an attempt to make the functionality clearer.
A test branch will be created to update and run the current react-native cli tests using the new steps, which should run through before this is merged.
=> [PLAT-5566] Add react-native-CLI steps

CHANGELOG.md, Gemfile.lock, lib/features/steps/aws_sam_steps.rb, lib/features/support/hooks.rb, lib/maze.rb, lib/maze/aws/sam.rb, test/fixtures/aws-sam/Gemfile, test/fixtures/aws-sam/features/fixtures/node-app/events/event.json, test/fixtures/aws-sam/features/fixtures/node-app/hello-world/app.js, test/fixtures/aws-sam/features/fixtures/node-app/template.yaml, test/fixtures/aws-sam/features/fixtures/ruby-app/events/error event.json, test/fixtures/aws-sam/features/fixtures/ruby-app/events/example-event.json, test/fixtures/aws-sam/features/fixtures/ruby-app/hello_world/app.rb, test/fixtures/aws-sam/features/fixtures/ruby-app/template.yaml, test/fixtures/aws-sam/features/invoke.feature, test/fixtures/aws-sam/features/support/env.rb
Add the ability to use AWS' SAM CLI to test notifiers running in AWS Lambda functions
This has to run on the host machine because SAM doesn't run in Docker. Therefore we only have the ability to invoke Lambda functions directly (`sam local invoke`) and do not allow running the local API (`sam local start-api`). This makes everything a lot simpler as we don't need to worry about ports clashing or zombie processes. The downside to this is that we need to write event files to change any of the request parameters
- New `Maze::Aws::Sam` class that can invoke Lambda functions and parse their responses
- New set of steps for invoking & asserting against Lambda functions
- Tests and fixtures that exercise the new `Sam` class and associated steps
Tests run locally. These need a new setup to run on …
=> AWS SAM CLI integration for Lambdas

CHANGELOG.md, Gemfile.lock, lib/maze.rb, lib/maze/browser_stack_utils.rb, lib/maze/option/processor.rb, test/browser_stack_utils_test.rb, test/option/processor_test.rb
Only expand the `--app` option to a full file path (dealing with, for example, tilde use) when uploading to BrowserStack.  Avoids erroneous expansion of Mac and pre-uploaded apps. 
Covered by unit testing.
=> Only expand paths when actually uploading to BrowserStack

CHANGELOG.md, Gemfile.lock, lib/features/steps/network_steps.rb, lib/features/steps/payload_steps.rb, lib/features/steps/runner_steps.rb, lib/features/support/hooks.rb, lib/maze.rb, lib/maze/log_servlet.rb, lib/maze/runner.rb, lib/maze/server.rb, lib/maze/servlet.rb, test/fixtures/http-response/features/scripts/send_request.rb, test/fixtures/http-response/features/set_different_responses.feature
Adds a new step to allow tests to delay responses to an HTTP request.
Takes a similar approach to the existing status code functionality.
I've also added a new mechanism for running scripts with an interpreter - this was purely so that I could rename the script that's run to have an `.rb` extension and benefit from the language aware facilities of my IDE.
Covered by CI, with a new test having been added..
=> Add step to set response delay on next HTTP request

CHANGELOG.md, Gemfile.lock, lib/maze.rb, lib/maze/option/validator.rb
2nd attempt at fixing the erroneous expansion of app paths.  This affected only BrowserStack usage, which I have now tested locally with:
- A previously uploaded app `bs://` style
- A relative path
- A path starting with a tilde
=> Correct expansion of app option

CHANGELOG.md, Gemfile.lock, lib/features/steps/request_assertion_steps.rb, lib/features/support/configuration.rb, lib/version.rb
Allow notifiers (and back-ports) still using MazeRunner v2 to change the time given for requests to be received in the `I wait to receive {int} request(s)` step.
We recently found (in Android v5) that some requests can take longer than 30s to reach the Maze Runner server (in the BrowserStack environment).  We have some backports to perform on Android v4, hence the desire to backport the capability in Maze Runner.
CI is sufficient to show that the existing functionality if not broken.  It's more time consuming to test the new functionality works with a notifier test suite, but the risk of it not doing so seems minimal.
=> Back-port of receive_requests_wait config

.buildkite/pipeline.yml, CHANGELOG.md, Gemfile.lock, docker-compose.yml, dockerfiles/Dockerfile.ci, lib/features/hooks/hooks.rb, lib/features/steps/request_assertion_steps.rb, lib/features/support/app_automate_driver.rb, lib/version.rb, test/app_automate_driver_test.rb, test/fixtures/browserstack-app/dockerfile, test/fixtures/comparison/Dockerfile, test/fixtures/payload-helpers/Dockerfile, test/fixtures/proxy/Dockerfile
Back-ports some logging improvements to v2, in support of Android back-ports currently being made for Unity fixes.
Includes the move to a Ubuntu Docker image from Alpine, which we felt improved stability (it certainly leads to a cleaner log).  I've also taken the opportunity to trim the pipeline back from unnecessarily running tests on all Android versions, and brought the pushing of the Docker image for the branch closer to the start.
Covered by CI and I have also been running a v4 Android branch against it.
=> v2 logging improvements

.buildkite/pipeline.yml
Adds tests for the SAM CLI functionality to the pipeline.
These tests failed at first due to a permission error resulting from the Buildkite agent being configured to check files out beneath `/usr/local`, which is owned by `root`.  The agent has now been reconfigured to work beneath `/Users/admin`, avoiding the problem.
Covered by CI.
=> Add AWS SAM CLI tests to the pipeline

CHANGELOG.md, lib/features/support/hooks.rb, lib/maze.rb, lib/maze/logger.rb
Makes Maze output a log file when testing a MacOS app with the `--farm=local` option set.
The file and resulting upload can be seen here: https://buildkite.com/bugsnag/bugsnag-cocoa/builds/2101#575036dc-e9db-4caa-856f-e748db2d2b16/307-308
=> Output Application logs when running on MacOS

CHANGELOG.md, Gemfile.lock, bin/maze-runner, lib/maze.rb, lib/maze/configuration.rb, lib/maze/option.rb, lib/maze/option/parser.rb, lib/maze/option/processor.rb, lib/maze/server.rb, test/option/processor_test.rb, test/server_test.rb
Adds options to control the bind address and port of the mock server.
Covered by unit tests combined with manual testing to confirm that the bind address and port options take effect correctly, accessing the mock server from a separate machine.
=> Add --bind-address and --port options

CHANGELOG.md, Gemfile.lock, bin/maze-runner, lib/features/support/hooks.rb, lib/maze.rb, lib/maze/browser_stack_utils.rb
Prevent the BrowserStackLocal binary from loitering after a test run.
Covered by CI and tested locally with Activity Monitor to verify that the spawned process is terminated.
=> Stop BrowserStackLocal binary at end of run

CHANGELOG.md, Gemfile.lock, lib/features/support/hooks.rb, lib/maze.rb, lib/maze/browser_stack_utils.rb, test/browser_stack_utils_test.rb
Terminate the BrowserStackLocal process(es) at the end of a run in a way that doesn't lead to it hanging.
Despite the `BrowserStackLocal -d stop` option being intended for CI use and testing prior to its introduction, it appears that the command can hang, causing build steps to time out.  This change takes a different approach to terminating the processes that a launched, by extracting the parent process id from the output of the `-d start` command.  Sending this the `TERM` signal also closes any children that are created.
Tested locally to verify that the `BrowserStackLocal` processes are terminated upon exit.  This new approach should be "CI safe", in the sense that even if the processes are not terminated, the Buildkite agent will perform the clean-up admirably.  The important thing is …
=> Terminate BrowserStackLocal without hanging

CHANGELOG.md, lib/maze/option/parser.rb, lib/maze/server.rb, test/option/processor_test.rb, test/server_test.rb
Do not set a default for the recently introduced `--bind-address` option, allowing `WEBrick::HTTPServer` to follow its default behaviour, which has generally served us well.
Setting a default of `127.0.0.1` when introducing the option caused some areas to regress (JS Browser and Node testing).  Making this change should remove the need to remedial configuration in those pipelines.
Sufficiently covered by unit and e2e tests to merge to `master`.  Further testing against the JS repo will be performed before release.
=> Do not set explicit default for —bind-address

CHANGELOG.md, lib/features/steps/aws_sam_steps.rb, lib/maze/aws/sam.rb, test/fixtures/aws-sam/features/fixtures/node-app/process-exit/app.js, test/fixtures/aws-sam/features/fixtures/node-app/template.yaml, test/fixtures/aws-sam/features/fixtures/python-app/hello_world/app.py, test/fixtures/aws-sam/features/fixtures/python-app/template.yaml, test/fixtures/aws-sam/features/invoke.feature
Currently it's impossible to test a Lambda function that returns no response or returns a response body which is not JSON
A Lambda can avoid responding by forcefully exiting; when this happens AWS return some generic JSON to the user. If we get a JSON error when parsing the last line of output, it's now assumed that there was no response. We now validate that there's an "END" marker in SAM's output so we can still provide a useful error message if something really goes wrong
The Lambda response body does not _have_ to be JSON, so we now allow non-JSON bodies without immediately failing the test. This allows testing against projects that return HTML, for example
=> Loosen requirements on Lambda responses

CHANGELOG.md, lib/features/steps/request_assertion_steps.rb
This step should be used exclusively for stress-testing, as ensuring we don't receive excessive requests is an important criteria in our end-to-end testing.
=> Add a step asserting a minimum number of requests to have received

.buildkite/pipeline.yml, CHANGELOG.md, Gemfile.lock, bin/maze-runner, lib/features/support/hooks.rb, lib/maze.rb, lib/maze/configuration.rb, lib/maze/option.rb, lib/maze/option/parser.rb, lib/maze/option/processor.rb, test/option/parser_test.rb, test/option/processor_test.rb
Adds the `--no-request-output` option, as well as tidying some of options into categories.
=> Add an option to suppress request outputs when a failure occurs

.buildkite/pipeline.yml, lib/maze/option/parser.rb
Requires #240 and #241 to be merged first
Allows the use of `BROWSER_STACK_USERNAME`, `BROWSER_STACK_ACCESS_KEY`, `SAUCE_LABS_USERNAME` and `SAUCE_LABS_ACCESS_KEY` environment variables depending on the set `--farm` attribute
=> Use environment variables instead of command line options for credentials

CHANGELOG.md, Gemfile.lock, lib/features/support/hooks.rb, lib/maze.rb, lib/maze/configuration.rb, lib/maze/devices.rb, lib/maze/option.rb, lib/maze/option/parser.rb, lib/maze/option/processor.rb, lib/maze/sauce_labs_utils.rb, test/option/parser_test.rb, test/option/processor_test.rb, test/option/validator_test.rb
Adds an environment variable for the Sauce Connect binary, following the established pattern for `BrowserStackLocal`.
Also a few minor tidy-ups and TODOs added for later implementation.
Covered by CI and with these changes in place I am able to successfully run the handled smoke test scenarios in bugsnag-android locally.
=> Add environment variable for Sauce Connect binary

CHANGELOG.md, lib/features/support/hooks.rb, lib/maze/capabilities.rb, lib/maze/configuration.rb, lib/maze/devices.rb, lib/maze/driver/appium.rb, lib/maze/option.rb, lib/maze/option/parser.rb, lib/maze/option/processor.rb, test/option/parser_test.rb, test/option/processor_test.rb
Get all of our Android e2e tests working with Appium 1.20 using BrowserStack devices.  Also makes significant improvements for running the tests on locally held devices.
Our Android e2e tests do not currently work properly with Appium versions 1.9.1+.  This change set fixes that (with a small change to the Android pipeline).  Whilst this is not directly related to the Sauce Labs integration, it's an important building block when considering that Sauce Labs do not support <1.15.  It can also be viewed as a breaking change, so I opted to target this integration branch and a major version bump.
- The `noReset` capability is now specified to prevent the app from being reset when `driver.launch_app` is called, which was breaking all of our test scenarios involving unhandled errors.  The app is …
=> Updates for Appium 1.20 with Android

.buildkite/pipeline.yml, CHANGELOG.md, Gemfile.lock, bin/maze-runner, lib/maze.rb, lib/maze/server.rb, test/server_test.rb
Move logging of the Maze Runner version right to the start, so that it's alway clear which version we have, even if command line option validation errors are raised.
=> Move logging of version to the start

.buildkite/pipeline.yml, CHANGELOG.md, CONTRIBUTING.md
Ensure Docker images for v5 releases are tagged with `latest-v5-cli` and not overwrite the last v4 release.
=> Correct docker tag for v5 releases

CHANGELOG.md, Gemfile.lock, bugsnag-maze-runner.gemspec, lib/maze.rb, lib/maze/interactive_cli.rb, test/fixtures/docker-app/features/fixtures/interactive/guessing-game
Stop using the Boring gem, which was introduced to resolve flaking React Native CLI e2e tests.
An internal ticket has been raised to find an alternative to `Boring`, or write our own implementation.  I have also contact its author in the hope that they may be willing to add a `LICENSE`.
=> Remove use of unlicensed Boring gem

CHANGELOG.md, lib/maze/appium_server.rb, lib/maze/configuration.rb, lib/maze/option.rb, lib/maze/option/parser.rb, lib/maze/option/processor.rb, test/appium_server_test.rb
Allows the appium server to output to a file which can be attached to the buildkite build when running in local mode.
Adds an `--appium-logfile` option denoting the file output, which defaults to `appium_server.log`
- Tested manually and confirmed that the `appium_server.log` file is created by default and contains appium logs
- In addition, the `--appium-logfile` override successfully sets the file path of the logfile
=> Adds logging to a file for the appium server

.buildkite/pipeline.yml, Gemfile.lock, bugsnag-maze-runner.gemspec, config/.gitignore, docker-compose.yml, dockerfiles/Dockerfile.audit, scripts/license_finder.sh
Add a check to the pipeline to ensure that any added dependencies comply with company policy.
A script is provided to run the license checks locally.  Decision files for the [LicenseFinder](https://github.com/pivotal/LicenseFinder) tool are held centrally with our [license-audit tool](https://github.com/bugsnag/license-audit) for process control and to avoid duplication.
New pipeline step to perform license auditing.
Covered by CI and by running the script locally.  I've confirmed that a dependency not covered by an approved license would cause CI to fail.
=> Add license finder to pipeline

CHANGELOG.md, lib/features/steps/request_assertion_steps.rb
Corrects the failure message to output the number of requests held in the list.  A double `.size` occurred before, meaning that 8 (bytes for an integer) was always output.
=> Correct step failure message

CHANGELOG.md, Gemfile.lock, dockerfiles/Dockerfile.audit, lib/features/steps/app_automator_steps.rb, lib/maze.rb
When running local MacOS tests, the platform-dependent tables fail due to the OS not being correctly set. This resolves the issue by using the configuration option as a default.
=> Fix issue with os not being defined in local test runs

CHANGELOG.md, Gemfile.lock, lib/maze.rb, lib/maze/browser_stack_devices.rb
Adds a Pixel 2.0 running Android 9.0 accessible using `--device=ANDROID_9_0_GOOGLE_PIXEL_2`
=> Prepare 5.2.0 release

CHANGELOG.md, lib/features/support/hooks.rb, lib/maze/configuration.rb, lib/maze/option.rb, lib/maze/option/parser.rb, lib/maze/option/processor.rb, test/option/processor_test.rb
Adds an `--always-log` option, defaulting to `false`, to allow all received requests to be logged at the end of a scenario, whether it passes or fails.
Tested locally and unit test updated.
=> Add —always-log option

CHANGELOG.md, Gemfile.lock
Provide support for running on ARM based Macs.
Adds the `arm64-darwin` platform to the `Gemfile.lock`.
On an ARM-based Mac before running this change, running `bundle exec maze-runner --help` results in an exception: `Cannot load such file -- nokogiri/nokogiri`.  This change resolves that exception and allows the Maze Runner tool to be used to run e2e tests.
=> Add support for ARM-based Macs

CHANGELOG.md, lib/maze/option/parser.rb, test/option/parser_test.rb
Slightly knee-jerk removal of short-form command line options to avoid an clashes with underlying Cucumber options.
Longer term, a wholesale reassessment of command line use is likely to take place, including the use of files for options and `--` separators in the CL (for instance).
Covered by CI and existing unit tests.
=> Remove short command line options to avoid clashes with cucumber

CHANGELOG.md, Gemfile.lock, lib/maze.rb, lib/maze/browser_stack_devices.rb
Adds a small variety of Android 10 devices available on BrowserStack.
Use of all new devices tested locally.
=> Add Android 10 devices

dockerfiles/Dockerfile.audit
libcurl3 and libcurl4-openssl-dev conflict on the latest version of the license-audit base image, causing the build to fail.  As only libcurl4-openssl-dev is required we can remove libcurl3 completely.
=> Remove now unnecessary libcurl3 from license_finder docker image

CHANGELOG.md, lib/features/steps/multipart_request_steps.rb
Adds new multipart request steps that allow multipart field checking on any received requests.
Deprecated steps have not been updated (as there are up to date replacements that should be used instead).
To keep backwards compatibility the original steps call into the new steps using the `error` queue by default.
=> Add multipart steps usable against any request queue

CHANGELOG.md, Gemfile.lock, lib/maze.rb, lib/maze/option/processor.rb, lib/maze/option/validator.rb, test/option/validator_test.rb
Allow `windows` to be specified as the `--os`.  Also allow the `--os-version` to be set when running with no farm (i.e. not Appium).
The approach to running Unity tests on Windows has been to employ WSL.  This means that MazeRunner can run on Ubuntu, on Windows, avoiding the need to port the codebase (noting that many dependencies have native extensions).  However, it also means that the MazeRunner test setups cannot meaningfully detect the current operating system (Ruby will report Linux).  Adding this option allows the developer to explicitly configure where the tests are being run.
Command line option processing and validation updated.
Tested locally as part of setting up MR testing on Windows for our Unity notifier.
=> Allow Windows to be set as --os

CHANGELOG.md, Gemfile.lock, lib/features/support/hooks.rb, lib/maze.rb
Prevent the dereference of `nil` with using `--os=macos` with a `--farm` (i.e. starting the macOS app on the command line and not using Appium.
v5.5.0 introduced the ability to specify an `--os` option without having to use Appium, to allow clients to make decisions based on the intended platform.  The existing code assumed that Appium would be used, leading to a `nil` `Maze.driver`.
Addition of a nil guard.
Tested locally using the Unity e2e tests on macOS, where the problem was highlighted.  Longer term we should add some more macOS-based tests to our pipeline (with and without Appium).
=> Only start macOS apps when using Appium

CHANGELOG.md, lib/features/steps/app_automator_steps.rb
Corrects the guard on "platform-dependent value" steps that was using a now false assumption that Appium must be in use for the `--os` option to be set.
Verified locally that Unity steps that were failing due to this now pass.
=> Correct guard for “platform-dependent” steps

CHANGELOG.md, Gemfile.lock, bugsnag-maze-runner.gemspec
Pin the version of RubyZip, an indirect dependency dependency, to avoid possible breakage in Ruby 3.
=> Pin Rubyzip version

CHANGELOG.md, lib/maze/driver/appium.rb
add a generic send keys methods for unity as it can't access elements
=> add a generic send keys methods for unity as it can't access elements

.buildkite/pipeline.yml, CHANGELOG.md, Gemfile.lock, bugsnag-maze-runner.gemspec, docker-compose.yml, dockerfiles/Dockerfile.ci, lib/maze.rb, test/fixtures/android-appium-test/app/build.gradle, test/fixtures/android-appium-test/dockerfile, test/fixtures/cli/Dockerfile, test/fixtures/comparison/Dockerfile, test/fixtures/doc-server/Dockerfile, test/fixtures/docker-app/Dockerfile, test/fixtures/framework/Dockerfile, test/fixtures/http-response/Dockerfile, test/fixtures/ios-app/dockerfile, test/fixtures/payload-helpers/Dockerfile, test/fixtures/proxy/Dockerfile
Allow Maze Runner to be used with Ruby 3.
The only identified change needed is to add a dependency on `webrick`.  The remaining changes enhance the pipeline to run tests with both Ruby 2.7 and 3.
The addition of tests against Ruby 2.5 (the minimum support version) was also considered, but the additional work needed to the base image and pipeline steps did not seem worthwhile.
Covered by updated CI pipeline and I've also verified that the Docker image pushed for the branch can be successfully used in another pipeline (Android).
=> Support Ruby 3

CHANGELOG.md, dockerfiles/Dockerfile.ci
Pin the Docker image base to Debian 10 (Buster) to avoid us having to continually port our subsequent Docker build steps to new Debian versions.
Covered by CI.
=> Pin Docker image base to Debian 10 (Buster)

CHANGELOG.md, Gemfile.lock, lib/features/steps/app_automator_steps.rb, lib/maze.rb
Remove the blanket rescue for macOS in step `I click the element {string}`.
A localized rescue, specific to only crashy button clicks will be added to `bugsnag-cocoa`.
Covered by CI.
=> Remove blanket rescue for macOS

.buildkite/pipeline.yml
Implement eager concurrency for the CI browserstack-app concurrency group.
By default, Buildkite processes jobs in the order in which they were created, which is often very inefficient for our needs.  Jobs that are ready to be processed can be held behind those that are still waiting for other steps to complete.  
Setting `concurrency_method` to `eager` is Buildkite's mechanism to avoid this situation and is perfect for our needs.
Covered by CI.
=> Eager concurrency

lib/maze/option.rb
This was using an underscore, meaning it needed to be provided as `--enable_retries` instead of using hyphens like other options (`--enable-retries`)
=> Make enable-retries consistent with other options

CHANGELOG.md, Gemfile.lock, lib/maze.rb, lib/maze/browser_stack_devices.rb
Add Android 12 and additional Android 7 devices on BrowserStack.
Use of new symbolic device names tested locally.
=> Add Android 7 and 12 devices

CHANGELOG.md, lib/maze/driver/browser.rb, lib/maze/retry_handler.rb, test/retry_handler_test.rb
The Browser driver does not have a `restart` method, so instead we should call the `refresh` method (to refresh the webpage) when a driver error happens.
This likely won't fix any critical driver issues, but if the webpage doesn't load correctly for some reason it may help, and it'll also float the original error out.
=> Retry: Browser driver fix

CHANGELOG.md, Gemfile.lock, lib/maze.rb, lib/maze/helper.rb, lib/maze/option/parser.rb, lib/maze/option/processor.rb, lib/maze/option/validator.rb, test/option/processor_test.rb
Allows the `--app` option to be provided in a file by prefixing with `@`.  E.g: `bundle exec maze-runner --app=@in_this_file --farm=bs --device=ANDROID_9_0`
The need for this isn't obvious and came to light whilst developing a Buildkite pipeline to upload an app to BrowserStack only once (we currently do it on every Maze Runner step).  I found that the easiest way to pass the BrowserStack URL for uploaded apps between Buildkite steps is to write them to file and use build artefacts.  As Maze Runner commands are provided in the Buildkite YML files, I couldn't simply `cat` the file to pass it in via the existing command line and adding this feature seemed to be the easiest approach.
New unit test added and overall effect tested locally.
=> Allow --app to be read from file

CHANGELOG.md, lib/maze/configuration.rb, lib/maze/hooks/appium_hooks.rb, lib/maze/option/parser.rb, lib/maze/option/processor.rb, lib/maze/option/validator.rb, test/hooks/appium_hooks_test.rb, test/option/parser_test.rb
Allows multiple `--device` options when running maze-runner.  These options will then be iterated through when attaching to the appropriate device farm, moving onto the next if one fails, allowing us to specify several appropriate devices for a test.
Unit tests cover the basic functionality of the added/refactored methods
Not tested in anger - I'd suggest using this release in a test job against android/cocoa before merging.
=> Allow multiple `--device` options to be specified

CHANGELOG.md, lib/maze/option/processor.rb
`device` option now defaults to an array, so needs a guard with both `nil` and `empty` instead of just `nil`
=> Add fix for BrowserStack browser mode devices issue

CHANGELOG.md, Gemfile.lock, lib/maze.rb, lib/maze/browsers.yml
Add Safari 14 and 15 to set of options (for BrowserStack).
Tested locally using a development branch of `bugang-js`.
=> Add Safari 14 and 15

CHANGELOG.md, Gemfile.lock, dockerfiles/Dockerfile.ci, lib/maze.rb
Bump BrowserStackLocal to 8.4 (from 8.0).
See release notes on https://www.browserstack.com/local-testing/releases (v8.4 currently missing, raising with BS support).
=> Bump BrowserStackLocal to 8.4

CHANGELOG.md, Gemfile.lock, dockerfiles/Dockerfile.ci, lib/features/steps/app_automator_steps.rb, lib/features/support/internal_hooks.rb, lib/maze.rb, lib/maze/capabilities.rb, lib/maze/helper.rb, lib/maze/hooks/appium_hooks.rb, lib/maze/hooks/browser_hooks.rb, lib/maze/hooks/command_hooks.rb, lib/maze/hooks/hooks.rb, lib/maze/option/processor.rb, lib/maze/sauce_labs_utils.rb, test/hooks/appium_hooks_test.rb
Fix support for Sauce Labs, which was partially broken in a recent refactor.  Also makes a few code improvements.
- Necessary code for Sauce Labs reinstated into Cucumber hooks 
- Code style violations resolved
- Sauce Connect version bumped
- Platform detection code moved to Helper class to allow reuse
Tested locally against Sauce Labs, CI covers the BrowserStack side.  Some further testing will be performed against notifier pipelines before release.
=> Refresh support for Sauce Labs

CHANGELOG.md, lib/maze/hooks/appium_hooks.rb, test/fixtures/ios-app/features/steps/test_steps.rb
Kill the the Mac test fixture even if it deadlocks while running a scenario.
Passes the `-KILL` option to `killall` to forcibly terminate the app rather than sending a signal that needs to be handled by the fixture itself.
Tested here - https://buildkite.com/bugsnag/bugsnag-cocoa/builds/4140#903d8512-a752-47c8-8332-a33190e65ad7 and observed via screen sharing to verify that the fixture is terminated.
=> Use -KILL to terminate deadlocked Mac apps

CHANGELOG.md, lib/maze/capabilities.rb
Set capabilities to improve performance on Sauce Labs.
- Warnings in Appium resolve by using booleans rather than strings
- Capabilities set to avoid long waits for crashy scenarios (these are set by default on BrowserStack).
Tested locally against Sauce Labs.
=> Set capabilities to improve performance on Sauce Labs

CHANGELOG.md, Gemfile.lock, bugsnag-maze-runner.gemspec, lib/features/steps/app_automator_steps.rb, lib/features/steps/aws_sam_steps.rb, lib/features/steps/breadcrumb_steps.rb, lib/features/steps/error_reporting_steps.rb, lib/features/steps/feature_flag_steps.rb, lib/features/steps/header_steps.rb, lib/features/steps/log_steps.rb, lib/features/steps/multipart_request_steps.rb, lib/features/steps/payload_steps.rb, lib/features/steps/proxy_steps.rb, lib/features/steps/query_parameter_steps.rb, lib/features/steps/request_assertion_steps.rb, lib/features/steps/runner_steps.rb, lib/maze/assertions/request_set_assertions.rb, lib/maze/checks/assert_check.rb, lib/maze/checks/noop_check.rb, lib/maze/compare.rb
Follow-up to #327, refactoring the remaining codebase to use the new `Maze.check` and adding a few methods that were missed at first.
Refactoring and new methods added.
I have successfully tested local branches for the `bugsnag-js`, `bugsnag-cocoa` and `bugsnag-android` repos with updates to use this.
=> Refactor remaining codebase to use Maze.check

CHANGELOG.md, lib/maze/capabilities.rb
Reduce the time the iOS App Hang scenarios take to run locally.  For me it reduced the time from 8 minutes to 5.5.
These capabilities are set by default on BrowserStack, providing some confidence that they won't break tests.
Tested will a full test run locally.
=> Set capabilities to speed up App Hang tests locally

.buildkite/pipeline.yml, docker-compose.yml, test/fixtures/browser/Dockerfile, test/fixtures/browser/Gemfile, test/fixtures/browser/features/fixtures/test.html, test/fixtures/browser/features/handled_errors.feature, test/fixtures/browser/features/lib/server.rb, test/fixtures/browser/features/steps/browser_steps.rb, test/fixtures/browser/features/support/env.rb
Adds a new test fixture based on the JS Browser fixture to CI, ensuring breaking changes will be caught before release.
This currently only works on Ruby 2.7.  We'll need to update Selenium Webdriver to `~> v4.1`, which will also require Appium to be updated to `~> v12`.
Unfortunately that doesn't seem like a trivial update ([as demonstrated here](https://buildkite.com/bugsnag/maze-runner/builds/2033#cff7583f-16d6-4368-a959-ae00609bf452/223-242)), but will hopefully be fairly quick.
I'd suggest we merge this PR and I'll ticket the driver updates separately.
=> Add a browser smoke test platform to CI

CHANGELOG.md, Gemfile.lock, lib/features/support/internal_hooks.rb, lib/maze.rb
Update the retry plugin so that it only applies a retry if `--retry` has not already been set.  This prevents the plugin from stopping retries that have a blank allow in place.
Verified locally that `--retry` will retry all scenarios in a run and that `@retry` on a scenario will cause only that scenario to be retried (if `--retry` is not used).
=> Allow retry option to take effect

CHANGELOG.md, bin/maze-runner, dockerfiles/Dockerfile.audit, lib/maze.rb
Add the `--color` as a default argument to the cucumber command to output ANSI escaped characters on Windows
Add `--color` as a default argument to cucumber
Set the licence audit docker container version to `6.15.0` to fix issues with the latest version causing tests to fail
Argument has been manually added to a windows test to ensure that it gives the desired output.
=> Add --color as a default argument passed to Cucumber

.buildkite/pipeline.yml, CHANGELOG.md, dockerfiles/Dockerfile.audit, lib/maze.rb, lib/maze/browser_stack_utils.rb, test/browser_stack_utils_test.rb
Retry uploading the app to BrowserStack for a max of 3 times or until we get a success.
Decided to use a while loop rather than `Maze::Wait` as the upload could take longer than the timeout specified.
Add while loop to the `upload_app` function in the `browser_stack_utils.rb` to retry the app upload for max of 3 attempts or until we get a success
Full CI
=> Retry Failed BrowserStack App Uploads

CHANGELOG.md, Gemfile.lock, lib/features/steps/request_assertion_steps.rb, lib/maze.rb, lib/maze/assertions/request_set_assertions.rb, test/fixtures/comparison/features/scripts/send_request.sh, test/fixtures/comparison/features/test_unordered_requests.feature
Fixes an issue where the `the received errors match` step fails due to the `request_matches_row` method having been moved.
=> Fix received errors match step

CHANGELOG.md, lib/maze/browser_stack_devices.rb, lib/maze/capabilities.rb
Correct capability name to `disableAnimation`.  
See https://www.browserstack.com/app-automate/capabilities.
Android 6 and below doesn't support this capability and BrowserStack will raise an error if you try to set it. 
In addition to CI, I have manually run tests on Android against versions 5,6 and 7 (i.e. across the v6 boundary) and on iOS versions 10 and 15.
=> Correct capability to disableAnimation

CHANGELOG.md, lib/features/steps/request_assertion_steps.rb, lib/maze/bugsnag_config.rb, lib/maze/plugins/bugsnag_reporting_plugin.rb
We've implemented Bugsnag error reporting in Cucumber, but it's very noisy due to the presence of test failures preventing us from seeing unexpected errors as easily.
1. I've changed the "payloads not received" error from a standard `RuntimeError` to a `Test::Unit::AssertionFailedError`.  This isn't strictly correct, as there are many places where a systematic error can cause this assertion to fail, but it can also be reflective of a genuine test failure.  @twometresteve I'd suggest we make a custom error for this failure, then we can determine how to handle it on a separate basis (e.g. route it to a different bugsnag api-key)
2. I've added a filter to our Bugsnag config to drop events involving the `Test::Unit::AssertionFailedError` class, which will filter assertion failures out of our …
=> Decrease noise in Bugsnag by skipping assertion failures

CHANGELOG.md, Gemfile.lock, bin/maze-runner, dockerfiles/Dockerfile.ci, lib/maze/browsers_cbt.yml, lib/maze/capabilities.rb, lib/maze/configuration.rb, lib/maze/driver/browser.rb, lib/maze/hooks/browser_hooks.rb, lib/maze/option.rb, lib/maze/option/parser.rb, lib/maze/option/processor.rb, lib/maze/option/validator.rb, lib/maze/smart_bear_utils.rb, test/option/parser_test.rb, test/option/processor_test.rb, test/option/validator_test.rb
Add support for running Selenium tests on CrossBrowserTesting.
Follows the existing approach for BrowserStack browsers - the usage pattern is analogous. 
- New option for the `--farm` switch
- Capabilities YML file to support a range of browsers
- New SmartBear utils class for running the secure tunnel (this will overlap with Bitbar once added)
Unit tests updated.  Also ran the browser test in the repo against each browser option in the YML file.  I've not updated the pipeline to run against CBT just yet, as we need to perform some further testing before we move everything across.
=> Add support for CrossBrowserTesting

CHANGELOG.md, Gemfile.lock, lib/maze.rb, lib/maze/driver/appium.rb
Add access to driver.page_source, as described on https://appium.io/docs/en/commands/session/source.
Tested locally by logging the result in a real `bugsnag-android` test run.
=> Add driver.page_source

CHANGELOG.md, Gemfile.lock, bugsnag-maze-runner.gemspec, lib/maze/browser_stack_utils.rb, test/browser_stack_utils_test.rb
Retry failed app uploads for ten minutes, giving BrowserStack more of a chance to repair itself.
Number of iterations of retry loop increased, with sleep between and logging improved.
Covered by updating the existing unit test.
=> Retry failed app uploads for ten minutes

CHANGELOG.md, lib/maze/driver/appium.rb, lib/maze/hooks/appium_hooks.rb
Ensure devices are unlocked at the start of each test run.
If a device is already unlocked then Appium simply ignores the call.
Expose the Appium `driver.unlock` method and call it after starting the test session.
Covered by CI and I have tested that every version of Android and iOS that we run against is happy with the change.
=> Ensure devices are unlocked

CHANGELOG.md, Gemfile.lock, lib/maze.rb, lib/maze/terminating_server.rb
Up the '@max_received_size' for the terminating server to 1MB
Change `@max_received_size` to `1048576` for the terminating server.
Covered by CI
I've also installed this version and tested it locally.
```
I, [2022-04-21 16:27:41#61176]  INFO -- : Terminating server received request
I, [2022-04-21 16:27:41#61176]  INFO -- : Reading 1048576 bytes
```
=> Change the @max_received_size to 1MB

CHANGELOG.md, lib/maze/checks/assert_check.rb, lib/maze/checks/noop_check.rb
Corrects the implementation of `Maze.check.match`, which worked by chance for the simple case - but had misleading parameter names and would not have allowed a failure message to have been provided.
Tested locally with a scenario that uses the step `the {word} payload field {string} matches the regex {string}`.
=> Correct Maze.check.match implementation

CHANGELOG.md, Gemfile.lock, lib/maze.rb, lib/maze/hooks/appium_hooks.rb, lib/maze/option/processor.rb, lib/maze/option/validator.rb, test/hooks/appium_hooks_test.rb, test/option/processor_test.rb, test/option/validator_test.rb
Allow --os-version to be omitted when --farm=local.
Relaxes the CL parser and adds inference of OS version from the Appium session capabilities.  Those capabilities may not be right, but it doesn't really matter when running locally.
Verified this works locally against Appium 1.21.0 with Android 10 and iOS 15.3.  Unit tests also updated.
=> Allow --os-version to be omitted when --farm=local

CHANGELOG.md, lib/maze/hooks/browser_hooks.rb
Stop BrowserStack tunnel after browser test runs.
I stumbled upon the missing call, which was introduced in a refactor as part of v5.8.0 (July 2021).  I'm not sure if it could be causing PLAT-7670 or not (browser tests not always shutting down).
Reinstated call to stop the BrowserStack tunnel for browser test runs.
Covered by CI.
=> Stop BrowserStack tunnel after browser test runs

CHANGELOG.md, Gemfile.lock, docker-compose.yml, lib/maze.rb, lib/maze/hooks/appium_hooks.rb, lib/maze/hooks/browser_hooks.rb
Fix logging of BrowserStack session links.
Tested locally and by inspection of the CI build.
=> Fix logging of BrowserStack session links

CHANGELOG.md, lib/maze/hooks/browser_hooks.rb
Close Selenium session at end of test run.
Tested by inspecting the BrowserStack dashboard before and after the change (sessions did continue to report running, now they show as completed).
=> Close Selenium session at end of test run

CHANGELOG.md, Gemfile.lock, lib/maze.rb, lib/maze/driver/appium.rb, test/appium_driver_test.rb
Adds 5 retries with 10 seconds intervals over the course of a minute when starting the appium driver.
This should add some flexibility with appium test runs by allowing for initialisation/connection errors.
Unit tests have been added to ensure the functionality resolves as expected.
Note - Due to adding a significant time to the unit tests the full failure situation has _not_ been added to these tests, but it can on request.
In addition to the unit tests, basic localised testing has been performed.  The resulting output in a full failure scenario read:
```
I, [2022-05-05 16:14:39#83031]  INFO -- : Creating Appium driver instance
I, [2022-05-05 16:14:39#83031]  INFO -- : Appium driver initialized for:
I, [2022-05-05 16:14:39#83031]  INFO -- :     project : local
I, [2022-05-05 …
```
=> Add retries to appium driver failures

.buildkite/pipeline.yml, CHANGELOG.md, Gemfile.lock, lib/maze/configuration.rb, lib/maze/server.rb, lib/maze/servlets/servlet.rb, test/fixtures/android-appium-test/features/handled_exception.feature, test/fixtures/http-response/features/invalid_requests.feature, test/fixtures/http-response/features/scripts/send_invalid_error.rb, test/fixtures/http-response/features/steps/steps.rb
Allow invalid requests to be ignored on specific endpoints.
By default, Maze will captured invalid (e.g. unparsable as JSON) requests that are received and fail the scenario.  This isn't always desirable, though, so a new config value `captured_invalid_requests` is added to specify the types of requests that should be monitored for invalidity.
To use, a test suite would remove the request type it wants to remove in its `BeforeAll` hook, e.g:
```
Maze.config.captured_invalid_requests -= [:sessions]
```
Includes a slight refactor to pass a symbol from `Server` to each `Servlet` so that the `Servlet` know what type of request it is handling.
New test added, which fails if the `When I ignore invalid errors` step is commented out.
=> Allow invalid requests to be ignored on specific endpoints

CHANGELOG.md, bin/maze-runner, lib/maze.rb, lib/maze/browser_stack_devices.rb, lib/maze/option.rb, lib/maze/option/parser.rb
Adds an option to list all available device keys, along with the device and OS they represent in the command line.
Currently this only works for BrowserStack, but the method can be expanded upon to add more device farms as necessary.
=> Add  option to list available device farm devices

CHANGELOG.md, Gemfile.lock, lib/maze.rb, lib/maze/driver/appium.rb, lib/maze/hooks/appium_hooks.rb, test/appium_driver_test.rb, test/hooks/appium_hooks_test.rb
Updates the logic of retrying driver initialisation to:
- Retry 6 times on driver failures if a single device is provided
- Retry by iterating through the given list of devices if one is present
I've updated the current tests, and run some functional tests using existing e2e test fixtures which have worked as expected - this should be ready for review now.
=> Update start-driver retry logic to re-enable device lists

CHANGELOG.md, Gemfile.lock, lib/maze.rb, lib/maze/runner.rb
Allow access to pids created by the Runner.
This allows individual repos to perform special actions on processes created by the Runner without risking breaking the behaviour elsewhere (especially on different platforms).  E.g. it is useful to be able to use `pkill` to kill process groups, which Maze does not do.
`Maze::Runner.pids` made public.
Covered by CI and I have verified locally that the change will do what is needed.
=> Allow access to pids created by the Runner

CHANGELOG.md, Gemfile.lock, lib/maze.rb, lib/maze/helper.rb, test/fixtures/android-appium-test/features/handled_exception.feature, test/fixtures/android-appium-test/features/steps/steps.rb, test/fixtures/browser/features/handled_errors.feature, test/fixtures/browser/features/steps/browser_steps.rb
Update Maze::Helper.get_current_platform to support "browser" as a known platform.
I found this is useful on platforms like Unity where we want to discern between each of the target platforms (including WebGL, running in a browser).
Helper updated to report `browser` when in Browser mode, which is determined in the `BeforeAll` internal hook.
New steps added for the browser and Android tests.
=> Update Maze::Helper.get_current_platform to support browser

CHANGELOG.md, Gemfile.lock, bin/maze-runner, bugsnag-maze-runner.gemspec, lib/maze/browser_stack_devices.rb, lib/maze/browsers_bs.yml, lib/maze/capabilities.rb, lib/maze/driver/appium.rb, lib/maze/driver/browser.rb, lib/maze/helper.rb, lib/maze/hooks/appium_hooks.rb, lib/utils/deep_merge.rb, test/capabilities/devices_test.rb, test/fixtures/ios-app/features/steps/test_steps.rb, test/option/processor_test.rb
Update the Appium and Selenium dependencies to the latest available, which will hopefully lead to greater stability in the longer term.
Upgrading to Appium 12 means using Selenium 4, which enforces use of w3c capabilities.  That in turn means using Appium 1.15 or later, which would cause a problem for our iOS 10/11 tests.  They are currently using Appium 1.8 to dodge various bugs on either side that caused our tests to flake (heavily at times).  
I'm therefore parking this as a draft for the time being while we consider where we take our testing of these versions.
- Appium/Selenium versions bumped.  
- Capabilities updated to comply with w3c
- Deprecation warnings resolved by moving to new driver methods (`terminate_app` etc)
So far tested with the full bugsnag-cocoa pipeline, subset of …
=> Update Appium and Selenium dependencies (enforcing w3c capabilities)

lib/maze/browsers_bb.yml, lib/maze/capabilities.rb, lib/maze/hooks/browser_hooks.rb, lib/maze/option/processor.rb, lib/maze/option/validator.rb, lib/maze/smart_bear_utils.rb
Add basic support for Bitbar Web.
Note that this depends on us updating the Selenium client library, but other than that follows the approach for BrowserStack browsers and CrossBrowserTesting.
Tested locally against Bitbar Web using the browser tests in this repo.  We should conduct some further tests using the bugsnag-js Browser tests before release this (but this will go into an integration branch before that).
=> Basic support for Bitbar Web

CHANGELOG.md, Gemfile.lock, lib/features/support/internal_hooks.rb, lib/maze.rb
Lessens the visual impact of displaying scenario locations in Buildkite.
Uses ANSI color codes to make the locations grey (the same approach as Cucumber).
I've also wrapped the line in a guard so that it only gets printed on Buildkite.  Locally the line has always been a duplicate to what Cucumber produces, which we accepted for the benefit of being able to fold the logs.
See https://buildkite.com/bugsnag/maze-runner/builds/2435#018201ab-0de5-4964-80fd-63b0b51f2564.
=> Display scenario locations in grey

lib/maze/browsers_bb.yml, lib/maze/capabilities.rb, lib/maze/hooks/browser_hooks.rb
Allows the sue of more credentials by acquiring them from the TMS alongside BitBar devices.
Requires #380 to be merged first
=> BitBar web credentials from TMS

CHANGELOG.md, Gemfile.lock, lib/maze.rb, lib/maze/browsers_bs.yml
Adds some extra required browsers to the BS definitions file to facilitate their usage in Browser JS tests, based on the migration of browser tests doc.
=> V6 BS Browser updates

.buildkite/pipeline.yml, CHANGELOG.md, Gemfile.lock, lib/maze.rb, lib/maze/browser_stack_devices.rb
Add support for Android 13 beta on BrowserStack.
Follows the existing well-trodden path.
Also bumped the version that Maze Runner CI uses to Android 12 (will move to 13 once it's out of Beta).
Tested by temporarily adjusting the buildkite to include the new device here: https://buildkite.com/bugsnag/maze-runner/builds/2453
=> Add support for Android 13 beta on BrowserStack

CHANGELOG.md, Gemfile.lock, lib/maze/checks/assert_check.rb, lib/maze/plugins/cucumber_report_plugin.rb
Remove code that's no longer needed to avoid a breaking change.
This code was added in a previous version to avoid breaking some clients during a refactor.  Now the change has been made the code isn't needed anyway, especially now that we're into v7 (which no one is yet using).
Also fixed a minor code style issue.
Covered by CI.
=> Remove workaround code no longer necessary 

CHANGELOG.md, Gemfile.lock, lib/maze.rb, lib/maze/server.rb, lib/maze/servlets/command_servlet.rb, test/server_test.rb
Adds a UUID to all command payloads, generated when the server first starts, which will enable us to match a particular Maze-runner test run message to a device.
This will help to determine if there's any cross contamination between maze-runner command payloads anywhere.
=> Use UUIDs in command payloads for better tracking

CHANGELOG.md, Gemfile.lock, lib/maze.rb, lib/maze/hooks/appium_hooks.rb, test/hooks/appium_hooks_test.rb
Handle a `nil` device list, which happens when using `--farm=local` (because a `--device` option is not required).
Addition of a simple nil guard.
Tested locally to verify that:
- A session can be successfully created
- Retries still occur if the driver cannot be started
=> Handle nil device list

CHANGELOG.md, Gemfile.lock, bin/maze-runner, lib/maze/bitbar_devices.rb, lib/maze/bitbar_utils.rb, lib/maze/capabilities.rb, lib/maze/driver/appium.rb, lib/maze/hooks/appium_hooks.rb, lib/maze/option/processor.rb, lib/utils/selenium_money_patch.rb
Fix support for BitBar in Maze v7, where W3C capabilities are now mandatory (having upgraded appium_lib to v12).
To some extent the release of v7 was a little hasty, as we hadn't had the chance to retest and fix the BitBar integration.  This PR brings BitBar back as an option. 
- Capabilities updated to be W3C compliant
- Various tweaks to improve logging
- BitBar Appium server URL change to US, as our dedicated devices are located there
Tested locally:
- Android - successfully ran a single smoke test scenario several times.
- iOS - capabilities appear to be in order, but the server is complaining that the app (the Id given for the uploaded IPA) cannot be found.  Have raised with the BitBar team.
=> Fix support for BitBar (using W3C capabilities)

CHANGELOG.md, UPGRADING.md, lib/features/steps/request_assertion_steps.rb, lib/features/support/internal_hooks.rb, lib/maze/request_list.rb, lib/maze/servlets/command_servlet.rb, test/request_list_test.rb
Remove ambiguity from RequestList interface.
UPGRADING.md updated.
`RequestList.empty?` has been removed, as it was ambiguous whether it applied to all requests received, or just those 
that had not been processed.  It also meant that in general `empty?` was not the same as `size == 0`.  
`size` has also been renamed to `size_remaining` to avoid ambiguity.
Covered by CI and unit tests.
=> Remove ambiguity from RequestList interface

CHANGELOG.md, lib/maze/client/bb_client_utils.rb, lib/maze/hooks/browser_hooks.rb
Clear up resources after a BitBar Browser session - release the user from the TMS and stopping the secure tunnel.
Covered by CI.
=> Stop BitBar tunnel and release account on exit

CHANGELOG.md, lib/features/support/internal_hooks.rb, lib/maze/server.rb, test/fixtures/payload-helpers/features/compare_requests_json_fixtures.feature, test/fixtures/payload-helpers/features/scripts/send_request.sh, test/server_test.rb
Adds a new end for receiving trace requests, on `/traces`.
Follows the same approach as existing endpoints, e.g. #213.
A future PR will introduce JSON schema based validation of requests received on the endpoint.
New end point and tests.
Unit tests updated and new e2e test added to CI.
=> Add traces endpoint

CHANGELOG.md, Gemfile.lock, lib/features/steps/request_assertion_steps.rb, lib/maze.rb, lib/maze/request_list.rb, lib/maze/servlets/servlet.rb, test/fixtures/comparison/features/value_checks.feature, test/request_list_test.rb
Add a Cucumber step to allow received requests to be sorted by a given field key.  E.g:
```
I sort the errors by the payload field "events.0.exceptions.0.message"
```
In the `I wait to receive {int} {word}` step,  Maze Runner will sort the requests by `Bugsnag-Sent-At` header to deal with occasional race conditions.  However, this isn't always sufficient if a notifier is sending 
New Cucumber step powered by a new method on the `RequestList` class.
New e2e test added to CI.
=> Add Cucumber step to sort received requests by field key

CHANGELOG.md, Gemfile.lock, lib/maze.rb, lib/maze/checks/assert_check.rb, test/checks/assert_check_test.rb
Ensure String patterns behave as expected when calling Maze.check.match.
It's infuriating when you write a new Cucumber step that uses `Maze.check.match` and forget to convert the pattern into a `Rexexp` option.  It's completely unobvious to a developer when it seems it should just work - this change means you can pass either a `String` or `Rexexp` object.
New unit test added.
=> Ensure String patterns behave as expected when calling Maze.check.match

CHANGELOG.md, Gemfile.lock, bugsnag-maze-runner.gemspec, lib/maze.rb
Appium-lib-core 5.5.0 has released, which has broken some core functionality of the notifier.  This change restricts our W3C running mode to appium-lib-core 5.4.*, which runs as expected.
Note - the appium-lib-core release does not effect legacy running.
=> Ensure appium-lib-core is temporarily restricted to v5.4.0 in w3c mode

CHANGELOG.md, Gemfile.lock, lib/features/steps/network_steps.rb, lib/features/support/internal_hooks.rb, lib/maze.rb, lib/maze/server.rb, lib/maze/servlets/command_servlet.rb, lib/maze/servlets/log_servlet.rb, lib/maze/servlets/servlet.rb, test/fixtures/http-response/features/scripts/send_verbed_requests.rb, test/fixtures/http-response/features/set_different_responses.feature
Allows a "verb" to be specified when setting an HTTP response, so we can make our tests involving `OPTIONS` requests more deterministic
Expanded http_payload tests to cover the usage of the new steps.
=> Add step to allow setting a status code for specific connection types

CHANGELOG.md, lib/features/steps/request_assertion_steps.rb, lib/maze.rb, test/fixtures/comparison/features/test_across_requests.feature
Provide a step for check for a minimum number of requests (rather than a precise amount).
Sometimes a scenario doesn't care if extra requests are sent (e.g. due to automation quirks that leads to multiple app launches).  This new step provides more flexibility.
Step added to existing CI test.
=> Add step to check for a minimum number of requests

CHANGELOG.md, lib/maze/client/appium/bs_devices.rb
Remove support for Google Pixel running Android 8 - it has been deprecated by BrowserStack.
=> Remove support for Google Pixel running Android 8

CHANGELOG.md, Gemfile.lock, lib/maze.rb, lib/maze/option/processor.rb
Correct the setting of `Maze.config.os_version` when using the w3c protocol on BrowserStack.
Correct the capability that we pull out for use at the OS version in config.
Tested as part of updating bugsnag-android (OS version based `@skip`a were not working before this).
=> Use correct capability for OS version

CHANGELOG.md, lib/maze/client/appium/bs_client.rb
Log the device ID after connecting to a device on BrowserStack.
Tested locally with both Android and iOS devices.
=> Log device UDID on BrowserStack

CHANGELOG.md, Gemfile.lock, lib/maze.rb, lib/maze/browser_stack_devices.rb
Add support for iOS 16 on BrowserStack
Basic use tested locally using `bugsnag-cocoa`.
=> Add support for iOS 16 on BrowserStack

.buildkite/pipeline.yml
Allows tests on Android 7 to soft fail whilst the secure tunnel outage at BrowserStack is resolved.
Once the outage is resolved and the job starts running again we should remove the soft fail.
Covered by CI.
=> Temporary soft fail on Android 7

CHANGELOG.md, lib/features/steps/network_steps.rb, lib/features/support/internal_hooks.rb, lib/maze/server.rb
Refactor the response delay steps to use Maze::Generator, meaning that all the steps in `network_steps.rb` use a consistent approach (and code in `Maze::Server` etc is consistent as a result).
I considered adding a new step for controlling the response delay over a series of requests, but decided there was no need for this and adding it was potentially only creating a maintenance burden for ourselves.
Covered by existing e2e tests.
=> Refactor response delay steps to use Maze::Generator

CHANGELOG.md, Gemfile.lock, lib/features/steps/breadcrumb_steps.rb, lib/maze.rb, test/fixtures/payload-helpers/features/breadcrumb_json_fixtures.feature, test/fixtures/payload-helpers/features/support/send_request.rb
Enables us to verify that a breadcrumb with a specific message isn't present, even if a breadcrumb with the same type is present.
Added tests to verify positive conditions, and manually verified the step catches when the breadcrumb is present.
=> Add negative breadcrumb type and message step with tests

CHANGELOG.md, dockerfiles/Dockerfile.ci, lib/maze/docker.rb
`docker compose` (with a space) is v2 of the docker compose CLI. Currently Maze Runner uses `docker-compose`, which is now out of date and doesn't implement some commands (e.g. `docker compose cp`)
This is supposed to be backwards compatible, so we now always run docker compose commands with `docker compose`
=> Use 'docker compose' not 'docker-compose'

.buildkite/pipeline.yml, CHANGELOG.md, Gemfile.lock, lib/maze.rb, lib/maze/client/selenium/bb_browsers.yml
Bump Bitbar browser versions to those currently available:
This is a quick fix after some browsers we depend on slipped off of Bitbar.  In future we will implement a "latest" based option.
Partially covered by CI and I've run a test on every option locally.
=> Bump Bitbar browser versions

CHANGELOG.md, lib/maze/client/appium/bb_client.rb, lib/maze/client/appium/bs_client.rb, lib/maze/client/appium/bs_legacy_client.rb, lib/maze/configuration.rb, lib/maze/option.rb, lib/maze/option/parser.rb, lib/maze/option/processor.rb, test/option/parser_test.rb, test/option/processor_test.rb
Allow users to not use the secure tunnels provided by BrowserStack/Bitbar.
Adds a `--tunnel` (and `-no-tunnel` by virtue of it being a boolean).
There are some deployment environments where the secure tunnel is not required.  Not starting it saves some time and removes something potentially breakable from the equation, reducing flakes overall.
Default case is covered by CI and I've updated the unit tests for the command line option processing.  I've also performed some extra testing locally to ensure that the `--no-tunnel` option can be used with BrowserStack in both W3C and JWP modes of operations (which did uncover a bug - the capabilities should not be set in this case).
=> Add --tunnel option

CHANGELOG.md, lib/features/steps/runner_steps.rb, lib/maze/docker.rb, test/fixtures/docker-app/features/fixtures/docker-compose.yml, test/fixtures/docker-app/features/fixtures/sleepy/Dockerfile, test/fixtures/docker-app/features/run_docker_services.feature
Add support for running `docker compose exec` in tests, which allows running commands in already running containers
I've added two new steps as well:
> I execute the command {string} in the service {string}
> I execute the command {string} in the service {string} in the background
Where "in the background" means "pass the `--detach` option"
=> Add support for 'docker compose exec' commands

lib/features/steps/runner_steps.rb
Noticed I forgot to add docs for the steps added in #425 and I assume this is what's stopping them from showing up at https://bugsnag.github.io/maze-runner/requirements/step_transformers.html
=> Add missing docs to steps

CHANGELOG.md, lib/features/steps/breadcrumb_steps.rb, test/fixtures/payload-helpers/features/breadcrumb_json_fixtures.feature, test/fixtures/payload-helpers/features/support/send_request.rb
Adds two steps to allow tests to be more precise when dealing with breadcrumbs:
> the event has {int} breadcrumb(s)
> the event has no breadcrumbs
The current steps only allow checking if a breadcrumb exists at all, but not e.g. if it's the only instance of that breadcrumb. Context for this is wanting to check that breadcrumbs are cleared in between running queued jobs in Laravel, but other repos that manually clear breadcrumbs may also find this useful (e.g. Python)
=> Add steps to assert an event has _x_ breadcrumbs

lib/features/steps/breadcrumb_steps.rb
This step wasn't actually checking the name of the breadcrumb, so it would always pass if there was at least 1 breadcrumb with the right type
=> Add missing assertion to step

CHANGELOG.md, DOCS.md, Gemfile.lock, bugsnag-maze-runner.gemspec, lib/maze/logger.rb, test/logger_test.rb, test/test_helper.rb
This PR simplifies the default format of Maze Runner's logger, from this:
```
I, [2022-12-12 13:03:10 #98309]  INFO -- : Maze Runner v7.9.0
I, [2022-12-12 13:03:10 #98309]  INFO -- : No test report will be delivered for this run
I, [2022-12-12 13:03:10 #98309]  INFO -- : Running in command mode
I, [2022-12-12 13:03:10 #98309]  INFO -- : Starting mock server
I, [2022-12-12 13:03:10 #98309]  INFO -- : Fixture commands UUID: 083181b5-3cc9-4b51-a671-4562692fc1cd
I, [2022-12-12 13:03:10 #98309]  INFO -- : WEBrick 1.7.0
I, [2022-12-12 13:03:10 #98309]  INFO -- : ruby 3.1.2 (2022-04-12) [arm64-darwin21]
D, [2022-12-12 13:03:10 #98309] DEBUG -- : #<WEBrick::HTTPServlet::ProcHandler:0x00000001064ccd48 @proc=#<Proc:0x00000001064ccdc0 /Users/joe.haines/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/bundle …
```
=> Simplify logger's format

CHANGELOG.md, lib/maze/client/selenium/bs_browsers.yml
Add Safari 16 on BrowserStack.
Tested on CI with a temporary commit in the pipeline, now removed.
=> Add Safari 16 on BrowserStack

CHANGELOG.md, Gemfile.lock, lib/maze.rb, lib/maze/client/selenium/bs_browsers.yml
Fixes the addition of Safari in #440 .  Unfortunately I changed the BitBar step in the pipeline rather than BrowserStack, meaning that I did not exercise the new functionality at all.
Now tested properly with a temp commit:
https://buildkite.com/bugsnag/maze-runner/builds/2828
=> Correct capability for Safari 16

CHANGELOG.md, lib/features/steps/request_assertion_steps.rb, test/fixtures/comparison/features/value_checks.feature
Fixes the step `I have received at least {int} {word}`.
A bug crept into the implementation of this in the v7 uplift (`RequestList` no longer has a `size` method). 
Step added to tests on CI.
=> Fix step 'I have received at least {int} {word}'

CHANGELOG.md, lib/maze/client/appium/bs_client.rb, lib/maze/client/appium/bs_legacy_client.rb, lib/maze/client/selenium/bs_client.rb, lib/maze/driver/appium.rb, lib/maze/driver/browser.rb, test/appium_driver_test.rb
Avoid problems setting information in the BitBar dashboard caused by setting the `project` and `build` capabilities.
BitBar have their own capability, `bitbar_project`,for setting the project name in the dashboard, but it doesn't take effect if these capabilities are set.  This PR pushes the logic for setting the capabilities into the BrowserStack client rather than apply them for all device farms.
The main thing this change risked breaking was the links to the BrowserStack dashboard that we log at the start of each session.  I've run both browser and device sessions locally, in both legacy and w3c modes to check those.  I've also checked the links created on Buildkite.
=> Only set build and project capabilities for BrowserStack

CHANGELOG.md, lib/features/support/internal_hooks.rb, lib/maze.rb, lib/maze/client/appium.rb, lib/maze/client/appium/base_client.rb, lib/maze/client/appium/bs_client.rb, lib/maze/client/appium/bs_legacy_client.rb, lib/maze/client/bb_client_utils.rb, lib/maze/client/selenium.rb, lib/maze/client/selenium/base_client.rb, lib/maze/client/selenium/bb_client.rb, lib/maze/client/selenium/bs_client.rb, lib/maze/hooks/appium_hooks.rb, lib/maze/hooks/browser_hooks.rb, lib/maze/server.rb, lib/maze/servlets/command_servlet.rb, test/server_test.rb
Previously we were generating UUIDs in different part of the code for the Appium/Selenium session and for returning in `/command` messages.
This change unifies all of those under a single "run UUID".
Storing the UUID in the globally accessible `Maze.run_uuid` means that we can do away much of the previous plumbing.  It also means that the UUID returned in `/command`s will match that used for the BrowserStack session, which could be useful for analysis purposes.
- `Maze.run_uuid` added
- Generation of UUIDs collapsed to just one instance
- Various plumbing removed
Covered by CI and I've performed some basic checks that the BrowserStack dashboard link are still correct.
=> Generate and use a single UUID for for the application run

CHANGELOG.md, lib/maze/api/appium/file_manager.rb
Add `files` to the path for the fixture config file on Android.
Tested with the Android fixture locally on both BB and BS.
=> Tweak config file path for Android

CHANGELOG.md, Gemfile.lock, lib/maze.rb, lib/maze/client/appium/base_client.rb, lib/maze/client/appium/bb_client.rb, lib/maze/client/appium/bs_client.rb
Fix a bug that caused tests to fail on macOS and older mobile OS versions.
The push_file mechanism used in #456 is only supported from Appium version 1.15.  This means it can't be used with older mobile versions (roughly and adequately equivalent to Maze Runner's legacy mode).  It is also not supported on macOS, although we don't need it to be.
The fix was to push the logic that makes the push_file call further down the class hierarchy, so that it only take effect on the BitBar and BrowserStack devices farms - and only when legacy mode is not being employed.
Tested using a special branch of bugsnag-cocoa set to use these change.  See https://buildkite.com/bugsnag/bugsnag-cocoa/builds/6575#_.
=> Only write fixture config on modern mobiles

CHANGELOG.md, Gemfile.lock, lib/features/steps/trace_steps.rb, lib/maze.rb
Add a step to assert that no spans have been received, regardless of the number of traces sent (ie: only empty traces were sent). This is required to ensure that client-side sampling is working as expected.
Tested locally with a dependant feature.
=> Add a step to assert no spans were received

CHANGELOG.md, Gemfile.lock, lib/maze.rb, lib/maze/client/appium/bb_client.rb
Prevent BitBar Appium sessions from timing out.
By default, Appium sessions on BitBar will time out after 60 seconds of no Appium actively.  This frequently happens in "normal" condition for our tests (it fail be a test failure case, but we don't want to lose the whole Appium session because of it).
This change stops BitBar sessions from timing out at all due to lack of activity.
New capability added.  Technically I think it should go in the top level of the hash, but this doesn't get picked up by BitBar.  I've therefore added a note in case the behaviour changes over time.
Tested locally using a simple scenarios that just sleeps for 70 seconds.
=> Do not let BitBar Appium sessions timeout

CHANGELOG.md, lib/maze/client/appium/base_client.rb, lib/maze/client/appium/bb_devices.rb
Effects two BitBar device acquisition factors to improve stability:
- Reduces the chance of multiple tests simultaneously attempting to acquire the same device by having them randomly select a device from the requested list of devices
- When the device isn't available, instead of retrying with the same device (which previously worked with BrowserStack due to accessing an entire device pool) the logic will now re-acquire the device list, avoiding repeating the same failure multiple times.
Unit tests were attempted to be implemented, but proved un-suitable for this change set.  Any appium tests should prove suitable to verify the proper outcome.
=> Ensure device lists are re-acquired and accessed randomly when appium driver is being initialized

CHANGELOG.md, lib/maze/client/appium/bb_devices.rb
Sets a couple of capabilities needed for our Cocoa e2e tests to generally function on BitBar (using Appium 1.22).
I also took the opportunity to rename a variable, to make it more clear as to what we're querying in the BitBar API.
Tested on a dev branch of bugsnag-cocoa.
=> Set capabilities needed for iOS devices on BitBar

.buildkite/pipeline.yml, docker-compose.yml, test/fixtures/android-appium-test/Dockerfile.legacy, test/fixtures/android-appium-test/Dockerfile.w3c
Guard against obvious regression of Maze Runner's support for the BitBar device farm by running a basic set up tests on CI (as we already do for BrowserStack).
For now the step will use BitBar with the secure tunnel enabled.  If this proves to be problematic we can change it to use the AWS public IPs (as we are for our notifier repos).
I've also changed the Docker image used to run the tests so it just uses a volume to access the `features` folder rather than copying everything into it.  Steps that took 8 minutes to run now take 1!
Covered by CI.
=> Add BitBar device tests to CI

.buildkite/pipeline.yml, docker-compose.yml, lib/maze/client/appium/bb_client.rb, test/fixtures/android-appium-test/app/build.gradle, test/fixtures/android-appium-test/app/src/main/java/com/bugsnag/android/mazerunner/MainActivity.kt
Update the e2e test fixture for Android to read the Maze Runner address from disk and use the AWS public IP when running on BitBar.
The BitBar secure tunnel is very flaky and was causing frustration in Maze Runner builds.  This change means we're using the same approach for BitBar as bugsnag-android will.
I've also bumped the version of the Android notifier used by the fixture, as it was quite out of date.
Covered by CI.
=> Update Android test fixture to read Maze Address from disk

CHANGELOG.md, lib/maze/client/appium/bb_devices.rb, lib/maze/helper.rb
Provide a basic mechanism for exiting cleanly after logging a user-friendly error message.
Until now, Maze Runner has rather lazily `raise`d errors in order to terminate the current run.  Whilst this is appropriate for some cases, it is very unfriendly to users in many situations, as a large stack trace typically obfuscates the root cause of termination.  This change provides a basic mechanism for terminating the process cleanly when all that's needed is a simple message to the user.
Tested locally by adding a temporary line of code to force the failure condition.
=> Gracious exit for human-readable errors

CHANGELOG.md, docs/Device_Mode.md, lib/maze/client/appium/bb_devices.rb, lib/maze/client/bb_api_client.rb
Let `--device` specify a device, rather than just a device group, name on BitBar.
The main approach for using devices on BitBar is to provide a device group name, e.g. `ANDROID_10`.  We're finding that some test scenarios behave differently on specific devices, so this change makes it possible for the `--device` option to also specify a particular device.
Existing docs tweaked.
- New BitBar REST api method added and existing routines refactored 
- Device allocation logic updated to look for a device if no device group with the name if found
Device group use (the primary use) covered by CI.  Specific device use tested locally, e.g:
```
$ bundle exec maze-runner --farm=bb --device='Google Pixel 4 -US' ...
[17:05:19]  INFO: Starting SBSecureTunnel
[17:05:21]  INFO: 1 of 3 devices with name …
```
=> Allow --device to specify a BitBar device name

CHANGELOG.md, Gemfile.lock, lib/features/steps/trace_steps.rb, lib/maze.rb
Corrects the logic for step `a span field {string} matches the regex {string}`.
It should select the items that match, rather than barf on the first entry that does not.
Tested locally against the branch of `bugsnag-cocoa-performance` that discovered the bug.
=> Correct logic for span step

CHANGELOG.md, bin/maze-runner, lib/maze/client/appium/bb_client.rb, lib/maze/client/appium/bb_devices.rb, lib/maze/client/bb_api_client.rb
Allows a list of all device groups available to the given BitBar access key to be output to the console.
Running manually, sample outputs include:
- No access key specified:
```
bundle exec maze-runner --farm=bb --list-devices
...
Listing BitBar device groups available requires a valid access key
```
- Invalid access key (i.e. No device groups found):
```
bundle exec maze-runner --farm=bb --access-key=foobar --list-devices
...
There are no device groups available for the given user access key
```
- Valid access key:
```
bundle exec maze-runner --farm=bb --access-key=<REDACTED> --list-devices
...
BitBar device groups available:
------------------------------
Group name   : ANDROID_10
Group ID     : <ID>
OS           : ANDROID
Device count : 8
------------------------------
Group name   : …
```
=> Add --list-devices option for BitBar

CHANGELOG.md, bin/maze-runner, lib/maze/client/appium/bb_devices.rb, lib/maze/client/bb_api_client.rb
Allows a list of all devices belonging to a given BitBar access key and device group to be output to the console.
Running manually, sample outputs include:
- No access key specified:
```
bundle exec maze-runner --farm=bb --device=ANDROID_10 --list-devices
...
Listing BitBar devices or device groups available requires a valid access key
```
- Invalid access key (i.e. No device groups found):
```
bundle exec maze-runner --farm=bb --access-key=foobar --device=ANDROID_10 --list-devices
...
No device groups were found with the given name ANDROID_10
```
- Valid access key, invalid device group name:
```
bundle exec maze-runner --farm=bb --access-key=<REDACTED> --device=ANDROID_ --list-devices
...
No device groups were found with the given name ANDROID_
```
- Valid access key:
```
bundle exec …
```
=> Allow --list-devices option for BitBar to list devices belong to a device group

CHANGELOG.md, lib/maze/client/appium/bs_devices.rb, test/option/validator_test.rb
Remove support for Android 4 to 6 devices on BrowserStack.
These devices have either been explicitly deprecated by BrowserStack, or their avaialbility/stability is so poor thhat 
Changes verified by peer review and covered by CI.
=> Remove support for Android 4 to 6 devices on BrowserStack

CHANGELOG.md, Gemfile.lock, lib/maze.rb, lib/maze/client/selenium/bb_browsers.yml
For usage in Bugsnag JS browser test pipeline
=> Add chrome 43 & 72 and firefox 78 to available BitBar browsers

CHANGELOG.md, lib/features/support/internal_hooks.rb
Currently the document server is started in Maze Runner's `BeforeAll` block. This runs before any Maze Runner hooks are run, which is usually where Maze Runner configuration would be applied
For example, this doesn't currently work but will after this PR:
```rb
Maze.hooks.before_all do
Maze.config.document_server_root = 'some/path'
end
```
=> Start the document server after client hooks run

lib/maze/client/bb_client_utils.rb
The `SBSecureTunnel` binary expects to be run interactively in the foreground and so logs some pretty graphs showing the incoming/outgoing requests per second
This doesn't work nicely when it's run in the background by Maze Runner because updating the graphs causes the entire output to run again
Other than just spamming Maze Runner's output, this also appears to break Buildkite's log parsing:
Maze Runner will still collect the output to be logged at warning level if the process crashes, so this change _shouldn't_ hide legitimate problems
=> Remove `SBSecureTunnel` output in debug mode

.buildkite/pipeline.yml, CHANGELOG.md, lib/maze/client/selenium/bb_browsers.yml
BitBar now support using `latest` as a version to get the latest version of a given browser:
This PR adds the latest versions of Chrome, Firefox & Edge[^1] to `bb_browsers.yml` so we can use them in other repos
Updated the Firefox version to `firefox_latest` in the pipeline
[^1]: I've not added Safari as (presumably) it'd also need the `osVersion` to be `latest` and I'm not sure if that's possible — there are basically no docs on this AFAICT. Safari only updates its major version once per year, so it's not as onerous to update manually compared to other browsers
=> Add 'latest' versions of Chrome, Firefox & Edge to BitBar browser list

CHANGELOG.md, lib/maze/client/bb_client_utils.rb
Currently Maze Runner waits for the BitBar "ready file" to be deleted as a sign of the SBSecureTunnel being stopped. However, it doesn't look like this file is actually deleting and MR doesn't check if the wait succeeds — this means we wait for a full 30 seconds for every test run that uses BitBar
We can instead wait for the thread that's running the secure tunnel binary to stop
I've also added a log for the success & fail cases, so we know the status of the tunnel thread when exiting
=> Fix wait for the SBSecureTunnel stopping

CHANGELOG.md, Gemfile.lock, lib/maze.rb, lib/maze/schemas/trace_validator.rb, test/fixtures/payload-helpers/features/support/send_request.rb, test/fixtures/payload-helpers/features/traces_support.feature
Recently added trace payload validation breaks with full setups due to not allowing an exception through.
This PR adds that exception to the validation logic so a specific payload with an a single key of `resourceSpans` with no elements in the array will pass.
Added proper E2E tests to cover the scenario.
=> Add a passthrough in trace validation for initial sampling payloads

.buildkite/pipeline.yml
Main aim is to have an overall limit of 25 slots for BitBar devices, but also corrected a BS step.
Covered by CI.
=> Correct concurrency groups

CHANGELOG.md, lib/maze/client/appium/bb_client.rb, test/client/appium/bb_client_test.rb
Simplify how the BitBar project name and test run values are calculated, whilst also improving logging so that repos can more easily set themselves up with the right environment variables.
I've simplified the logic on Buildkite to avoid using Git - it's just an unnecessary complexity.  The Buildkite slug is adequate and invariably exactly the same.  I've also improved the logging to make it easier to see how values are generated and set up docker-compose services for CI accordingly.
Unit tests updated and given a trial run using bugsnag-android.
=> Improve calculation of BitBar dashboard properties

CHANGELOG.md, bin/upload-app, lib/maze/client/bb_client_utils.rb
This allows us to upload an app to BitBar early during a build process then use that application ID later in the build to avoid uploading build artefacts more than once.
While the `farm` argument will allow us to switch to BitBar, the default will remain as BrowserStack to maintain continuity with our current pipelines.
Tested multiple times to ensure the uploads function as expected with varying amounts of arguments present.
=> Update upload-app script for use with BitBar

CHANGELOG.md, lib/maze/client/selenium/base_client.rb, lib/maze/client/selenium/bb_client.rb, lib/maze/client/selenium/bs_client.rb, lib/maze/driver/browser.rb, lib/maze/hooks/browser_hooks.rb
Adds links after BitBar and BrowserStack selenium test runs for easy access to the sessions.
Note - I realise this means on a successful BrowserStack run the links will appear close to one another, but on an unsuccessful run being able to access the session from both the top and bottom of the test run could prove useful.
Verified the links are present and work manually.
=> Add Selenium session links after tests run

CHANGELOG.md, lib/features/steps/network_steps.rb
Fix an error in the `I open the URL {string}` step when running with Ruby 3.  Corresponds to the following warning in Ruby 2:
```
warning: calling URI.open via Kernel#open is deprecated, call URI.open directly or use URI#open
```
Reran the test in `bugsnag-java` that uncovered it.
=> Use URI.open directly

CHANGELOG.md, lib/features/steps/network_steps.rb, test/fixtures/http-response/features/scripts/send_verbed_requests.rb, test/fixtures/http-response/features/set_different_responses.feature
We've found that when setting status responses for incoming requests, OPTIONS requests can cause inconsistent behaviour between tests, and currently have to be specially accounted for.  Following discussion we believe that desiring a set response to effect the OPTIONS request is generally rare or undesirable behaviour.
This change introduces a default verb of POST for any step that sets a specific number of responses (next/list) if a verb isn't already specified.  This should have minimal impact across the vast majority of tests, but will put the status code steps more in line with their expected purpose.
Existing HTTP status tests have been updated to cover the new defaulting behaviour where it isn't covered already.
=> Set the default HTTP verb for status setting to 'POST' request only

CHANGELOG.md, lib/maze/driver/browser.rb
Fixes a crash when trying to retry browser tests:
`refresh` doesn't exist on the Selenium WebDriver, it's on the `navigate` object: https://www.selenium.dev/documentation/webdriver/interactions/navigation/#refresh
=> Fix crash when trying to retry browser tests

CHANGELOG.md, lib/maze/client/bb_client_utils.rb
Currently nothing checks if we successfully get BitBar credentials, so if the 30 minute timeout fails then we crash as `account_credentials` returns `false` and the code tries to use that as the credentials:
This PR changes this to raise an error explaining that fetching the credentials failed
I've also fixed the retry interval saying it's 30 seconds when it's actually 10 seconds
=> Improve handling when failing to get BitBar credentials

CHANGELOG.md, lib/maze/servlets/trace_servlet.rb
Cross-origin JavaScript requests are only allowed to read a set of "cors safe" headers by default. To allow scripts to read other headers, the server needs to set [`Access-Control-Expose-Headers`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Expose-Headers) and explicitly list any additional allowed headers
This PR adds `Bugsnag-Sampling-Probability` as an allowed header in the trace servlet
See https://github.com/bugsnag/bugsnag-js-performance/pull/96
=> Allow JS to access the sampling header

CHANGELOG.md, bin/upload-app
Fail upload-app with non-zero exit code if the BitBar access key is not provided.
When first using this in a pipeline it took me a while to realise that the previous Buildkite step had errored, but passed in Buildkite due to the exit code of 0.
Tested locally.
=> Fail upload-app with non-zero exit code

CHANGELOG.md, lib/maze/helper.rb, lib/maze/option/validator.rb
Allow the id for an app previously uploaded to BitBar to be read from a file.
This mechanism has been in place for BrowserStack for some time.  If the `--app` options starts with an `@` then Maze Runner will read the contents of the file.  The change had just not been applied on the BitBar side.
Tested locally.
=> Read app option from file

CHANGELOG.md, lib/maze/client/selenium/local_client.rb
Fixes a recently introduced crash in local selenium client.
This crash was readily reproducible by running `bundle exec maze-runner --farm=local --browser=firefox` in `test/fixtures/browser` - fixed after the change.
=> Fix crash in local selenium client

CHANGELOG.md, lib/features/steps/request_assertion_steps.rb
Use `JSONSchemer::Errors.pretty` to output a nicer JSON schema validation failure message:
- https://www.rubydoc.info/gems/json_schemer/0.2.24/JSONSchemer/Errors
- https://github.com/davishmcclurg/json_schemer/blob/master/lib/json_schemer/errors.rb
=> Improve JSON schema validation failure messages

.buildkite/pipeline.yml, CHANGELOG.md, lib/maze/client/selenium/bb_client.rb, test/fixtures/android-appium-test/app/src/main/java/com/bugsnag/android/mazerunner/MainActivity.kt, test/fixtures/browser/features/steps/browser_steps.rb
Fix an issue running browser tests on BitBar on local machines.
On CI, if the secure tunnel is used, we use multiple BitBar users as each user can only start a single secure tunnel.  Locally, there is no need to have separate users - local user accounts are sufficient.
This change was introduced in a recent PR, during a time that the secure tunnel was broken and so we couldn't test it locally.
I've made some changes to the browser test fixture so that the tests can be run on Chrome, Firefox or Safari on a local machine.
I've also bumped the version of Android in use for the legacy protocol (JsonWP) tests, as BrowserStack are increasingly short of Android 7 devices, causing unnecessary test failures.  We don't need to test on an old device to test the legacy protocol.
Tested locally and CI …
=> Only use separate BitBar accounts on CI

.buildkite/pipeline.yml, CHANGELOG.md, docs/Device_Mode.md, lib/maze/client/appium/bb_devices.rb, lib/maze/client/bb_api_client.rb
Allow multiple device group name for BitBar, from which an available device will be selected at random.
E.g. `--device=ANDROID_11|ANDROID_12`.
This change was slightly more complicated than I anticipated, as I needed to refactor some methods a little to handle multiple API calls.
Docs updated.
Covered by CI and I'm also performed some testing locally with both single and multiple device group names.
=> Allow multiple device groups to be listed

.buildkite/pipeline.yml, CHANGELOG.md, CONTRIBUTING.md, Gemfile.lock, UPGRADING.md, lib/maze.rb, lib/maze/option.rb, lib/maze/option/parser.rb, lib/maze/option/processor.rb, test/option/processor_test.rb
Name boolean CLI options consistently.
This is a breaking change (whilst we are already moving into v8).
I've just removed the `enable-` on a couple of command line options to be consistent with out Boolean options.  Although this might seem less clear when looking at options in isolation, I think it hangs together when considered the output from `--help` and also means less verbose use of the tool.
CLI help and upgrading guide updated.
Command line options and their symbolic names updated.
I've also set the `short:` options for all CLI options to `:none`, meaning that an abbreviated form of the CLI option will not be generated.  These can conflict with the underlying options for Cucumber in surprising ways (e.g. the `-e` Cucumber option suddenly meaning something completely different). …
=> Review command line options for consistency

.buildkite/pipeline.yml, CHANGELOG.md, docker-compose.yml, dockerfiles/Dockerfile.ci-ruby-2, dockerfiles/Dockerfile.ci-ruby-3
Update the shipped Docker image to be based on Ruby 3, rather than 2.  This applies to the image that uses the W3C protocol for Appium and Selenium.  The legacy (JSON-WP) image remains as Ruby 2, as Selenium 3 is not compatible with
Ruby 3.
The minimum Ruby version for development remains unchanged at 2, but shipping with 3 will allow clients to use the new language features in their test code.  
There's also sill the option of using the "legacy" image (which uses the JSON-WP protocol with Appium and Selenium.  The legacy image cannot be updated to Ruby 3, as the Selenium 3 client will not run with it.
I've refactored the Docker files/compose services a little - opting for a little duplication in exchange for (hopefully) greater clarity on what the pipeline is running.  Previously I found …
=> Update published Docker image to Ruby 3

.buildkite/pipeline.yml, CHANGELOG.md, UPGRADING.md, docs/Test_Outputs.md, lib/maze/api/appium/file_manager.rb, lib/maze/appium_server.rb, lib/maze/client/appium/bb_devices.rb, lib/maze/client/bb_api_client.rb, lib/maze/client/bb_client_utils.rb, lib/maze/logger.rb, lib/maze/repeaters/request_repeater.rb, lib/maze/server.rb, lib/maze/servlets/servlet.rb, lib/maze/terminating_server.rb, test/appium_server_test.rb
Add a `TRACE` log level.
The rule of thumb is that `DEBUG` level logs should be of use to people running Maze Runner tests.  `TRACE` level logs are of interest to people developing Maze Runner itself.
Markdown docs updated.
Built in logger monkey patches to add a TRACE level.  Existing DEBUG level logs reviewed throughout.
There was also a subtle build problem introduced by #534 - the tag for the Ruby 2 image that would pushed did not precisely match the tag being requested in another.  The build for that PR only passed because the tag previously existing in the development of the branch and so just happened to exist.  The problem only became evident due to the new branch name and "clean start".
Covered by CI and I also ran a quick test locally that the `DEBUG` and `TRACE` environment …
=> Add TRACE log level

CHANGELOG.md, UPGRADING.md, lib/features/steps/app_automator_steps.rb, lib/features/steps/header_steps.rb, lib/features/steps/multipart_request_steps.rb, lib/features/steps/payload_steps.rb, lib/features/steps/query_parameter_steps.rb, lib/features/steps/request_assertion_steps.rb, lib/features/steps/runner_steps.rb, lib/features/steps/trace_steps.rb, lib/features/steps/value_steps.rb, lib/features/support/cucumber_types.rb, lib/maze/schemas/trace_validator.rb, lib/maze/server.rb, lib/maze/servlets/servlet.rb, lib/maze/servlets/trace_servlet.rb, test/fixtures/framework/features/support/env.rb, test/fixtures/http-response/features/steps/steps.rb, test/fixtures/payload-helpers/features/traces_support.feature
Store trace sampling requests in their own list, allowing them to be inspected separately and avoiding flakes caused by race conditions between the receipt of them and regular trace requests.
The `Servlet` has been refactored slightly allowing the `TraceServlet` to put received requests into the appropriate list.
A custom Cucumber parameter type of `request_type` has been created, allowing arguments to have space in them without using speech marks (this can't be done with either `{word}` or `{string}` parameters).
Upgrading guide updated.
CI tests updated and I've also updated the entire set of `bugsnag-android-performance` tests to run against it.
=> Store sampling requests in their own list 

CHANGELOG.md, UPGRADING.md, lib/features/steps/header_steps.rb, lib/features/steps/request_assertion_steps.rb, test/fixtures/payload-helpers/features/compare_requests_json_fixtures.feature
A slightly pedantic clarification that the steps verify that the header is present/not present at all, as opposed to being present with some null value.
CI tests updated.  I also checked that the steps fail as expected by modifying the scenarios locally.
=> Reword header checking steps

CHANGELOG.md, lib/maze/client/selenium/bs_browsers.yml
Adds two devices required for testing JS performance to the BS driver:
- iphone_14, providing iOS 16
- Pixel 7, providing an up-to-date chrome driver
This _doesn't_ add an iOS 11 device, as that is already covered by the `iphone_x` device.
(Thoughts on changing the naming convention as a v8 release feature (in a separate PR)?  I was thinking just changing them to the OS version, so `iphone_14` just becomes `iOS_16` etc)
=> Add JS performance required BS devices to driver

CHANGELOG.md, Gemfile.lock, lib/features/support/internal_hooks.rb, lib/maze.rb
Output the traces that were received to stdout when a scenario fails on CI.
We do his for all other request types, it just got missed when traces were added.
Tested locally by artificially causing a scenario to fail and setting `BUILDKITE=1`.
=> Output received traces when scenario fails

CHANGELOG.md, UPGRADING.md, lib/maze/client/selenium/bs_browsers.yml
To make it clearer which devices and versions are being targeted when running tests on mobile browsers, the existing browsers have been renamed to an `os_version` format.
=> Rename BrowserStack mobile browsers to OS and version format

CHANGELOG.md, Gemfile.lock, bin/maze-runner, lib/maze.rb, lib/maze/option/parser.rb
Set the `--expand` Cucumber option by default, causing `Scenario Outline`s to be written out in full, as opposed to a single line for each instance of the scenario.
Tested locally by supplying each option on the command line - `--expand`, `--no-expand` and neither.
=> Expand Scenario Outlines by default

CHANGELOG.md, UPGRADING.md, lib/features/steps/network_steps.rb, lib/features/support/cucumber_types.rb, test/fixtures/http-response/features/set_different_responses.feature
Avoid the need for speech marks around the list of status codes, making it consistent with the Cucumber steps that accept 
just a single integer.
UPGRADING guide updated.
Covered by CI.
=> Remove speech marks from status codes list

CHANGELOG.md, lib/maze/client/appium/base_client.rb, lib/maze/driver/appium.rb
Prevent failed calls to `Maze.driver.unlock` from crashing Maze Runner.
Tested locally using bugsnag-cocoa with iOS 11 and the legacy driver mode (which found the issue).
=> Guard against Maze.driver.unlock raising and error

CHANGELOG.md, Gemfile.lock, lib/features/support/internal_hooks.rb, lib/maze.rb, lib/maze/logger.rb, lib/maze/maze_output.rb, lib/maze/servlets/log_servlet.rb, lib/maze/servlets/servlet.rb
Fixes a crash when trying to log gzipped trace requests, as well as making general improvements to the logging of requests.
Previous we tried to log the whole raw request in addition to the JSON formatted payload.  This failed for gzipped payloads, as the `request.body` was still in its binary form, but really logged the raw request wasn't that useful anyway.  Instead I've opted for logging specific fields within it, meaning we have more control of what is being logged.
Responses sent back from Maze Runner are now stored in the `RequestList`, allow us to log their headers and bodies too.
Tested locally, inspecting the `maze_output` contents and by forcing failures in a couple of pipelines:
[Android Performance (traces)](https://buildkite.com/bugsnag/bugsnag-android-performance/builds/999#0 …
=> Fix and improve logging of received requests

CHANGELOG.md, lib/maze/client/bb_api_client.rb
Add the `delete` method to the API request within the `delete_project` function
Built and tested locally
=> Update the delete method for purging projects on bitbar

CHANGELOG.md, Gemfile.lock, lib/maze.rb, lib/maze/client/appium/bb_client.rb
Set a timeout of ten minutes for BitBar Appium sessions if no operation is received.
There are a couple of reasons why indefinite timeouts are not a good idea:
- Docker containers running on our Buildkite CI instances terminate immediate on cancellation, meaning that cleanup code designed to terminate the Appium session is not invoked.
- The Ruby client can sometimes throw an error when creating a session, but leaving a session running.  Because of the error we don't have a handle on the session to close it.  Hopefully setting this capability will mean that it will take care of itself.
Tested using a build of bugsnag-cocoa here: https://buildkite.com/bugsnag/bugsnag-cocoa/builds/6967#_.  I cancelled two steps and observed the concurrent usage the BitBar dashboard drop down after 10 …
=> Set a sensible timeout for BitBar Appium sessions

CHANGELOG.md, Gemfile.lock, lib/maze.rb, lib/maze/servlets/servlet.rb
Only set HTTP response code for specific request types.  In particular, requests sent to `/metrics` should always return 200.
Covered by CI and having rerun a test from `bugsnag-unity` that broke when trying to add metrics.
=> Only set HTTP response code for specific request types

CHANGELOG.md, Gemfile.lock, lib/maze.rb, lib/maze/servlets/servlet.rb
Trace requests got missed from #565 .
Tested locally using a bugsnag-unity-performance test that found the issue.
=> Include traces when setting HTTP response codes

CHANGELOG.md, Gemfile.lock, lib/maze.rb, lib/maze/server.rb, test/server_test.rb
Add additional sourcemaps endpoints so that we can use MazeRunner to test the Bugsnag CLI.
Add the following endpoints to the mock server:
`/dart-symbol`
`/ndk-symbol`
`/proguard`
Updated tests, covered by CI
=> Add endpoints for bugsnag-cli testing

CHANGELOG.md, lib/features/steps/deprecated_steps.rb
Fix bug a bug introduced in #571 due to the order of parameters to the function being changed.
We added tests for the new steps in #571, but not the now deprecated step.  I've tested this change use bugsnag-cocoa-performance, which found the problem.
=> Fix bug in #571

CHANGELOG.md, lib/maze/schemas/trace_validator.rb, lib/maze/schemas/validator.rb, test/fixtures/payload-helpers/features/fixtures/maze-harness/features/scripts/send_trace.sh, test/fixtures/payload-helpers/features/scripts/send_gzip.sh, test/fixtures/payload-helpers/features/scripts/send_spans.sh, test/fixtures/payload-helpers/features/support/send_request.rb, test/schemas/trace_validation_test.rb
Adds validation of the following headers on every trace request received
- Bugsnag-Api-Key – 32 hex char guid
- Bugsnag-Sent-At – ISO 8601 date
- Bugsnag-Span-Sampling – of the format x:y where
- x is a decimal between 0 and 1 (inclusive)
- y is an integer 
Existing mechanism extended to include steps for validating headers.
Unit and e2e tests updated and I've also run the whole set of Android and Cocoa performance e2e tests against it.
=> Add validation of trace request headers

.buildkite/pipeline.yml, CHANGELOG.md, lib/features/support/internal_hooks.rb
Make it easier for Buildkite pipelines to upload all test results, by creating a zip archive of the `maze_output` folder.
Covered by CI and I've also tested locally that an existing file is deleted at the start of a run.
=> Create zip archive for maze_output directory

CHANGELOG.md, lib/maze/client/appium/bs_devices.rb, lib/maze/client/selenium/bs_browsers.yml
Samsung Galaxy S8 Plus has been deprecated by Browserstack but is still in use in the JS pipeline - this PR switches to using regular Samsung Galaxy S8 (which is still available as of writing: https://www.browserstack.com/list-of-browsers-and-platforms/automate)
=> Remove deprecated Galaxy S8 Plus device from BS devices

.buildkite/pipeline.yml, CHANGELOG.md, lib/features/support/internal_hooks.rb, lib/maze.rb
Make the `maze_output.zip` easily accessible from docker containers
Move the `maze_output.zip` to the `maze_output` folder when completed so that it can be easily accessed from within docker containers.
Covered via CI
=> Move maze_output.zip so that it can be easily accessed from docker containers

CHANGELOG.md, Gemfile.lock, lib/maze.rb, lib/maze/api/appium/file_manager.rb, lib/maze/configuration.rb
Allow push_file location for Android to be overidden.
Adds a new config value that can be set to push files to a different location on Android.  iOS have no other viable location to use, so there is no point in adding a config option for that.
Tested using a RN Perf branch that needs to read for the temp folder.
=> Allow push_file location for Android to be overidden

CHANGELOG.md, Gemfile.lock, lib/maze.rb, lib/maze/servlets/base_servlet.rb
Allow `Bugsnag-Uncompressed-Content-Length` in CORS header policy.
Reran the bugsnag-unity-performance test that found the issue.
=> Allow Bugsnag-Uncompressed-Content-Length in CORS header policy

CHANGELOG.md, Gemfile.lock, UPGRADING.md, lib/maze.rb, lib/maze/plugins/bugsnag_reporting_plugin.rb
Tweaks the context and grouping hash to improve the presentation of reported errors in the BugSnag Maze Runner dashboard.
For now I have just changed the grouping hash to the current scenario steps.  So, for example, different scenarios failing on the same `Background:` step will be grouped together.  Looking at the errors currently being reported I believe this will make it easier to analyse, although we may wantto make the mechanism more sophisticated in the future, allowing individual repos to choose their grouping strategy.
I have also tweaked the Context to include the repo name, as the dashboard contains errors from many different repos.
I forced an error to occur in a background step locally, which produced the following grouping and context in the dashboard.
=> Improve presentation of BugSnags

CHANGELOG.md, Gemfile.lock, lib/features/support/internal_hooks.rb, lib/maze.rb, lib/maze/aws_public_ip.rb, lib/maze/bugsnag_config.rb, lib/maze/client/appium/base_client.rb, lib/maze/client/bb_api_client.rb, lib/maze/client/bb_client_utils.rb, lib/maze/client/bs_client_utils.rb, lib/maze/driver/appium.rb, lib/maze/driver/browser.rb, lib/maze/hooks/appium_hooks.rb, lib/maze/logger.rb, lib/maze/proxy.rb, lib/maze/server.rb, lib/maze/servlets/log_servlet.rb, lib/maze/servlets/reflective_servlet.rb, lib/maze/servlets/servlet.rb, lib/maze/terminating_server.rb
Incorporate reporting of internal errors to BugSnag
The BugSnag integration is already in Maze Runner, so we can just call notify.
For now I have also disabled the feature that reports test failures as errors.  Although it works well, no one is currently using it and now we are sending internal errors, test failures will need to be routed to different dashboards.
It's not viable to test this outright at this stage, but I'll be monitoring the dashboard over the coming days to ensure it's presenting information as expected.
=> Incorporate reporting of internal errors to BugSnag

dockerfiles/Dockerfile.ci-ruby-2
Upgrade `apt` packages installed as part of the Maze Runner Docker build process to fix several vulnerabilities reported by AWS ECR scanning. 
Included in this is the patch for `libwebp | CVE-2023-4863` 
add `apt-get upgrade -y` to the Dockerfile
Covered by CI and manually checking the vulnerability report produced by CI
=> [PLAT-11091] Fix several vulnerabilities within the Maze Runner Docker image

CHANGELOG.md, Gemfile.lock, lib/maze/client/selenium/bb_client.rb
Fixes PLAT-10842 by extending session timeouts to 900 seconds (15 minutes).
=> Add BitBar selenium timeout extension

CHANGELOG.md, Gemfile.lock, lib/maze.rb, lib/maze/client/appium/local_client.rb
Reinstate a methods that was logically removed by a recent refactor.
Basic local testing has been performed.  Local Appium mode may still not work fully (it is used infrequently and in fact may no longer be needed), but this resolves an obvious problem.
=> Reinstate removed method

CHANGELOG.md, lib/maze/client/appium/bb_client.rb, lib/maze/client/appium/bb_devices.rb
On certain older appium servers in BitBar we're getting `'automationName' can't be blank` errors when starting sessions.  Upon contacting support we've been advised to add the `appium:options` capabilities under the main capabilities listing.
[Tested here](https://buildkite.com/bugsnag/bugsnag-cocoa/builds/7208#018b5cf3-afca-40cc-9020-1147a44e6a7d), certain tests are failing there, but not because of this change.
=> Add appium options capabilities for compatibility with older appium servers

CHANGELOG.md, Gemfile.lock, lib/maze.rb, lib/maze/client/appium/base_client.rb, lib/maze/client/appium/bb_client.rb, lib/maze/client/appium/bb_devices.rb, lib/maze/client/appium/bs_client.rb, test/client/appium/bb_client_test.rb, test/client/bb_client_utils_test.rb
Refactor the Appium client so that a different retry strategy can be employed for each device farm.  For BitBar, we will not retry after waiting for different times depending on the error that was experienced.
Relatively light refactor to push `handle_error` into each farm-specific client, allowing them to retry based on different logic.
Some manual testing performed, but the retry logic is primarily covered by a new unit test.
=> Retry creation of BitBar Appium sessions

CHANGELOG.md, Gemfile.lock, lib/maze.rb, lib/maze/servlets/servlet.rb
Fixes a crash when logging the message for invalid requests received.
Verified by peer review.
=> Fix crash when logging message for invalid requests

CHANGELOG.md, Gemfile.lock, lib/maze.rb, lib/maze/hooks/appium_hooks.rb, lib/maze/hooks/browser_hooks.rb
Notify errors that occur in Appium or Browser hooks, to provide better visibility of device farm issues occurring in e2e tests.
Tested by temporarily adding explicit `raise` statements to force an error condition.  In each case the error was reported to BugSnag, with an error still being output to the console and causing the test run to fail.
=> Notify errors that occur in Appium or Browser hooks

CHANGELOG.md, Gemfile.lock, lib/maze.rb, lib/maze/client/appium/bb_devices.rb
Further adds the appium options capabilities to the base hash of capabilities to attempt fixing of our `automationName` missing errors.
=> Add appium options to the base capabilities dictionary

CHANGELOG.md, Gemfile.lock, UPGRADING.md, lib/maze.rb, lib/maze/hooks/appium_hooks.rb
Remove use of the deprecated Appium `driver.reset` method.
This means that test fixtures and scenarios will need to take responsibility for clearing any persistent files between scenarios. The Android fixture already does this to a large extent, I just found a couple of extra files needed to be deleted.
Upgrading guide updated.
For BitBar devices only, `Maze.driver.reset` replaced with:
```
Maze.driver.terminate_app <app_id>
Maze.driver.activate_app <app_id>
```
Covered by CI.
=> Do not use driver.reset with BitBar devices

CHANGELOG.md, Gemfile.lock, bin/download-logs, bin/maze-runner, bin/purge-projects, bin/upload-app, lib/maze.rb
Works around the following crash on ARM-based macOS machines:
```
bash-3.2$ bundle exec maze-runner --version
Unable to load the EventMachine C extension; To use the pure-ruby reactor, require 'em/pure_ruby'
bundler: failed to load command: maze-runner (/Users/administrator/.rbenv/versions/2.7.7/lib/ruby/gems/2.7.0/bin/maze-runner)
```
Previously we can manually added this to the installed Gem on our ARM build servers, but we're changing how Gems and managed and so Maze Runner needs to work out of the box.
Covered by CI and by running the tool locally on an ARM machine.
=> Work around Event Machine issue on ARM macOS

CHANGELOG.md, Gemfile.lock, lib/maze.rb, lib/maze/client/appium/bb_devices.rb
Analogy of #590 for launching Android apps on BitBar.
Try to avoid mid-run test failures on BitBar caused by slow launch times of Android apps.
Increases the `uiautomator2ServerLaunchTimeout` from the default 20s to 60s.
Covered by CI and inspection of the BitBar dashboard.  I've checked in the Appium logs that there are no errors being caused by the capabilities now set.
=> Increase `uiautomator2ServerLaunchTimeout` to 60s on BitBar

CHANGELOG.md, Gemfile.lock, lib/maze.rb, lib/maze/client/appium/bb_devices.rb, lib/maze/client/appium/bs_devices.rb
Auto accept iOS alert this this one:
Tested locally with both BrowserStack and BitBar, verifying that the alert is dismissed in the video recording.
=> Auto-accept alerts on iOS

CHANGELOG.md, Gemfile.lock, lib/maze.rb, lib/maze/client/bb_client_utils.rb
Correct logic for use of BUILDKITE_RETRY_COUNT - it is zero based, so the first attempt of a job has a value of 0 for it.
Covered by CI.
=> Correct logic for use of BUILDKITE_RETRY_COUNT

CHANGELOG.md, lib/maze/api/appium/file_manager.rb
Enables us to pull files off of the device during an appium session, with specifics to be implemented on the individual feature setups.
I'm going to test this works using the scenario it was written for in Unity
=> Add method to allow pulling of files via appium client

CHANGELOG.md, UPGRADING.md, lib/maze/hooks/appium_hooks.rb
Reset the `Maze::Server` while the app is stopped.
There's a problem with idempotent Commands when it comes to moving onto the following scenario.  If the list of commands is reset while the fixture is still polling with a UUID, then warnings will be continually logged that there is no command with the given UUID.  Conversely, if the app is restarted before we clear the list then the scenario will get the command intended for the previous scenario and everything gets messed up.
One way to handle this is to reset the lists after we terminate the app but before we start it again for the next scenario.
I've also changed the calls used for stopping/starting the app to be consistent across all device farms and Appium versions.  It was getting confusing trying to remember each combination and …
=> Clear request lists while the app is stopped

CHANGELOG.md, lib/maze/client/appium/bb_client.rb
Adds a retry case for failed BitBar Appium sessions.  
If this error occurs then it's likely to be an isolated issue on a specific device and a near immediate retry on another device will succeed.
Covered by CI/peer review.
=> Add retry case for BitBar Appium sessions

CHANGELOG.md, Gemfile.lock, lib/maze.rb, lib/maze/hooks/appium_hooks.rb
When an internal error occurs in maze-runner the existing `after_all` hooks won't be run, meaning we won't get appium clients outputting the session(s) information for easy linking.
This moves the hook into the `at_exit` hook, ensuring it will always be run if possible.
=> Move appium outro logging to at_exit method

CHANGELOG.md, Gemfile.lock, lib/maze.rb, lib/maze/client/appium/bb_client.rb
Allow Appium versions to be set on BitBar (within the bounds of what BitBar supports).
Tested locally using the `--appium-version` option, inspecting the version in the appium.log in the dashboard.
=> Allow Appium versions to be set on BitBar

CHANGELOG.md, Gemfile.lock, docker-compose.yml, lib/features/support/internal_hooks.rb, lib/maze.rb, lib/maze/bugsnag_config.rb, lib/maze/option/parser.rb, lib/maze/plugins/bugsnag_reporting_plugin.rb
Re-enables reporting failures as errors to bugsnag, provided a specific API key is present.
Tested locally, confirming errors are reporting correctly.  They can be seen here:
https://app.bugsnag.com/bugsnag-test-projects/maze-runner-prime/errors/65ba7ddf7b68a4000717dece?filters[event.since]=all
=> Re-enable reporting on test failures

CHANGELOG.md, Gemfile.lock, lib/maze.rb, lib/maze/server.rb, test/server_test.rb
A basic endpoint `/dsym` added to the mock server for integration testing scenarios for dSYM uploads via BugSnag CLI.
This change follows the same what we had done previously for other symbol file upload endpoints. ([See here](https://github.com/bugsnag/maze-runner/pull/570/files))
N/A
Add the following endpoint to the mock server:
`/dsym`
Updated tests, covered by CI
=> [PLAT-11498] Setup for dSYM integration tests

CHANGELOG.md, Gemfile.lock, lib/maze.rb, lib/maze/hooks/appium_hooks.rb
Avoid failures from `terminate_app` not closing the app in sufficient time.
We have found that in some isolated test scenarios `terminate_app` does not stop the app from running in the 500ms that Appium allows, resulting in the test run failing.  This change catches the error and falls back to the slower but more forceful close_app instead.
Tested against the branch of `bugsnag-android` that discovered the issue.
=> Fall back to close_app if terminate_app fails

.buildkite/pipeline.yml, CHANGELOG.md, lib/maze/client/appium/base_client.rb
When running BrowserStack appium tests we've been seeing errors with the test fixture trying to access the config file that should be present on the device.  This is caused by the `app_id` being missing when uploaded the config file, causing it to upload in the wrong location.
It appears the session capabilities which would normally indicate the app_id are now missing in BrowserStack, namely the `CFBundleIdentifier` capability, so a check has been added to see if this is present, and if not will use the `bundleID` capability.
I've added this as a fix, but I'd like it to go out with #632 if possible, so once this is merged I'll rebase that PR and prepare the release in there.
=> Apply fix for app_id missing in BrowserStack tests

CHANGELOG.md, lib/maze/client/appium/bb_client.rb
Adds an additional retry parameter for appium server proxy failures
=> Add missing retry logic for appium proxy error

.buildkite/pipeline.yml, CHANGELOG.md, Gemfile.lock, lib/maze.rb, lib/maze/client/appium/base_client.rb, lib/maze/client/appium/bb_client.rb
Fixes the issue outlined in https://github.com/bugsnag/maze-runner/pull/633 in the v8 version
=> Fix app_id missing issue in v8

CHANGELOG.md, Gemfile.lock, lib/maze.rb, lib/maze/schemas/trace_validator.rb, test/fixtures/payload-helpers/features/fixtures/maze-harness/features/scripts/send_trace.sh, test/fixtures/payload-helpers/features/scripts/send_gzip.sh, test/fixtures/payload-helpers/features/scripts/send_spans.sh, test/fixtures/payload-helpers/features/support/send_request.rb, test/fixtures/payload-helpers/features/traces_support.feature
Remove trace request check on `service.version`, as not all our libraries will include it.
Tests updated to removed the payload elements that were previously required and would have caused validation to fail if not present.
=> Remove trace request check on `service.version`

CHANGELOG.md, Gemfile.lock, lib/features/steps/request_assertion_steps.rb, lib/features/support/cucumber_types.rb, lib/maze.rb, lib/maze/maze_output.rb, lib/maze/server.rb, lib/maze/servlets/reflective_servlet.rb, test/fixtures/payload-helpers/features/reflect_requests.feature, test/fixtures/payload-helpers/features/scripts/send_query.sh, test/fixtures/payload-helpers/features/steps/scripting_steps.rb, test/fixtures/payload-helpers/features/support/send_request.rb
I've tested locally, but have some ideas about a maze_output test fixture which could be added to verify this and all other post-test outputs if we think it's necessary.
=> Enable logging captured reflect requests

CHANGELOG.md, lib/maze/bugsnag_config.rb
In effort to slightly improve how errors are presented on our bugsnag dashboard, this PR adds a middleware to our bugsnag config that applies a different grouping hash based on the error message in the event a specific error type occurs.
Note: While this is a general structure that I think should do what we want, we can adjust and add new error classes that we believe to be ambiguous as and when we need to.
=> Improve maze feedback in bugsnag dashboard 

CHANGELOG.md, lib/features/support/internal_hooks.rb
Currently Maze Runner unconditionally creates a zip file from the `maze_output` directory even if `file_log` is disabled and therefore `maze_output` will be empty
This PR gates this behind the `Maze.config.file_log` flag so that an empty `maze_output` zip file isn't created every time Maze Runner runs
=> Only zip maze_output if file_log is on

Rakefile
Adds an in-process check to see if a given release matches (or exceeds) the release marked as 'latest' on github.  We'll only attempt to build and update the docs if that's the case.
=> Only update documentation if the release is the most recent

.buildkite/pipeline.yml, CHANGELOG.md, docs/Mock_Server.md, lib/maze/server.rb
Serve documents on primary port, under `/docs`.
A source of repeated annoyance are CORS errors stemming form the document server running on a separate port to the mock server that captures errors, traces, etc.  This change adds a document serving capability beneath `/docs`, avoiding that complication.
I've tested this using the Unity Performance tests that highlighted a new CORS issue when setting an addition header.
=> Serve documents on primary port

.gitignore, CHANGELOG.md, Gemfile.lock, lib/features/steps/trace_steps.rb, lib/maze.rb, test/fixtures/payload-helpers/features/span_support.feature
Allows us to create a table of properties to be verified in a specifically named span, in the form:
```
Then a span named {name} has the following properties:
| property                       | value                          |
| path.to.property          | here i am                   |
| spanId                          | 7af51275a21aa300   |
| attributes.0.key           | bugsnag.sampling.p |
```
Note, it verifies these by converting the properties into strings, as the table values will also be strings.  If this is a potential issue (i.e. numbers need to be within a tolerance) we can look at changing the behaviour.
=> Add span step for checking properties

docker-compose.yml
Resolve error parsing port information in the BitBar iOS test, which has come about at Cocoa has started to use the document server on port 9040.
Covered by inspecting the log out in the CI run.
=> Resolve error parsing port information

CHANGELOG.md, lib/maze/client/appium/bs_devices.rb
Required as the iPhone 11 Pro will no longer be supported by BrowserStack shortly.
Looking through our test setups I can't find anywhere this is actually in use, as we run all of our IOS_15 tests against BitBar, but it'll protect us against some weird nonsense in the future.
The other removed devices have no effect on our existing setup.
=> Update IOS_15 BrowserStack tests to iPhone 13

.buildkite/pipeline.yml, CHANGELOG.md, bugsnag-maze-runner.gemspec, lib/maze.rb
Fix bundle install (building native extensions) on newer ARM macs.
Tested locally and covered by CI.
=> Bump Curb to 1.0.5

CHANGELOG.md, lib/maze/driver/appium.rb
This should prevent multiple instances of server side errors appearing in the dashboard.  Afterwards any attempt to access the appium driver should fail without delivering a report, and the session will close.
=> Captures server-side error and removes appium driver

CHANGELOG.md, bin/maze-runner, lib/features/steps/trace_steps.rb, lib/features/support/internal_hooks.rb, lib/maze/configuration.rb, lib/maze/schemas/config_validator.rb, lib/maze/schemas/error_validator.rb, lib/maze/schemas/trace_validator.rb, lib/maze/schemas/validator.rb, lib/maze/schemas/validator_base.rb, test/fixtures/validation/Dockerfile, test/fixtures/validation/Gemfile, test/fixtures/validation/features/config_validation.feature, test/fixtures/validation/features/fixtures/maze-harness/Gemfile, test/fixtures/validation/features/fixtures/maze-harness/features/error_payload.feature, test/fixtures/validation/features/fixtures/maze-harness/features/steps/maze_harness_steps.rb, test/fixtures/validation/features/fixtures/maze-harness/features/support/env.rb, test/fixtures/validation/features/fixtures/maze-harness/features/trace_payload.feature, test/fixtures/validation/features/steps/scripting_steps.rb, test/fixtures/validation/features/support/env.rb, test/schemas/config_validation_test.rb, test/schemas/trace_validation_test.rb, test/schemas/validator_base_test.rb
The main functional change, this should allow us to write a custom validator in a block, which will automatically get run, replacing any existing validation.
This accomplishes a few things:
- Moves file loading from maze-runner to the main validator class
- Adjusts where the schema validation is called from, moving it into the validator itself.  This should allow us to add more complex logic to when and how it's called without cluttering our hooks
- Adds a config option to add validators for specific endpoints, a form of which will be demonstrated below
- Adds a config validator, a ValidatorBase subclass that wraps the blocks given above, allowing them to access the validator base functionality
I've semi-implemented validation in go, [which can be viewed …
=> Enable general validation through configuration

docs/Environment_Variables.md
A quick and basic docs page for the environment variables supported by Maze Runner.
N/A.
=> Docs for supported environment variables

CHANGELOG.md, bin/maze-runner, lib/features/support/internal_hooks.rb
Add the ability to override the `--fail-fast` option via an environment variable `MAZE_NO_FAIL_FAST`
Check if we're passing the `--fail-fast` option and that we've set the environment variable `MAZE_NO_FAIL_FAST` and remove the `--fail-fast` option before we pass it to cucumber.
Covered by CI
=> [PLAT-12770] Override `--fail-fast` via an environment variable

CHANGELOG.md, lib/maze/schemas/validator_base.rb, test/schemas/validator_base_test.rb
Adds some extra functions to shortcut a bunch of more complicated logic that had to be used in the [Go tests](https://github.com/bugsnag/bugsnag-go/pull/248).
=> Add extra validation steps and unit tests

CHANGELOG.md, bin/maze-runner, docs/Test_Inputs.md
Support reading command line options from files, reducing repetition in Buildkite pipeline files.
Docs updated.
Basic testing performed locally and by prototyping the change to the Android pipeline.
=> Read command line options from files

CHANGELOG.md, lib/maze.rb, lib/maze/configuration.rb, lib/maze/schemas/trace_validator.rb, lib/maze/schemas/validator.rb
Accomplishes 3 things:
- Changes how validation will be run by default, ensuring a given config block won't prevent the default validators being run
- Adds a new configuration option that will disable the default validation if called, but won't disable any custom configured validators:
```
Maze.config.skip_default_validation('errors')
```
- Adds a new configuration option that denotes that the test is in client mode, and indicates different kinds of verification could be used.  This is intended to be used to modify the internal validators in the case where certain attributes are not present in different notifier circumstances.
Not implemented yet...
=> Modify default setup for how validation works

CHANGELOG.md, bugsnag-maze-runner.gemspec, lib/maze.rb
Namely:
- `ostruct`
- `bigdecimal`
- `base64`
- `logger`
=> Add extra dependencies no longer part of the standard library to gemspec

.buildkite/pipeline.yml, CHANGELOG.md, bin/maze-runner, test/fixtures/cli/features/support/maze.all.cfg, test/fixtures/command-workflow/features/support/maze.all.cfg, test/fixtures/comparison/features/support/maze.all.cfg, test/fixtures/doc-server/features/support/maze.all.cfg, test/fixtures/docker-app/features/support/maze.all.cfg, test/fixtures/exit-codes/features/support/maze.all.cfg, test/fixtures/framework/features/support/maze.all.cfg, test/fixtures/http-response/features/support/maze.all.cfg, test/fixtures/payload-helpers/features/support/maze.all.cfg, test/fixtures/proxy/features/support/maze.all.cfg, test/fixtures/validation/features/support/maze.all.cfg
Moves some method calls around to allow options in config files to be passed into the options parser.
I've removed the exclusion of the purposefully failing features from the buildkite file calling those tests, and moved that option into the config files in each test fixture.   This should act as a trip, as if these excluded tests start failing the CI runs we'll know the options aren't being picked up from the config files.
=> Fix loading maze options from config files

CHANGELOG.md, lib/maze.rb, lib/maze/client/appium/bs_devices.rb
Add support for iOS 18 on BrowserStack.
I've also removed/changed some devices that have been deprecated (removed) by BrowserStack.
Tested locally using the Cocoa notifier test suite.
=> Add support for iOS 18 on BrowserStack

CHANGELOG.md, lib/maze/hooks/appium_hooks.rb
close_app has been deprecated, so this avoids calling it when an appium version of >2 is expected on the server
It's been run through the android tests here: https://buildkite.com/bugsnag/bugsnag-android/builds/11999
=> Add guard for close_app usage in appium v2+

CHANGELOG.md, lib/maze.rb, lib/maze/client/appium/bs_devices.rb
Add support for Android 15 on BrowserStack.
Tested locally using bugsnag-android.
=> Add support for Android 15 on BrowserStack

CHANGELOG.md, bugsnag-maze-runner.gemspec, lib/maze.rb
We've experienced errors for fixtures attempting to access the command servlet, which appear to be linked to the v1.0.0 release of the ruby `uri` module.
This pins the version to `~> 0.13.0` to avoid the issue.
A full test run [here](https://buildkite.com/bugsnag/maze-runner/builds/4278) confirmed the issue.
The test run of this PR proves the fix works.
=> Fix uri version to avoid command servlet errors

.buildkite/pipeline.yml, CHANGELOG.md, lib/maze.rb, lib/maze/client/selenium/bb_browsers.yml
Removes the deprecated safari 15 and 16 from our bitbar config, replacing them with 17 & 18
I've updated our safari 16 test to safari 18 in repo.
=> Remove safari 15 & 16, add 17 & 18

CHANGELOG.md, lib/maze/hooks/appium_hooks.rb
When calling terminate_app we sometimes get the sessionId error.  We can safely ignore it, and prevent it calling into our testing dashboard.
Should be covered by existing tests
=> Add extra guard when terminating appium session app

CHANGELOG.md, lib/maze.rb, lib/maze/aws_public_ip.rb
It seems like the curl command to get the public port sometimes returns successfully, but with an invalid response.
This change captures the subsequent error, allowing us to retry the command a number of times (currently 2, for 3 runs total).  After that it can be assumed we aren't going to receive a usable response and we should exit the test run.
Difficult to test currently, but non-invasive and we should be able to see any generated errors in the dashboard.
=> Add simple retry system for invalid aws public port response

CHANGELOG.md, lib/features/support/internal_hooks.rb, lib/maze.rb, lib/maze/client/appium/base_client.rb, lib/maze/client/selenium/base_client.rb, lib/maze/driver/appium.rb, lib/maze/driver/browser.rb, lib/maze/hooks/appium_hooks.rb, test/client/appium/bb_client_test.rb
Skip remaining scenarios if the Appium session fails.
Previously we were nilling out `Maze.driver` when it failed and guarding any uses of it with the `&.`.  That was generally ok, but the problem with `&.` is that operations essentially fail silently.  This change introduces an explicit failed state, which we can build more rigour on top of.
This change can be seen in action on this trial build:
https://buildkite.com/bugsnag/bugsnag-unity/builds/5355#0193cf49-9bcd-4d1a-adad-2d719f96ea89
Although there are many errors in amongst the skipped scenarios, they are due to the failed driver still attempting to be used.  I've raised PLAT-13337 to introduce a formal API for accessing driver methods instead of calling it directly.
=> Skip remaining scenarios if the Appium session fails

CHANGELOG.md, lib/maze/driver/browser.rb
This will include them being removed from the js-perf repo.  There was an additional change added to the trace servlet which has already been implemented in maze-runner, so that isn't being removed in this PR.
=> Add wait for element and click element patches from js-perf into browser driver

CHANGELOG.md, bin/maze-runner, lib/maze/api/appium/file_manager.rb, lib/maze/api/appium/manager.rb, test/api/appium/file_manager_test.rb
Add failed driver guard to FileManager Appium API.
First of a number of PRs to shift logic away from `Maze::Appium::Driver` and protect clients from noise caused by a failed underlying Appium driver.
Unit test added and some local testing performed, but further testing will be performed on the integration branch prior to release.
=> Add failed driver guard to FileManager Appium API

.buildkite/pipeline.yml, CHANGELOG.md, dockerfiles/Dockerfile.ci-ruby-3, lib/maze.rb, lib/maze/client/selenium/base_client.rb, lib/maze/client/selenium/bb_client.rb, lib/maze/client/selenium/bs_client.rb, lib/maze/configuration.rb, lib/maze/option/parser.rb, lib/maze/option/processor.rb, lib/maze/option/validator.rb, test/option/parser_test.rb, test/option/validator_test.rb
Allows multiple browsers to be specified when running against a browser farm.  This will utilise them in the order given until either the driver successfully boots or we run out of connection attempts.
The main bulk of the changes consist of refactoring the selenium driver start process, which should now function by:
- start_session is called on the appropriate BB or BS driver
- Local tunnels and initial capabilities are created according to the drivers needs
- start_driver is called, which sits in the base client
- start_driver attempts to start the driver with the existing attributes
- If this fails, the error is handled by the base client to determine if it is recoverable (it's assumed they all are currently)
- If multiple targets exist in the config browser_list the next one will be …
=> Allow multiple browsers to be specified

CHANGELOG.md, bin/maze-runner, lib/maze/api/appium/app_manager.rb, test/api/appium/app_manager_test.rb, test/api/appium/file_manager_test.rb, test/fixtures/appium-api/README.md, test/fixtures/appium-api/features/app-manager.feature, test/fixtures/appium-api/features/steps/steps.rb
Add an official API for performing operations and queries against an app with Appium.  Currently supports launch/close of the app, as well as getting the state of the run (running in forgeround, not running, etc).
Follows the same pattern as the File Manage API just added.
Adds a single class, `Maze::API::Appium::AppManager`.
New set of e2e tests added; not added to CI as yet but could be as part of the integration branch.
=> Add App Manger API

CHANGELOG.md, lib/maze/api/appium/app_manager.rb, test/api/appium/app_manager_test.rb, test/fixtures/appium-api/features/appium-api.feature, test/fixtures/appium-api/features/steps/steps.rb
Follow on from #713 , adding the `activate` and `terminate` methods.  These are now the preferred methods to use - close and launch are included for legacy purposes.
Existing unit and e2e tests updated to cover success and failure cases.
=> Add activate and terminate methods to App Manager API

.buildkite/pipeline.yml, .github/workflows/aws-lambda-tests.yml, CHANGELOG.md, lib/maze/aws/sam.rb, test/e2e/aws-sam/features/invoke.feature
This will hopefully be slightly more reliable than our existing test setup with docker on the macs, as it'll be a new environment every time.
This will also serve as a pattern to be used on other repos testing using AWS lambda.
=> Move AWS tests from MacOS boxes to github actions

CHANGELOG.md, lib/features/support/internal_hooks.rb
Do not run `Before` and `After` hooks for scenarios that are being skipped - avoiding unnecessary processing and errors from things like using a failed Appium driver.
Changes like this are hard to include in automated tests for this repo, but I have:
- Inspected the value of `scenario.status` in each hook block for skipped and not-skipped scenarios.
- Run a [full build](https://buildkite.com/bugsnag/bugsnag-android/builds/12555#_) for `bugsnag-android` against it to check nothing unexpected happens.
=> Skip hooks for skipped scenarios

CHANGELOG.md, lib/maze.rb, lib/maze/client/appium/bs_devices.rb
Use an alternative device to Google Pixel 4 for Android 11 on BrowserStack, as they are removing it.
Tested locally, in particular that the Android ANR tests work on it.
=> Avoid deprecated BrowserStack device

CHANGELOG.md, lib/maze.rb, lib/maze/api/appium/device_manager.rb, test/e2e/appium-api/features/appium-api.feature, test/e2e/appium-api/features/steps/steps.rb
Provide a mechanism for pressing the back button using Appium, whilst detecting a failed Appium driver.
For now this follows the existing pattern.  In a future change I'll reactor all the API methods to avoid duplicating the error handling.
e2e test updated and ran locally, inspecting the BrowserStack dashboard to be sure that the back button from pressed.
=> Add Appium API method for pressing the back button

CHANGELOG.md, lib/maze/api/appium/device_manager.rb, test/e2e/appium-api/features/appium-api.feature, test/e2e/appium-api/features/steps/steps.rb, test/unit/maze/api/appium/device_manager_test.rb
Add get_log to the DeviceManager API.
Follows the existing pattern for API methods.
Unit and e2e tests updated.
=> Add get_log to DeviceManager

CHANGELOG.md, lib/maze.rb, lib/maze/api/appium/app_manager.rb, test/unit/maze/api/appium/app_manager_test.rb
Ensure that `UnknownError`s occurring in `AppManager` routines are handled and lead to the driver being marked as failed.
Unit test updated for some basic coverage.
=> Handle Appium UnknownError in AppManager routines

CHANGELOG.md, lib/features/support/internal_hooks.rb, lib/maze.rb, lib/maze/api/appium/app_manager.rb, lib/maze/api/appium/device_manager.rb, lib/maze/api/appium/file_manager.rb, lib/maze/api/appium/ui_manager.rb, lib/maze/hooks/appium_hooks.rb, test/unit/maze/api/appium/app_manager_test.rb, test/unit/maze/api/appium/device_manager_test.rb, test/unit/maze/api/appium/ui_manager_test.rb
Ensure the scenario fails when the Appium driver fails.  Whilst the skipping of scenarios after an Appium driver failure has been working well, it was leading to false passes. 
The scenario will now be explicitly failed is the Appium driver has failed - either during the scenario steps themselves or in a previous `After` hook (note that `After` hooks are execute in reverse order of appearance in the file).
- Due to how we fall back to `close` if `terminate` fails, I've added an argument to allow us to suppress failing of the driver in that specific case.
- Logging improved so we can see which operation an error occurred on.  This may make the logs a little verbose in the short term due to logging in the driver itself, but this should resolve itself in due course when the driver is …
=> Fail scenario when Appium driver fails

CHANGELOG.md, lib/features/support/internal_hooks.rb, lib/maze.rb, lib/maze/hooks/appium_hooks.rb
Fail, rather than skip, remaining scenarios if the Appium/Selenium driver fails.
#740 attempted to fail any scenario that the driver failed in, but there was a gap in the logic.  
There are multiple Cucumber `After` hooks, of which:
- One will mark the scenario as failed if the driver failed.
- One will terminate then activate the app - both of these operations could result in a failed driver.
The problem is that they get executed in that order (implicitly due to the order in which they are declared in files).  That meant the driver could fail and not fail the current scenario.  The `Before` hook for the next scenario would then run and skip the scenario because of the failed driver - so the run as a whole would never be failed.
This change ensures subsequent scenarios and therefore the …
=> Explicitly fail remining scenarios if driver fails

CHANGELOG.md, lib/maze.rb, lib/maze/client/appium/bb_client.rb
Retry BitBar Appium session creation if beaten to device.
There's an inherent race condition if using the BB API to find a free device before trying to start an Appium session with it.  Another user (or just ourselves in another CI job) can get to the device first.  This change means MR will simply retry if it gets an error of the following form:
```
Status code 400.  Payload: {"sessionId"=>nil, "message"=>"com.testdroid.api.APIException: Failed to submit test run! Device model with name 'Apple iPhone XS A1920 14.0.1 -US' is currently unavailable.", "value"=>{"message"=>"com.testdroid.api.APIException: Failed to submit test run! Device model with name 'Apple iPhone XS A1920 14.0.1 -US' is currently unavailable.", "origValue"=>"com.testdroid.api.APIException: Failed to submit test run! …
```
=> Retry BitBar Appium session creation if beaten to device

CHANGELOG.md, lib/features/steps/app_automator_steps.rb, lib/maze.rb, lib/maze/api/appium/app_manager.rb, test/e2e/appium-api/features/appium-api.feature, test/unit/maze/api/appium/app_manager_test.rb
Adds `background` to the `AppManager` API class.
e2e and unit tests updated.
=> Add background to AppManager API

CHANGELOG.md, lib/maze.rb, lib/maze/driver/browser.rb
Remove erroneous use of global variable from browser driver `click_element`.
The use of `$browser` was an error resulting from moving the method in from the bugsnag-js-performance repo in a recently PR (the repo had contained a monkey patch).  We didn't notice as that is the only repo using the method and it works in that context.  If another repo tried to use the method an error would be raised for `$browser` not being initialised.
This change plays into a wider change - removing the use of legacy driver modes from repos (via `USE_LEGACY_MODE`).  I've run all the JS performance tests against this change in non-legacy mode.  No other repos are using the method changed (as noted above).
=> Remove erroneous use of global variable from browser driver `click_element`

CHANGELOG.md, lib/maze.rb, lib/maze/client/selenium/bs_browsers.yml
Add Edge 81 on BrowserStack and fix inconsistent capability names.
The are two styles of capability - for the legacy JWP mode (`snake_case`) and W3C (`camelCase`).  There's code in Maze Runner to convert from W3C to JWP when in the legacy mode, so everything should appear in camel case in the YAML file.
I've run a test against all of the browsers changed, in both legcy and W3C mode, checking in the BS dashboard that the right browser was used.
=> Add Edge 81 on BrowserStack and fix inconsistent capability names

CHANGELOG.md, lib/maze/api/appium/file_manager.rb, test/unit/maze/api/appium/file_manager_test.rb
Adds a FileManager API method to pull the whole app folder (and a zip file in a byte array).
Unit tests added for the basic logic and I've tested it locally with both iOS and Android.
=> Add API method to pull app folder

CHANGELOG.md, lib/features/support/internal_hooks.rb
Attempts to fix this issue when logging received invalid requests to console:
This is a difficult area to test as it relies on an error condition occurring to exercise the code, although the change should not make anything worse when the tests were failing and code crashing in the first place.  I'm going to try and create some form of automated test for this area in upcoming work.
=> Guard logging of invalid request headers

CHANGELOG.md, lib/maze.rb, lib/maze/servlets/servlet.rb
Prevent the following crash when writing invalid requests to file:
```
undefined method `body' for nil:NilClass (NoMethodError)
maze-runner/lib/maze/maze_output.rb:83:in `block (3 levels) in write_requests'
```
Tested locally using curl to send messages with an invalid JSON payload and wrong content-length respectively (exercising the two code paths changed).
=> Prevent crash when writing invalid requests to file

CHANGELOG.md, lib/features/steps/request_assertion_steps.rb, lib/maze.rb, lib/maze/request_list.rb, test/e2e/payload-helpers/features/breadcrumb_json_fixtures.feature, test/unit/maze/request_list_test.rb
Add the Cucumber step `I discard all {request_type}`.
The step `I clear the error queue` already exists, but it's almost certainly not what clients want as it removes all trace of the errors that were received.  In particular, when received errors are written to file at the end of the scenario they are not included, potentially leading to a great deal of confusion.
Unit test added for the `RequestList` update and exist scenario updated to include the new step.
=> Add step "I discard all {request_type}"

CHANGELOG.md, lib/maze/api/appium/manager.rb
Avoid double-reporting of Appium errors.
Uses the [documented approach](https://docs.bugsnag.com/platforms/ruby/other/#avoiding-re-notifying-exceptions) for this situation.
Tested locally by forcing an error in an Appium method called by the Cucumber `After` hook.  The error is notified just once and the scenario still fails as we expect.
=> Avoid double-reporting of Appium errors

CHANGELOG.md, lib/maze/hooks/appium_hooks.rb
Ensure Bugsnag reports for the Appium session status are sent before Bugsnag shuts down.
We were trying to send the report for the Appium session during `at_exit`, but the Bugsnag notifier shuts its internal queue down in `at_exit` and so the reports were often not getting sent (despite it indicating that it was on the console).
Tested locally and by CI.
=> Stop and report on Appium session before at_exit

CHANGELOG.md, lib/maze.rb, lib/maze/server.rb, test/unit/maze/server_test.rb
To allow us to test the unity-line-mappings changes to the BugSnag CLI we need to mock the unity-line-mappings endpoint within Maze Runner.
Covered by CI
=>  Add the unity-line-mappings endpoint to the mock server

CHANGELOG.md, bugsnag-maze-runner.gemspec, lib/maze.rb
Removes the pin for the `uri` Gem, allowing different versions of Ruby to use the version included with it.
#700 introduced the pin to deal with errors when making requests to the `/command` endpoint, but it no longer seems to be necessary (Maze Runner CI failed before the pin and it now passes again without).  `uri` is a [standard gem](https://stdgems.org/uri/) and different versions of Ruby include different versions of it.  Pinning it to a later version was causing issues in the Ruby notifier tests.
Covered by CI.
=> Remove pin for `uri` standard gem

CHANGELOG.md, lib/maze.rb, lib/maze/hooks/appium_hooks.rb
Remove reporting of Appium metrics to Datadog.
This functionality has now been overtaken by reporting Appium session outcomes to a Bugsnag dashboard.
Covered by CI.
=> Remove reporting of Appium metrics to Datadog

CHANGELOG.md, lib/maze/aws_public_ip.rb, lib/maze/plugins/datadog_metrics_plugin.rb
Set metadata token header when retrieving public IP of Docker container.
Response to an infrastructure change that meant Maze Runner was unable to retrieve the public IP of the running Docker contain, breaking any tests that required it (all of our BitBar CI tests in particular).
Core use case is covered by CI, I'll test the DataDog aspect in slower time as the priority is getting CI moving again.
=> Set metadata 

.buildkite/pipeline.yml, docker-compose.yml
Separate Buildkite plugins into different steps to avoid any being ignored in future releases of the Buildkite agent.
I've also remove the version from docker-compose.yml to remove a warning from the console output.
Covered by CI.
=> Separate Buildkite plugins into different steps

CHANGELOG.md, bugsnag-maze-runner.gemspec, lib/maze.rb
Include the missing dependency in the gem.spec for the `bencmark-to-datadog` tool
=> Add missing dep for benchmark tool

CHANGELOG.md, Gemfile, bugsnag-maze-runner.gemspec, lib/maze.rb
Correct dependency on Datadog API client.
I was able to reproduce the error caused after running `bundle clean` locally.  After the fix I could then run `bundle exec benchmarks-to-datadog` and get the usage output without error.
=> Correct dependency on Datadog API client

.buildkite/pipeline.yml, CHANGELOG.md, UPGRADING.md, bugsnag-maze-runner.gemspec, lib/maze.rb
Minimum Ruby version increased to 3.1 (due to Cucumber upgrade to v10).
Also a few other minor unrelated changes.
Covered by CI.
=> Minimum Ruby version increased to 3.1

CHANGELOG.md, lib/maze/plugins/global_retry_plugin.rb, lib/maze/retry_handler.rb, test/unit/maze/retry_handler_test.rb
Remove scenario retries for driver errors.
The approach used is now too fine grained and retries for driver failures are handled at a high level (using the exit code and Buildkite auto retries).
Covered by CI.
=> Remove scenario retries for driver errors

CHANGELOG.md, dockerfiles/Dockerfile.ci, lib/maze.rb
Downgrade Ruby in the published Docker image to avoid repetitive frozen string literal warnings like this:
```
/usr/local/bundle/gems/rubyzip-2.3.2/lib/zip/ioextras.rb:9: warning: literal string will be frozen in the future (run with --debug-frozen-string-literal for more information)
```
An alternative approach might have been to upgrade our dependency on`rubyzip` to 3.0, but `selenium-webriver` (a sub-dependency) places a constraint of `< 3.0` on it and there is not yet a version of `appium_lib_core` that depends on a version without it. 
Covered by CI - checking that the warnings are no longer shown at the end of each run in a Docker container.
=> Downgrade Ruby to avoid repetitive frozen string literal warnings

CHANGELOG.md, lib/maze/api/cucumber/scenario.rb, lib/maze/client/appium/bb_devices.rb
Stop using the `deviceGroupId` capability as it no longer consistently provides an available device.
I've simply removed the `if device_group_ids.size > 1` guard and what was its `else` branch, meaning that we will always query the API for an available device within that group.  Although we might lose a race with another Maze Runner istance, we have retry logic for that and overall it will be more reliable and within our control.
A Buildkite job that needed ANDROID_8 failed to get an available device with.the previous version of MR (using the capability).  Seconds later I ran this branch locally and it obtained a device on the first attempt.
=> Stop using BitBar deviceGroupId capability
