bugsnag/maze-runner

- lib/features/steps/request_assertion_steps.rb
Adds a step to check that a request part is null.
> Add step to check null request part

- bugsnag-maze-runner.gemspec
- pinned cucumber-expressions to 5.0.15
> fix(cucumber-expressions): Pin cucumber-expressions version

- lib/features/steps/error_reporting_steps.rb
- lib/features/steps/request_assertion_steps.rb
As per https://github.com/bugsnag/bugsnag-dotnet/pull/94#pullrequestreview-116802884, 4 is preferred
> Update expected version header

- lib/features/steps/request_assertion_steps.rb
More IE8/9 requirements!
We need to make assertions about the query parameters instead of the headers.
> Add steps for making assertions about query parameters

- Gemfile.lock
- bugsnag-maze-runner.gemspec
- lib/features/support/env.rb
Adds the OS gem to the gemspec for the current_ip call
> Add OS gem for current ip call

- lib/features/steps/request_assertion_steps.rb
There should be a space between request and request number
> Fix type in steps so other steps work

- lib/features/steps/error_reporting_steps.rb
- test/fixtures/browserstack-app/features/handled_exception.feature
- test/fixtures/browserstack-app/features/support/env.rb
Fixes incorrect elements with expecting specific payload_version
> Fix variable typo

- lib/features/steps/error_reporting_steps.rb
- lib/features/steps/request_assertion_steps.rb
- test/fixtures/browserstack-app/features/handled_exception.feature
- test/fixtures/browserstack-app/features/support/env.rb
Enables the usage of environment variables in tests, allowing specific version testing in future tests.
Added verification to browserstack integration test.
> V2 enable environment variables

- lib/features/steps/value_steps.rb
Fixes an issue where the field being recorded was used as the key instead of the desired key.
> Fix comparisons: Ensure key is used over field

- .buildkite/pipeline.yml
Enables slashes in branch names to be used in maze-runner v2 using the newly added `BRANCH_NAME` environment variable.
> Enable slashes in branch names

- .buildkite/pipeline.yml
- .gitignore
- README.md
- Rakefile
- lib/features/steps/android_steps.rb
- lib/features/steps/app_automator_steps.rb
- lib/features/steps/build_api_steps.rb
- lib/features/steps/error_reporting_steps.rb
- lib/features/steps/network_steps.rb
- lib/features/steps/request_assertion_steps.rb
- lib/features/steps/runner_steps.rb
- lib/features/steps/session_tracking_steps.rb
- lib/features/steps/value_steps.rb
- lib/features/support/capabilities/devices.rb
- lib/features/support/compare.rb
- lib/features/support/docker.rb
- lib/features/support/env.rb
- lib/features/support/fast_selenium.rb
- lib/features/support/network.rb
- lib/features/support/runner.rb
- lib/features/support/server.rb
- lib/features/support/values.rb
- yard-config
- Adds yardoc strings to all steps and publicly accessible methods and classes
- Adds yard and appropriate rake task to construct documentation using yard
- Adds (currently disabled) prep work for build and publishing documentation to github pages as part of CI
- Enable and test Github pages CI integration
> V2 documentation updates

- README.md
Modified for better personal understanding (and hopefully helpful more widely!).  Feel free to disagree :-)
Just the README.md
n/a
For the submitter, initial self-review:
- This pull request is ready for:
For the pull request reviewer(s), this changeset has been reviewed for:
> Small typographic and formatting changes.

- lib/features/steps/request_assertion_steps.rb
[Note: This duplicates #80.  Branches containing '/' cause Buildkite issues so the branch was recreated]
Add a string-not-equal assertion step.
Copy/paste the string-equal-to and change the match text and assertion appropriately.
Added `Then()` to `request_assertion_steps.rb`.
Tested through use in Cocoa notifier.
For the submitter, initial self-review:
- This pull request is ready for:
For the pull request reviewer(s), this changeset has been reviewed for:
> Add a string-not-equal assertion step

- lib/features/steps/session_tracking_steps.rb
Added a not-equals-to assertion for session fields.
Just the one file: `session-_tracking_steps.rb`
`bugsnag-cocoa` CI tests make use of this feature.
For the submitter, initial self-review:
- This pull request is ready for:
For the pull request reviewer(s), this changeset has been reviewed for:
> Added Session field-not-equal assertion.

- CHANGELOG.md
- lib/features/steps/app_automator_steps.rb
- lib/features/support/app_automate_driver.rb
- test/app_automate_driver_test.rb
Add steps to:
- Clear an element 
- Clear an element before sending keys to it
Unit tests added accordingly.
> Add ability to clear element

- lib/version.rb
> Bump version to 2.2.0 for release

- CHANGELOG.md
- Gemfile.lock
- lib/features/steps/app_automator_steps.rb
- lib/version.rb
- test/fixtures/browserstack-app/features/handled_exception.feature
Correct Ruby usage error when passing defaulted parameter.
> Correct passing of defaulted parameter

- CHANGELOG.md
- lib/features/hooks/hooks.rb
- lib/features/steps/request_assertion_steps.rb
- lib/features/support/assertions/request_set_assertions.rb
- lib/features/support/helper.rb
- test/assertions/request_set_assertions_test.rb
- test/fixtures/comparison/features/scripts/send_request.sh
- test/fixtures/comparison/features/steps/scripting_steps.rb
- test/fixtures/comparison/features/test_unordered_requests.feature
Resolves a bug where the environment was not clear at the start of each scenario, causing scenarios to bleed into each other.
This was causing currently in-progress Bugsnag AGP tests to fail, which are now resolved.
> Clear environment Before each scenario

- CHANGELOG.md
- Gemfile.lock
- UPGRADING.md
- lib/version.rb
> Document change of ECR repository

- Gemfile.lock
- lib/version.rb
> Release v3.3.0

- .buildkite/pipeline.yml
- CHANGELOG.md
- lib/features/support/servlet.rb
Just a tweak to the main pipeline to get faster feedback on the unit tests.  I was a bit too slow to include it on the last PR.
> Pipeline updated for faster feedback on unit tests

- CHANGELOG.md
- Gemfile.lock
- lib/version.rb
> Prepare for 3.5.0

- lib/features/steps/error_reporting_steps.rb
The documented type for this is currently a Hash but it's actually an Integer
https://bugsnag.github.io/maze-runner/top-level-namespace.html#test_unhandled_state-instance_method
> Fix documented type in test_unhandled_state

- CONTRIBUTING.md
Document the steps currently taken whist making a release.
> Guide to making releases

- CHANGELOG.md
- Gemfile.lock
- lib/features/support/hooks.rb
- lib/maze.rb
- lib/maze/driver/resilient_appium.rb
- lib/maze/request_list.rb
Corrects snd improves some logging, using Buildkite's collapsed logging feature when outputting requests at the end of failed scenarios.
> Logging corrections and improvements

- CHANGELOG.md
- lib/features/steps/browser_steps.rb
- lib/features/support/hooks.rb
- lib/maze/capabilities.rb
- lib/maze/configuration.rb
- lib/maze/option/processor.rb
- lib/maze/option/validator.rb
- lib/maze/sauce_labs_utils.rb
- test/option/processor_test.rb
The Maze Runner v5.0.0 had some rough edges (but consciously so for the benefit of an early release).  This PR round off some of those edges, correcting the processing of some command line options and improving input validation.
This PR "banks" a number of improvements, but there are likely to be further change sets before we make the next release.
Covered by CI.
> User interface refinements and validation

- CHANGELOG.md
- lib/features/support/hooks.rb
Corrects the logging of received requests so that the heading appears over every request.
> Correct logging of request heading

- CHANGELOG.md
- lib/features/steps/header_steps.rb
Adds a Cucumber step to check for null headers.
> Add header is null step

- Gemfile.lock
- docker-compose.yml
- test/fixtures/android-appium-test/app/build.gradle
- test/fixtures/android-appium-test/app/src/main/java/com/bugsnag/android/mazerunner/MainActivity.kt
Updates target Bugsnag Android version and adds minor debugging to test fixture.
Suggested run commands are:
```
BRANCH_NAME=integration/bitbar docker-compose build android-appium-test
```
```
BITBAR_USERNAME= BITBAR_ACCESS_KEY= docker-compose run android-appium-test bundle exec maze-runner --farm=bb --device=ANDROID_11_0 --os=android --app=app/build/outputs/apk/release/app-release.apk
```
> BitBar/Android: Update test app to enable bitbar support

- CHANGELOG.md
- Gemfile.lock
- lib/features/steps/value_steps.rb
- lib/maze.rb
- test/fixtures/comparison/features/scripts/send_request.sh
- test/fixtures/comparison/features/test_across_requests.feature
Add new steps to compare against stored values, ignoring case.
Covered by CI and I also verified that the test failed if the `downcase!` lines were removed from the new steps.
> New steps to compare against stored values, ignoring case

- CHANGELOG.md
- lib/maze/option/processor.rb
- lib/maze/option/validator.rb
- test/option/validator_test.rb
Ensure OS and OS version are provided for Sauce Labs.  
These are needed to populate the `platformName` and `platformVersion` capabilities.
Additional validation code.
Covered by new unit tests.
> Ensure OS and OS version are provided

- CHANGELOG.md
- Gemfile.lock
- lib/features/steps/app_automator_steps.rb
- lib/maze.rb
Add new step to background the app indefinitely.
Tested locally.
> Add new step to background the app indefinitely

- CHANGELOG.md
- bin/maze-runner
- lib/features/support/internal_hooks.rb
- lib/maze.rb
- lib/maze/driver/appium.rb
- lib/maze/timers.rb
- test/timer_test.rb
Add general simple timer mechanism, with specific application to select Appium operations.
This will help pipelines understand where automation operations are taking time, hopefully allowing us/them to make performance improvements.
New `Timer` and `Timers` classes, with use woven into the Cucumber hooks and Appium driver.
Covered by unit tests and by inspection of the CI build for this PR.
> Add timer mechanism

- .buildkite/pipeline.yml
Increase BrowserStack slots to 24.
Covered by CI.
> Increase BrowserStack slots to 24

- CHANGELOG.md
- lib/features/support/internal_hooks.rb
Include scenario location in folded output.
Covered by CI.
> Include scenario location in folded output

- CHANGELOG.md
- Gemfile.lock
- lib/maze.rb
- lib/maze/driver/appium.rb
- lib/maze/driver/browser.rb
Fixes an issue where browser and appium drivers initialising without any custom capabilities were failing.
> Add default to capabilities in appium/browser drivers

- CHANGELOG.md
- Gemfile.lock
- lib/maze.rb
- lib/maze/client/appium/bb_client.rb
- lib/maze/client/appium/bs_client.rb
- lib/maze/configuration.rb
- lib/maze/hooks/appium_hooks.rb
- lib/maze/option/processor.rb
- lib/maze/servlets/command_servlet.rb
Fixes various issues with the W3C protocol upgrade, having embarked on porting bugsnag-android to use Maze v7.
Covered by CI and from local testing with bugsnag-android.
> Various fixes

- CHANGELOG.md
- lib/features/steps/network_steps.rb
- lib/features/support/internal_hooks.rb
- lib/maze/server.rb
- lib/maze/servlets/servlet.rb
- lib/maze/servlets/trace_servlet.rb
- test/fixtures/payload-helpers/features/steps/scripting_steps.rb
- test/fixtures/payload-helpers/features/traces_support.feature
Adds the Cucumber step `I set the sampling probability for the next traces to {string}`.
Converts the existing sampling probably steps to use the `Generator` introduced in #424.
e2e tests updated.
> Handle lists of sampling probabilities to return

- CHANGELOG.md
- lib/features/steps/error_reporting_steps.rb
- lib/features/steps/payload_steps.rb
- test/fixtures/android-appium-test/features/handled_exception.feature
Add new Cucumber steps for checking float/double values in error payloads.
New steps added to existing tests run in CI.
> Add steps for checking float values

- .buildkite/pipeline.yml
- CHANGELOG.md
- docker-compose.yml
- lib/maze/client/selenium/bs_client.rb
- test/fixtures/browser/Dockerfile
- test/fixtures/browser/Dockerfile.legacy
- test/fixtures/browser/Dockerfile.w3c
Fixes an issue in the browser client code introduced in a recent refactor.
Before making any code changes I updated the pipeline to be sure of reproducing the error and to avoid future regression.
Covered by new and existing CI tests.
> Fix legacy browser mode

- test/fixtures/docker-app/features/run_docker_services.feature
Skip some recently added scenarios that have turned out to be very flaky on CI.
Covered by CI.
> Skip flaky scenarios

- CHANGELOG.md
- lib/maze/client/appium/bb_client.rb
- lib/maze/client/appium/bb_devices.rb
Tidy Bitbar capabilities.
A few tweaks to avoid warning in the Appium logs and to bring the caps more in line with what happens on BrowserStack by default.
Covered by CI.
> Tidy capabilities for BitBar

- CHANGELOG.md
- Gemfile.lock
- lib/maze.rb
- lib/maze/servlets/base_servlet.rb
Enable required headers in trace payload
> Add Bugsnag-Span-Sampling to Access-Control-Allow-Headers

- .buildkite/pipeline.yml
Build and push the Maze Runner Gem to RubyGems on release.
Tested on this branch by simply having the step unguarded by a condition, resulting in successful publishing:
> Push to RubyGems.org on release

- CHANGELOG.md
- Gemfile.lock
- lib/features/steps/trace_steps.rb
- lib/maze.rb
Fixes an issue blocking Cocoa performance tests using a couple of specific steps.
Note - this won't fix everything across the board, and further work is being ticketed to refactor the steps for proper testing.
> Fix issue causing nil access error in some span steps

- CHANGELOG.md
- lib/features/steps/app_automator_steps.rb
- lib/features/support/cucumber_types.rb
- test/fixtures/android-appium-test/features/handled_exception.feature
Add a new step to control the device orientation in Appium tests.
New steps added to CI.
> Add step `I set the device orientation to {orientation}`

- CHANGELOG.md
- Gemfile.lock
> Release 7.34.0

- CHANGELOG.md
- Gemfile.lock
- lib/maze.rb
Corrects the changelog and version for 8.1.0, which apparently I never actually released.
Covered by CI.
> Release 8.1.0

- CHANGELOG.md
- Gemfile.lock
- lib/maze.rb
- lib/maze/client/appium/bb_client.rb
> Set a sensible timeout for BitBar Appium sessions

- CHANGELOG.md
- Gemfile.lock
- lib/maze.rb
- lib/maze/servlets/servlet.rb
Third attempt following #565 and #566.
Covered by CI and rerunning another Unity test.
> Correct logic for HTTP response codes to session requests

- CHANGELOG.md
- Gemfile.lock
- lib/maze.rb
- lib/maze/bugsnag_config.rb
- lib/maze/driver/appium.rb
- lib/maze/servlets/log_servlet.rb
- lib/maze/servlets/reflective_servlet.rb
- lib/maze/servlets/servlet.rb
- test/fixtures/http-response/features/support/env.rb
A few improvements to the logging and monitoring of errors:
- Errors logged to the console for invalid requests made clearer
- App version added to the BugSnag integration, allowing us to "fix" errors as appropriate
- Removed a source of double reporting
- Disabled BugSnag for self-tests that force an error condition 
Covered by CI and inspection of the BugSnag dashboard.
> Improvements to error logging and monitoring

- CHANGELOG.md
- Gemfile.lock
- UPGRADING.md
- lib/maze.rb
- lib/maze/client/appium/bs_devices.rb
- lib/maze/client/selenium/bs_browsers.yml
Enable testing on IOS 17 devices on BS
Add IOS devices ( iPhone 15, 15 Pro and 15 Pro Max ) to available devices
Covered by CI
> Add IOS 17 devices to BS devices

- CHANGELOG.md
- Gemfile.lock
- lib/maze.rb
- lib/maze/client/appium/bs_client.rb
Corrects an error caused by an undefined variable - introduced in v8.10.0.
Verified by peer review.
> Correct error: undefined local variable or method `config'

- lib/maze/servlets/command_servlet.rb
Remove debug logging line.
Covered by CI.
> Remove debug logging line

- .buildkite/pipeline.yml
Correct version number in Docker tag.
Covered by CI.
> Correct version number in Docker tag

- .buildkite/pipeline.yml
- Gemfile.lock
- bugsnag-maze-runner.gemspec
Use macOS 14 build servers.
I've also bumped the two submodules.
Covered by CI.
> Use macOS 14 build servers

- .buildkite/pipeline.yml
Remove ruby 2 tests on CI
Covered by CI
> [PLAT-12352] Remove Ruby 2 tests

- Gemfile
- bin/maze-runner
- bugsnag-maze-runner.gemspec
- lib/maze/client/bugsnag/data_access_api.rb
- lib/maze/configuration.rb
- lib/maze/option.rb
- lib/maze/option/parser.rb
Also adds basic method of retrieving an event from the API
> Hackathon - Add Data Access API gem and configuration 

- .buildkite/pipeline.yml
Update the submodules used for e2e test fixtures.  The motivation is to make it easier to search for direct uses of "Maze.driver" in this repo as they are currently picked up in those submodules by my IDE.
Covered by CI.
> Update the submodules used for e2e test fixtures
